// i18n support for Easier Research
import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'es' | 'fr' | 'de' | 'ja' | 'ko' | 'pt' | 'ar' | 'hi' | 'ru' | 'it';

export const LANGUAGES: { code: Language; name: string; nativeName: string; dir?: 'rtl' | 'ltr' }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
];

type TranslationDict = Record<string, Record<Language, string>>;

const translations: TranslationDict = {
  // Brand
  'brand.name': { en: 'Easier Research', zh: '轻易研究', es: 'Easier Research', fr: 'Easier Research', de: 'Easier Research', ja: 'Easier Research', ko: 'Easier Research', pt: 'Easier Research', ar: 'Easier Research', hi: 'Easier Research', ru: 'Easier Research', it: 'Easier Research' },
  'brand.copyright': { en: '© 2026 Easier Research. All rights reserved.', zh: '© 2026 轻易研究。保留所有权利。', es: '© 2026 Easier Research. Todos los derechos reservados.', fr: '© 2026 Easier Research. Tous droits réservés.', de: '© 2026 Easier Research. Alle Rechte vorbehalten.', ja: '© 2026 Easier Research. All rights reserved.', ko: '© 2026 Easier Research. 모든 권리 보유.', pt: '© 2026 Easier Research. Todos os direitos reservados.', ar: '© 2026 Easier Research. جميع الحقوق محفوظة.', hi: '© 2026 Easier Research. सर्वाधिकार सुरक्षित।', ru: '© 2026 Easier Research. Все права защищены.', it: '© 2026 Easier Research. Tutti i diritti riservati.' },

  // Landing page
  'landing.hero.title1': { en: 'Research made', zh: '让研究变得', es: 'Investigación', fr: 'La recherche', de: 'Forschung', ja: 'リサーチを', ko: '연구를', pt: 'Pesquisa', ar: 'البحث أصبح', hi: 'शोध को बनाएं', ru: 'Исследования', it: 'La ricerca' },
  'landing.hero.title2': { en: 'easier', zh: '更轻易', es: 'más fácil', fr: 'simplifiée', de: 'leicht gemacht', ja: 'もっと簡単に', ko: '더 쉽게', pt: 'mais fácil', ar: 'أسهل', hi: 'आसान', ru: 'проще', it: 'più facile' },
  'landing.hero.subtitle': { en: 'Create surveys, collect quality data, and analyze results — all in one place.', zh: '创建问卷、收集高质量数据并分析结果——尽在一处。', es: 'Crea encuestas, recopila datos de calidad y analiza resultados.', fr: 'Créez des sondages, collectez des données de qualité et analysez les résultats.', de: 'Erstellen Sie Umfragen, sammeln Sie Daten und analysieren Sie Ergebnisse.', ja: 'アンケートを作成し、質の高いデータを収集し、結果を分析。', ko: '설문조사를 만들고, 양질의 데이터를 수집하고, 결과를 분석하세요.', pt: 'Crie pesquisas, colete dados de qualidade e analise resultados.', ar: 'أنشئ استطلاعات، واجمع بيانات عالية الجودة، وحلل النتائج.', hi: 'सर्वेक्षण बनाएं, गुणवत्तापूर्ण डेटा एकत्र करें, और परिणामों का विश्लेषण करें।', ru: 'Создавайте опросы, собирайте данные и анализируйте результаты.', it: 'Crea sondaggi, raccogli dati di qualità e analizza i risultati.' },
  'landing.getStarted': { en: 'Get started', zh: '开始使用', es: 'Comenzar', fr: 'Commencer', de: 'Loslegen', ja: '始める', ko: '시작하기', pt: 'Começar', ar: 'ابدأ الآن', hi: 'शुरू करें', ru: 'Начать', it: 'Inizia' },
  'landing.browseTemplates': { en: 'Browse templates', zh: '浏览模板', es: 'Ver plantillas', fr: 'Voir les modèles', de: 'Vorlagen ansehen', ja: 'テンプレートを見る', ko: '템플릿 보기', pt: 'Ver modelos', ar: 'تصفح القوالب', hi: 'टेम्पलेट देखें', ru: 'Шаблоны', it: 'Sfoglia modelli' },
  'landing.freeForever': { en: 'Free forever · No credit card required', zh: '永久免费 · 无需信用卡', es: 'Gratis para siempre · Sin tarjeta de crédito', fr: 'Gratuit pour toujours · Aucune carte requise', de: 'Für immer kostenlos · Keine Kreditkarte', ja: '永久無料・クレジットカード不要', ko: '영원히 무료 · 신용카드 불필요', pt: 'Grátis para sempre · Sem cartão', ar: 'مجاني للأبد · لا حاجة لبطاقة ائتمان', hi: 'हमेशा मुफ्त · क्रेडिट कार्ड नहीं', ru: 'Бесплатно навсегда · Карта не нужна', it: 'Gratis per sempre · Nessuna carta' },
  'landing.features.title': { en: 'Everything you need', zh: '您需要的一切', es: 'Todo lo que necesitas', fr: 'Tout ce dont vous avez besoin', de: 'Alles was Sie brauchen', ja: '必要なものすべて', ko: '필요한 모든 것', pt: 'Tudo o que você precisa', ar: 'كل ما تحتاجه', hi: 'आपको जो कुछ भी चाहिए', ru: 'Всё, что вам нужно', it: 'Tutto ciò di cui hai bisogno' },
  'landing.features.subtitle': { en: 'Powerful tools, zero complexity.', zh: '强大的工具，零复杂度。', es: 'Herramientas poderosas, cero complejidad.', fr: 'Des outils puissants, zéro complexité.', de: 'Leistungsstarke Tools, null Komplexität.', ja: '強力なツール、ゼロの複雑さ。', ko: '강력한 도구, 제로 복잡성.', pt: 'Ferramentas poderosas, complexidade zero.', ar: 'أدوات قوية، صفر تعقيد.', hi: 'शक्तिशाली उपकरण, शून्य जटिलता।', ru: 'Мощные инструменты, ноль сложности.', it: 'Strumenti potenti, zero complessità.' },
  'landing.howItWorks': { en: 'Three steps', zh: '三个步骤', es: 'Tres pasos', fr: 'Trois étapes', de: 'Drei Schritte', ja: '3つのステップ', ko: '세 단계', pt: 'Três passos', ar: 'ثلاث خطوات', hi: 'तीन चरण', ru: 'Три шага', it: 'Tre passaggi' },
  'landing.useCases.title': { en: 'Built for every field', zh: '为每个领域而建', es: 'Creado para cada campo', fr: 'Conçu pour tous les domaines', de: 'Für jedes Fachgebiet', ja: 'あらゆる分野に対応', ko: '모든 분야를 위해', pt: 'Feito para todos os campos', ar: 'مصمم لكل مجال', hi: 'हर क्षेत्र के लिए', ru: 'Для любой области', it: 'Per ogni settore' },
  'landing.cta.title': { en: 'Ready to start?', zh: '准备开始了吗？', es: '¿Listo para comenzar?', fr: 'Prêt à commencer ?', de: 'Bereit loszulegen?', ja: '始める準備はできましたか？', ko: '시작할 준비가 되셨나요?', pt: 'Pronto para começar?', ar: 'مستعد للبدء؟', hi: 'शुरू करने के लिए तैयार?', ru: 'Готовы начать?', it: 'Pronto per iniziare?' },
  'landing.cta.subtitle': { en: 'Join researchers who trust Easier for their studies.', zh: '加入信赖 Easier 的研究人员。', es: 'Únete a investigadores que confían en Easier.', fr: 'Rejoignez les chercheurs qui font confiance à Easier.', de: 'Schließen Sie sich Forschern an.', ja: 'Easierを信頼する研究者に加わりましょう。', ko: 'Easier를 신뢰하는 연구자들과 함께하세요.', pt: 'Junte-se a pesquisadores que confiam no Easier.', ar: 'انضم إلى الباحثين الذين يثقون بـ Easier.', hi: 'Easier पर भरोसा करने वालों से जुड़ें।', ru: 'Присоединяйтесь к исследователям.', it: 'Unisciti ai ricercatori che si fidano di Easier.' },
  'landing.cta.button': { en: 'Create your first survey', zh: '创建您的第一个问卷', es: 'Crea tu primera encuesta', fr: 'Créez votre premier sondage', de: 'Erstellen Sie Ihre erste Umfrage', ja: '最初のアンケートを作成', ko: '첫 설문조사를 만드세요', pt: 'Crie sua primeira pesquisa', ar: 'أنشئ استطلاعك الأول', hi: 'अपना पहला सर्वेक्षण बनाएं', ru: 'Создайте свой первый опрос', it: 'Crea il tuo primo sondaggio' },

  // AI Features section
  'landing.ai.title': { en: 'Built-in AI Features', zh: '内置AI功能', es: 'Funciones de IA integradas', fr: 'Fonctionnalités IA intégrées', de: 'Eingebaute KI-Funktionen', ja: '内蔵AIFeatures', ko: '내장 AI 기능', pt: 'Recursos de IA integrados', ar: 'ميزات الذكاء الاصطناعي المدمجة', hi: 'अंतर्निहित AI सुविधाएँ', ru: 'Встроенные функции ИИ', it: 'Funzionalità IA integrate' },
  'landing.ai.subtitle': { en: 'AI writes survey questions from your topic', zh: 'AI根据您的主题自动生成问卷问题', es: 'La IA escribe preguntas desde tu tema', fr: "L'IA écrit les questions depuis votre sujet", de: 'KI schreibt Umfragefragen aus Ihrem Thema', ja: 'AIがトピックから質問を作成', ko: 'AI가 주제에서 질문 작성', pt: 'IA escreve perguntas do seu tema', ar: 'الذكاء الاصطناعي يكتب الأسئلة من موضوعك', hi: 'AI आपके विषय से प्रश्न लिखता है', ru: 'ИИ пишет вопросы по вашей теме', it: "L'IA scrive domande dal tuo argomento" },
  'landing.ai.cta': { en: 'Participants answer by voice or chatbot', zh: '参与者可通过语音或聊天机器人回答', es: 'Los participantes responden por voz o chatbot', fr: 'Les participants répondent par voix ou chatbot', de: 'Teilnehmer antworten per Sprache oder Chatbot', ja: '参加者は音声やチャットボットで回答', ko: '참가자는 음성이나 챗봇으로 답변', pt: 'Participantes respondem por voz ou chatbot', ar: 'المشاركون يجيبون بالصوت أو الشات بوت', hi: 'प्रतिभागी आवाज या चैटबॉट से जवाब देते हैं', ru: 'Участники отвечают голосом или через чат-бот', it: 'I partecipanti rispondono con voce o chatbot' },
  'landing.ai.fullDesc': { en: 'Describe your research topic and AI generates a complete questionnaire. Participants can speak answers or chat with an AI assistant instead of typing.', zh: '描述您的研究主题，AI即可生成完整问卷。参与者可以用语音回答或与AI助手聊天，无需手动输入。', es: 'Describe tu tema y la IA genera un cuestionario completo.', fr: "Décrivez votre sujet et l'IA génère un questionnaire complet.", de: 'Beschreiben Sie Ihr Thema und KI erstellt einen Fragebogen.', ja: 'トピックを説明すると、AIが完全なアンケートを生成します。', ko: '주제를 설명하면 AI가 완전한 설문지를 생성합니다.', pt: 'Descreva seu tema e a IA gera um questionário completo.', ar: 'صف موضوع بحثك وسيقوم الذكاء الاصطناعي بإنشاء استبيان كامل.', hi: 'अपने विषय का वर्णन करें और AI एक पूर्ण प्रश्नावली बनाता है।', ru: 'Опишите тему, и ИИ создаст полную анкету.', it: "Descrivi il tuo argomento e l'IA genera un questionario completo." },
  'landing.ai.voiceDesc': { en: 'Voice input available for participants', zh: '参与者可使用语音输入', es: 'Entrada de voz disponible', fr: 'Entrée vocale disponible', de: 'Spracheingabe verfügbar', ja: '音声入力対応', ko: '음성 입력 가능', pt: 'Entrada de voz disponível', ar: 'إدخال صوتي متاح', hi: 'वॉयस इनपुट उपलब्ध', ru: 'Голосовой ввод доступен', it: 'Input vocale disponibile' },
  'landing.ai.cap1': { en: 'AI generates questions from your topic', zh: 'AI根据主题生成问题', es: 'IA genera preguntas de tu tema', fr: "L'IA génère des questions", de: 'KI generiert Fragen', ja: 'AIが質問を生成', ko: 'AI가 질문 생성', pt: 'IA gera perguntas', ar: 'الذكاء الاصطناعي يولد الأسئلة', hi: 'AI प्रश्न उत्पन्न करता है', ru: 'ИИ генерирует вопросы', it: "L'IA genera domande" },
  'landing.ai.cap2': { en: 'Voice input — speak instead of type', zh: '语音输入——说话代替打字', es: 'Entrada de voz — habla en lugar de escribir', fr: 'Entrée vocale — parlez au lieu de taper', de: 'Spracheingabe — sprechen statt tippen', ja: '音声入力 — タイプの代わりに話す', ko: '음성 입력 — 타이핑 대신 말하기', pt: 'Entrada de voz — fale em vez de digitar', ar: 'إدخال صوتي — تحدث بدلاً من الكتابة', hi: 'वॉयस इनपुट — टाइप करने के बजाय बोलें', ru: 'Голосовой ввод — говорите вместо печати', it: 'Input vocale — parla invece di digitare' },
  'landing.ai.cap3': { en: 'Chatbot helps participants answer', zh: '聊天机器人帮助参与者回答', es: 'Chatbot ayuda a los participantes', fr: 'Chatbot aide les participants', de: 'Chatbot hilft Teilnehmern', ja: 'チャットボットが参加者を支援', ko: '챗봇이 참가자를 도움', pt: 'Chatbot ajuda participantes', ar: 'روبوت الدردشة يساعد المشاركين', hi: 'चैटबॉट प्रतिभागियों की मदद करता है', ru: 'Чат-бот помогает участникам', it: 'Chatbot aiuta i partecipanti' },
  'landing.ai.tryButton': { en: 'Try it free', zh: '免费试用', es: 'Probar gratis', fr: 'Essayer gratuitement', de: 'Kostenlos ausprobieren', ja: '無料で試す', ko: '무료로 시도', pt: 'Experimentar grátis', ar: 'جرب مجاناً', hi: 'मुफ्त आज़माएं', ru: 'Попробовать бесплатно', it: 'Prova gratis' },

  // Common
  'common.back': { en: 'Back', zh: '返回', es: 'Atrás', fr: 'Retour', de: 'Zurück', ja: '戻る', ko: '뒤로', pt: 'Voltar', ar: 'رجوع', hi: 'वापस', ru: 'Назад', it: 'Indietro' },
  'common.next': { en: 'Next', zh: '下一步', es: 'Siguiente', fr: 'Suivant', de: 'Weiter', ja: '次へ', ko: '다음', pt: 'Próximo', ar: 'التالي', hi: 'अगला', ru: 'Далее', it: 'Avanti' },
  'common.submit': { en: 'Submit', zh: '提交', es: 'Enviar', fr: 'Soumettre', de: 'Absenden', ja: '送信', ko: '제출', pt: 'Enviar', ar: 'إرسال', hi: 'जमा करें', ru: 'Отправить', it: 'Invia' },
  'common.cancel': { en: 'Cancel', zh: '取消', es: 'Cancelar', fr: 'Annuler', de: 'Abbrechen', ja: 'キャンセル', ko: '취소', pt: 'Cancelar', ar: 'إلغاء', hi: 'रद्द करें', ru: 'Отмена', it: 'Annulla' },
  'common.save': { en: 'Save', zh: '保存', es: 'Guardar', fr: 'Enregistrer', de: 'Speichern', ja: '保存', ko: '저장', pt: 'Salvar', ar: 'حفظ', hi: 'सहेजें', ru: 'Сохранить', it: 'Salva' },
  'common.loading': { en: 'Loading...', zh: '加载中...', es: 'Cargando...', fr: 'Chargement...', de: 'Laden...', ja: '読み込み中...', ko: '로딩 중...', pt: 'Carregando...', ar: 'جاري التحميل...', hi: 'लोड हो रहा है...', ru: 'Загрузка...', it: 'Caricamento...' },
  'common.signIn': { en: 'Sign In', zh: '登录', es: 'Iniciar sesión', fr: 'Se connecter', de: 'Anmelden', ja: 'ログイン', ko: '로그인', pt: 'Entrar', ar: 'تسجيل الدخول', hi: 'साइन इन', ru: 'Войти', it: 'Accedi' },
  'common.signOut': { en: 'Sign Out', zh: '退出登录', es: 'Cerrar sesión', fr: 'Se déconnecter', de: 'Abmelden', ja: 'ログアウト', ko: '로그아웃', pt: 'Sair', ar: 'تسجيل الخروج', hi: 'साइन आउट', ru: 'Выйти', it: 'Esci' },
  'common.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'common.search': { en: 'Search', zh: '搜索', es: 'Buscar', fr: 'Rechercher', de: 'Suchen', ja: '検索', ko: '검색', pt: 'Buscar', ar: 'بحث', hi: 'खोजें', ru: 'Поиск', it: 'Cerca' },
  'common.delete': { en: 'Delete', zh: '删除', es: 'Eliminar', fr: 'Supprimer', de: 'Löschen', ja: '削除', ko: '삭제', pt: 'Excluir', ar: 'حذف', hi: 'हटाएं', ru: 'Удалить', it: 'Elimina' },
  'common.edit': { en: 'Edit', zh: '编辑', es: 'Editar', fr: 'Modifier', de: 'Bearbeiten', ja: '編集', ko: '편집', pt: 'Editar', ar: 'تعديل', hi: 'संपादित करें', ru: 'Редактировать', it: 'Modifica' },
  'common.confirm': { en: 'Confirm', zh: '确认', es: 'Confirmar', fr: 'Confirmer', de: 'Bestätigen', ja: '確認', ko: '확인', pt: 'Confirmar', ar: 'تأكيد', hi: 'पुष्टि करें', ru: 'Подтвердить', it: 'Conferma' },
  'common.done': { en: 'Done', zh: '完成', es: 'Hecho', fr: 'Terminé', de: 'Fertig', ja: '完了', ko: '완료', pt: 'Concluído', ar: 'تم', hi: 'पूर्ण', ru: 'Готово', it: 'Fatto' },
  'common.close': { en: 'Close', zh: '关闭', es: 'Cerrar', fr: 'Fermer', de: 'Schließen', ja: '閉じる', ko: '닫기', pt: 'Fechar', ar: 'إغلاق', hi: 'बंद करें', ru: 'Закрыть', it: 'Chiudi' },
  'common.open': { en: 'Open', zh: '打开', es: 'Abrir', fr: 'Ouvrir', de: 'Öffnen', ja: '開く', ko: '열기', pt: 'Abrir', ar: 'فتح', hi: 'खोलें', ru: 'Открыть', it: 'Apri' },
  'common.more': { en: 'More', zh: '更多', es: 'Más', fr: 'Plus', de: 'Mehr', ja: 'もっと見る', ko: '더보기', pt: 'Mais', ar: 'المزيد', hi: 'और', ru: 'Больше', it: 'Altro' },
  'common.less': { en: 'Less', zh: '更少', es: 'Menos', fr: 'Moins', de: 'Weniger', ja: '少なく', ko: '덜', pt: 'Menos', ar: 'أقل', hi: 'कम', ru: 'Меньше', it: 'Meno' },
  'common.yes': { en: 'Yes', zh: '是', es: 'Sí', fr: 'Oui', de: 'Ja', ja: 'はい', ko: '예', pt: 'Sim', ar: 'نعم', hi: 'हाँ', ru: 'Да', it: 'Sì' },
  'common.no': { en: 'No', zh: '否', es: 'No', fr: 'Non', de: 'Nein', ja: 'いいえ', ko: '아니요', pt: 'Não', ar: 'لا', hi: 'नहीं', ru: 'Нет', it: 'No' },
  'common.all': { en: 'All', zh: '所有', es: 'Todos', fr: 'Tous', de: 'Alle', ja: 'すべて', ko: '모두', pt: 'Todos', ar: 'الكل', hi: 'सभी', ru: 'Все', it: 'Tutti' },

  // Navigation
  'nav.research': { en: 'Research', zh: '研究', es: 'Investigación', fr: 'Recherche', de: 'Forschung', ja: '研究', ko: '연구', pt: 'Pesquisa', ar: 'البحث', hi: 'शोध', ru: 'Исследования', it: 'Ricerca' },
  'nav.discover': { en: 'Discover', zh: '发现', es: 'Descubrir', fr: 'Découvrir', de: 'Entdecken', ja: '発見', ko: '발견', pt: 'Descobrir', ar: 'اكتشف', hi: 'खोजें', ru: 'Обзор', it: 'Scopri' },
  'nav.inbox': { en: 'Inbox', zh: '收件箱', es: 'Bandeja de entrada', fr: 'Boîte de réception', de: 'Posteingang', ja: '受信箱', ko: '받은편지함', pt: 'Caixa de entrada', ar: 'صندوق الوارد', hi: 'इनबॉक्स', ru: 'Входящие', it: 'Posta' },
  'nav.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'nav.dashboard': { en: 'Dashboard', zh: '仪表板', es: 'Panel', fr: 'Tableau de bord', de: 'Dashboard', ja: 'ダッシュボード', ko: '대시보드', pt: 'Painel', ar: 'لوحة التحكم', hi: 'डैशबोर्ड', ru: 'Панель', it: 'Pannello' },
  'nav.participants': { en: 'Participants', zh: '参与者', es: 'Participantes', fr: 'Participants', de: 'Teilnehmer', ja: '参加者', ko: '참가자', pt: 'Participantes', ar: 'المشاركون', hi: 'प्रतिभागी', ru: 'Участники', it: 'Partecipanti' },
  'nav.joinStudies': { en: 'Join Studies', zh: '参与研究', es: 'Unirse a estudios', fr: 'Rejoindre des études', de: 'Studien beitreten', ja: '研究に参加', ko: '연구 참여', pt: 'Participar de estudos', ar: 'انضم إلى الدراسات', hi: 'अध्ययन में शामिल हों', ru: 'Присоединиться', it: 'Partecipa agli studi' },
  'nav.features': { en: 'Features', zh: '功能', es: 'Características', fr: 'Fonctionnalités', de: 'Funktionen', ja: '機能', ko: '기능', pt: 'Recursos', ar: 'الميزات', hi: 'सुविधाएँ', ru: 'Возможности', it: 'Funzionalità' },
  'nav.templates': { en: 'Templates', zh: '模板', es: 'Plantillas', fr: 'Modèles', de: 'Vorlagen', ja: 'テンプレート', ko: '템플릿', pt: 'Modelos', ar: 'القوالب', hi: 'टेम्पलेट', ru: 'Шаблоны', it: 'Modelli' },
  'nav.home': { en: 'Home', zh: '首页', es: 'Inicio', fr: 'Accueil', de: 'Startseite', ja: 'ホーム', ko: '홈', pt: 'Início', ar: 'الرئيسية', hi: 'होम', ru: 'Главная', it: 'Home' },

  // Auth
  'auth.welcomeBack': { en: 'Welcome back', zh: '欢迎回来', es: 'Bienvenido de nuevo', fr: 'Bon retour', de: 'Willkommen zurück', ja: 'おかえりなさい', ko: '다시 오신 것을 환영합니다', pt: 'Bem-vindo de volta', ar: 'مرحبًا بعودتك', hi: 'वापसी पर स्वागत', ru: 'С возвращением', it: 'Bentornato' },
  'auth.createAccount': { en: 'Create Account', zh: '创建账户', es: 'Crear cuenta', fr: 'Créer un compte', de: 'Konto erstellen', ja: 'アカウント作成', ko: '계정 만들기', pt: 'Criar conta', ar: 'إنشاء حساب', hi: 'खाता बनाएं', ru: 'Создать аккаунт', it: 'Crea account' },
  'auth.startCreating': { en: 'Start creating surveys in minutes', zh: '几分钟内开始创建问卷', es: 'Comienza a crear encuestas en minutos', fr: 'Commencez à créer des sondages', de: 'Erstellen Sie Umfragen in Minuten', ja: '数分でアンケート作成を開始', ko: '몇 분 안에 설문조사 만들기', pt: 'Comece a criar pesquisas em minutos', ar: 'ابدأ بإنشاء استطلاعات في دقائق', hi: 'मिनटों में सर्वेक्षण बनाना शुरू करें', ru: 'Начните создавать опросы за минуты', it: 'Inizia a creare sondaggi in pochi minuti' },
  'auth.signInToContinue': { en: 'Sign in to continue', zh: '登录以继续', es: 'Inicia sesión para continuar', fr: 'Connectez-vous pour continuer', de: 'Anmelden um fortzufahren', ja: 'サインインして続行', ko: '로그인하여 계속', pt: 'Entre para continuar', ar: 'سجل الدخول للمتابعة', hi: 'जारी रखने के लिए साइन इन करें', ru: 'Войдите для продолжения', it: 'Accedi per continuare' },
  'auth.iWantTo': { en: 'I want to...', zh: '我想要...', es: 'Quiero...', fr: 'Je veux...', de: 'Ich möchte...', ja: '私は...', ko: '나는...', pt: 'Eu quero...', ar: 'أريد أن...', hi: 'मैं चाहता/चाहती हूँ...', ru: 'Я хочу...', it: 'Voglio...' },
  'auth.participate': { en: 'Participate', zh: '参与研究', es: 'Participar', fr: 'Participer', de: 'Teilnehmen', ja: '参加する', ko: '참여하기', pt: 'Participar', ar: 'المشاركة', hi: 'भाग लें', ru: 'Участвовать', it: 'Partecipare' },
  'auth.takeSurveys': { en: 'Take surveys & earn rewards', zh: '参与问卷并获取奖励', es: 'Responde encuestas y gana recompensas', fr: 'Répondez aux sondages et gagnez des récompenses', de: 'Umfragen ausfüllen und Belohnungen verdienen', ja: 'アンケートに答えて報酬を得る', ko: '설문조사에 참여하고 보상 받기', pt: 'Responda pesquisas e ganhe recompensas', ar: 'أجب على الاستطلاعات واربح مكافآت', hi: 'सर्वेक्षण लें और पुरस्कार अर्जित करें', ru: 'Проходите опросы и получайте награды', it: 'Rispondi ai sondaggi e guadagna premi' },
  'auth.research': { en: 'Research', zh: '进行研究', es: 'Investigar', fr: 'Rechercher', de: 'Forschen', ja: '研究する', ko: '연구하기', pt: 'Pesquisar', ar: 'البحث', hi: 'शोध करें', ru: 'Исследовать', it: 'Ricercare' },
  'auth.createSurveys': { en: 'Create & manage surveys', zh: '创建和管理问卷', es: 'Crear y gestionar encuestas', fr: 'Créer et gérer des sondages', de: 'Umfragen erstellen und verwalten', ja: 'アンケートを作成・管理', ko: '설문조사 만들기 및 관리', pt: 'Criar e gerenciar pesquisas', ar: 'إنشاء وإدارة الاستطلاعات', hi: 'सर्वेक्षण बनाएं और प्रबंधित करें', ru: 'Создавайте и управляйте опросами', it: 'Crea e gestisci sondaggi' },
  'auth.email': { en: 'Email', zh: '电子邮件', es: 'Correo electrónico', fr: 'E-mail', de: 'E-Mail', ja: 'メール', ko: '이메일', pt: 'E-mail', ar: 'البريد الإلكتروني', hi: 'ईमेल', ru: 'Email', it: 'Email' },
  'auth.password': { en: 'Password', zh: '密码', es: 'Contraseña', fr: 'Mot de passe', de: 'Passwort', ja: 'パスワード', ko: '비밀번호', pt: 'Senha', ar: 'كلمة المرور', hi: 'पासवर्ड', ru: 'Пароль', it: 'Password' },
  'auth.enterEmail': { en: 'Please enter your email', zh: '请输入您的电子邮件', es: 'Ingresa tu correo', fr: 'Entrez votre e-mail', de: 'Bitte E-Mail eingeben', ja: 'メールを入力してください', ko: '이메일을 입력하세요', pt: 'Digite seu e-mail', ar: 'يرجى إدخال بريدك الإلكتروني', hi: 'कृपया अपना ईमेल दर्ज करें', ru: 'Введите ваш email', it: 'Inserisci la tua email' },
  'auth.enterPassword': { en: 'Please enter your password', zh: '请输入您的密码', es: 'Ingresa tu contraseña', fr: 'Entrez votre mot de passe', de: 'Bitte Passwort eingeben', ja: 'パスワードを入力してください', ko: '비밀번호를 입력하세요', pt: 'Digite sua senha', ar: 'يرجى إدخال كلمة المرور', hi: 'कृपया अपना पासवर्ड दर्ज करें', ru: 'Введите пароль', it: 'Inserisci la tua password' },
  'auth.passwordTooShort': { en: 'Password must be at least 6 characters', zh: '密码至少需要6个字符', es: 'La contraseña debe tener al menos 6 caracteres', fr: 'Le mot de passe doit contenir au moins 6 caractères', de: 'Passwort muss mindestens 6 Zeichen haben', ja: 'パスワードは6文字以上必要です', ko: '비밀번호는 6자 이상이어야 합니다', pt: 'A senha deve ter pelo menos 6 caracteres', ar: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل', hi: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए', ru: 'Пароль должен быть не менее 6 символов', it: 'La password deve avere almeno 6 caratteri' },
  'auth.createAccountBtn': { en: 'Create Account', zh: '创建账户', es: 'Crear cuenta', fr: 'Créer un compte', de: 'Konto erstellen', ja: 'アカウント作成', ko: '계정 만들기', pt: 'Criar conta', ar: 'إنشاء حساب', hi: 'खाता बनाएं', ru: 'Создать аккаунт', it: 'Crea account' },
  'auth.alreadyHaveAccount': { en: 'Already have an account? Sign in', zh: '已有账户？登录', es: '¿Ya tienes cuenta? Inicia sesión', fr: 'Déjà un compte ? Connectez-vous', de: 'Schon ein Konto? Anmelden', ja: 'アカウントをお持ちですか？ログイン', ko: '이미 계정이 있으신가요? 로그인', pt: 'Já tem uma conta? Entre', ar: 'لديك حساب بالفعل؟ سجل الدخول', hi: 'पहले से खाता है? साइन इन करें', ru: 'Уже есть аккаунт? Войти', it: 'Hai già un account? Accedi' },
  'auth.noAccount': { en: "Don't have an account? Sign up", zh: '没有账户？注册', es: '¿No tienes cuenta? Regístrate', fr: "Pas de compte ? Inscrivez-vous", de: 'Kein Konto? Registrieren', ja: 'アカウントがありませんか？新規登録', ko: '계정이 없으신가요? 가입하기', pt: 'Não tem conta? Cadastre-se', ar: 'ليس لديك حساب؟ سجّل الآن', hi: 'खाता नहीं है? साइन अप करें', ru: 'Нет аккаунта? Зарегистрируйтесь', it: 'Non hai un account? Registrati' },

  // Dashboard
  'dashboard.myJoinedStudies': { en: 'My Joined Studies', zh: '我参与的研究', es: 'Mis estudios unidos', fr: 'Mes études rejointes', de: 'Beigetretene Studien', ja: '参加した研究', ko: '참여한 연구', pt: 'Estudos participados', ar: 'الدراسات التي انضممت إليها', hi: 'मेरे शामिल अध्ययन', ru: 'Мои исследования', it: 'Studi a cui partecipo' },
  'dashboard.studies': { en: 'studies', zh: '项研究', es: 'estudios', fr: 'études', de: 'Studien', ja: '研究', ko: '연구', pt: 'estudos', ar: 'دراسات', hi: 'अध्ययन', ru: 'исследований', it: 'studi' },
  'dashboard.study': { en: 'study', zh: '项研究', es: 'estudio', fr: 'étude', de: 'Studie', ja: '研究', ko: '연구', pt: 'estudo', ar: 'دراسة', hi: 'अध्ययन', ru: 'исследование', it: 'studio' },
  'dashboard.newStudy': { en: '+ New Study', zh: '+ 新研究', es: '+ Nuevo estudio', fr: '+ Nouvelle étude', de: '+ Neue Studie', ja: '+ 新しい研究', ko: '+ 새 연구', pt: '+ Novo estudo', ar: '+ دراسة جديدة', hi: '+ नया अध्ययन', ru: '+ Новое исследование', it: '+ Nuovo studio' },
  'dashboard.edit': { en: 'Edit', zh: '编辑', es: 'Editar', fr: 'Modifier', de: 'Bearbeiten', ja: '編集', ko: '편집', pt: 'Editar', ar: 'تعديل', hi: 'संपादन', ru: 'Редактировать', it: 'Modifica' },
  'dashboard.owner': { en: 'Owner', zh: '负责人', es: 'Propietario', fr: 'Propriétaire', de: 'Eigentümer', ja: 'オーナー', ko: '소유자', pt: 'Proprietário', ar: 'المالك', hi: 'मालिक', ru: 'Владелец', it: 'Proprietario' },
  'dashboard.participant': { en: 'Participant', zh: '参与者', es: 'Participante', fr: 'Participant', de: 'Teilnehmer', ja: '参加者', ko: '참여자', pt: 'Participante', ar: 'مشارك', hi: 'प्रतिभागी', ru: 'Участник', it: 'Partecipante' },
  'dashboard.signInToStart': { en: 'Sign in to get started', zh: '登录以开始', es: 'Inicia sesión para comenzar', fr: 'Connectez-vous pour commencer', de: 'Melden Sie sich an', ja: 'ログインして始めましょう', ko: '로그인하여 시작하세요', pt: 'Entre para começar', ar: 'سجّل الدخول للبدء', hi: 'शुरू करने के लिए साइन इन करें', ru: 'Войдите, чтобы начать', it: 'Accedi per iniziare' },
  'dashboard.createOrJoin': { en: 'Create or join research studies', zh: '创建或参与研究', es: 'Crea o únete a estudios', fr: 'Créez ou rejoignez des études', de: 'Erstellen oder beitreten', ja: '研究の作成または参加', ko: '연구를 만들거나 참여하세요', pt: 'Crie ou participe de estudos', ar: 'أنشئ أو انضم إلى دراسات', hi: 'अध्ययन बनाएं या शामिल हों', ru: 'Создайте или присоединитесь', it: 'Crea o partecipa a studi' },
  'dashboard.noDescription': { en: 'No description', zh: '暂无描述', es: 'Sin descripción', fr: 'Aucune description', de: 'Keine Beschreibung', ja: '説明なし', ko: '설명 없음', pt: 'Sem descrição', ar: 'بدون وصف', hi: 'कोई विवरण नहीं', ru: 'Без описания', it: 'Nessuna descrizione' },
  'dashboard.noProjects': { en: 'No projects yet', zh: '暂无项目', es: 'Sin proyectos aún', fr: 'Pas encore de projets', de: 'Noch keine Projekte', ja: 'プロジェクトはまだありません', ko: '아직 프로젝트가 없습니다', pt: 'Nenhum projeto ainda', ar: 'لا توجد مشاريع بعد', hi: 'अभी तक कोई प्रोजेक्ट नहीं', ru: 'Пока нет проектов', it: 'Nessun progetto ancora' },

  // Status labels
  'status.draft': { en: 'Draft', zh: '草稿', es: 'Borrador', fr: 'Brouillon', de: 'Entwurf', ja: '下書き', ko: '임시저장', pt: 'Rascunho', ar: 'مسودة', hi: 'ड्राफ्ट', ru: 'Черновик', it: 'Bozza' },
  'status.published': { en: 'Published', zh: '已发布', es: 'Publicado', fr: 'Publié', de: 'Veröffentlicht', ja: '公開中', ko: '게시됨', pt: 'Publicado', ar: 'منشور', hi: 'प्रकाशित', ru: 'Опубликовано', it: 'Pubblicato' },
  'status.active': { en: 'Active', zh: '进行中', es: 'Activo', fr: 'Actif', de: 'Aktiv', ja: 'アクティブ', ko: '활성', pt: 'Ativo', ar: 'نشط', hi: 'सक्रिय', ru: 'Активно', it: 'Attivo' },
  'status.completed': { en: 'Completed', zh: '已完成', es: 'Completado', fr: 'Terminé', de: 'Abgeschlossen', ja: '完了', ko: '완료', pt: 'Concluído', ar: 'مكتمل', hi: 'पूर्ण', ru: 'Завершено', it: 'Completato' },
  'status.paused': { en: 'Paused', zh: '已暂停', es: 'Pausado', fr: 'En pause', de: 'Pausiert', ja: '一時停止', ko: '일시중지', pt: 'Pausado', ar: 'متوقف', hi: 'रुका हुआ', ru: 'Приостановлено', it: 'In pausa' },

  // Project type labels
  'projectType.survey': { en: 'Survey', zh: '问卷', es: 'Encuesta', fr: 'Enquête', de: 'Umfrage', ja: 'アンケート', ko: '설문', pt: 'Pesquisa', ar: 'استبيان', hi: 'सर्वेक्षण', ru: 'Опрос', it: 'Sondaggio' },
  'projectType.longitudinal': { en: 'Longitudinal', zh: '纵向研究', es: 'Longitudinal', fr: 'Longitudinal', de: 'Langzeitstudie', ja: '縦断研究', ko: '종단 연구', pt: 'Longitudinal', ar: 'طولي', hi: 'अनुदैर्ध्य', ru: 'Лонгитюдный', it: 'Longitudinale' },
  'projectType.esm': { en: 'ESM', zh: '经验取样', es: 'ESM', fr: 'ESM', de: 'ESM', ja: 'ESM', ko: 'ESM', pt: 'ESM', ar: 'ESM', hi: 'ESM', ru: 'ESM', it: 'ESM' },
  'projectType.ema': { en: 'EMA', zh: '生态瞬时评估', es: 'EMA', fr: 'EMA', de: 'EMA', ja: 'EMA', ko: 'EMA', pt: 'EMA', ar: 'EMA', hi: 'EMA', ru: 'EMA', it: 'EMA' },

  // AI Chatbot
  'ai.assistant': { en: 'AI Assistant', zh: 'AI 助手', es: 'Asistente IA', fr: 'Assistant IA', de: 'KI-Assistent', ja: 'AIアシスタント', ko: 'AI 어시스턴트', pt: 'Assistente IA', ar: 'مساعد الذكاء الاصطناعي', hi: 'AI सहायक', ru: 'ИИ-ассистент', it: 'Assistente IA' },
  'ai.answered': { en: 'answered', zh: '已回答', es: 'respondidas', fr: 'répondues', de: 'beantwortet', ja: '回答済み', ko: '응답됨', pt: 'respondidas', ar: 'تمت الإجابة', hi: 'उत्तर दिया', ru: 'отвечено', it: 'risposte' },
  'ai.inheritedDesc': { en: 'Inherited from project settings', zh: '继承自项目设置', es: 'Heredado de la configuración del proyecto', fr: 'Hérité des paramètres du projet', de: 'Von Projekteinstellungen geerbt', ja: 'プロジェクト設定から継承', ko: '프로젝트 설정에서 상속', pt: 'Herdado das configurações do projeto', ar: 'موروث من إعدادات المشروع', hi: 'प्रोजेक्ट सेटिंग्स से विरासत में', ru: 'Унаследовано из настроек проекта', it: 'Ereditato dalle impostazioni del progetto' },
  'ai.voiceInputLabel': { en: 'Voice Input', zh: '语音输入', es: 'Entrada de voz', fr: 'Entrée vocale', de: 'Spracheingabe', ja: '音声入力', ko: '음성 입력', pt: 'Entrada de voz', ar: 'إدخال صوتي', hi: 'वॉयस इनपुट', ru: 'Голосовой ввод', it: 'Input vocale' },
  'ai.assistHelpEnhance': { en: 'AI Assist (Help & Enhance)', zh: 'AI辅助（帮助和增强）', es: 'Asistencia IA (Ayuda y Mejora)', fr: "Assistance IA (Aide et Amélioration)", de: 'KI-Assistent (Hilfe & Verbesserung)', ja: 'AIアシスト（ヘルプ＆強化）', ko: 'AI 지원 (도움 및 향상)', pt: 'Assistência IA (Ajuda e Melhoria)', ar: 'مساعدة الذكاء الاصطناعي', hi: 'AI सहायता (मदद और सुधार)', ru: 'ИИ-ассистент (помощь и улучшение)', it: 'Assistenza IA (Aiuto e Miglioramento)' },
  'ai.autoAnswerPredictive': { en: 'AI Auto-Answer (Predictive)', zh: 'AI自动回答（预测）', es: 'Auto-respuesta IA (Predictiva)', fr: "Réponse auto IA (Prédictive)", de: 'KI Auto-Antwort (Prädiktiv)', ja: 'AI自動回答（予測）', ko: 'AI 자동 응답 (예측)', pt: 'Resposta automática IA (Preditiva)', ar: 'الإجابة التلقائية بالذكاء الاصطناعي', hi: 'AI ऑटो-उत्तर (भविष्यवाणी)', ru: 'ИИ авто-ответ (предиктивный)', it: 'Risposta automatica IA (Predittiva)' },
  'ai.guidanceForQuestion': { en: 'AI Guidance for this question', zh: '此问题的AI引导', es: 'Guía de IA para esta pregunta', fr: 'Guidance IA pour cette question', de: 'KI-Anleitung für diese Frage', ja: 'この質問のAIガイダンス', ko: '이 질문에 대한 AI 안내', pt: 'Orientação IA para esta pergunta', ar: 'إرشادات الذكاء الاصطناعي لهذا السؤال', hi: 'इस प्रश्न के लिए AI मार्गदर्शन', ru: 'Руководство ИИ для этого вопроса', it: 'Guida IA per questa domanda' },
  'ai.guidanceForQuestionPlaceholder': { en: 'e.g. Help the participant think about their daily routine', zh: '例如：帮助参与者思考他们的日常生活', es: 'Ej. Ayuda al participante a pensar en su rutina diaria', fr: 'Ex. Aidez le participant à réfléchir à sa routine', de: 'Z.B. Helfen Sie dem Teilnehmer, über seine Routine nachzudenken', ja: '例：参加者が日常のルーティンについて考えるのを助ける', ko: '예: 참가자가 일상 루틴에 대해 생각하도록 도움', pt: 'Ex. Ajude o participante a pensar em sua rotina', ar: 'مثال: ساعد المشارك على التفكير في روتينه اليومي', hi: 'उदा. प्रतिभागी को अपनी दैनिक दिनचर्या के बारे में सोचने में मदद करें', ru: 'Напр. Помогите участнику подумать о его распорядке дня', it: 'Es. Aiuta il partecipante a pensare alla sua routine' },
  'ai.featuresDesc': { en: 'These AI features help participants answer more easily', zh: '这些AI功能帮助参与者更轻松地回答', es: 'Estas funciones de IA ayudan a los participantes a responder más fácilmente', fr: 'Ces fonctionnalités IA aident les participants à répondre plus facilement', de: 'Diese KI-Funktionen helfen Teilnehmern, einfacher zu antworten', ja: 'これらのAI機能は参加者がより簡単に回答できるようにします', ko: '이러한 AI 기능은 참가자가 더 쉽게 답변하도록 도와줍니다', pt: 'Esses recursos de IA ajudam os participantes a responder mais facilmente', ar: 'هذه الميزات تساعد المشاركين على الإجابة بسهولة', hi: 'ये AI सुविधाएं प्रतिभागियों को आसानी से उत्तर देने में मदद करती हैं', ru: 'Эти функции ИИ помогают участникам отвечать проще', it: 'Queste funzionalità IA aiutano i partecipanti a rispondere più facilmente' },

  // Project
  'project.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'project.questionnaires': { en: 'Questionnaires', zh: '问卷', es: 'Cuestionarios', fr: 'Questionnaires', de: 'Fragebögen', ja: 'アンケート', ko: '설문지', pt: 'Questionários', ar: 'الاستبيانات', hi: 'प्रश्नावली', ru: 'Анкеты', it: 'Questionari' },
  'project.components': { en: 'Components', zh: '组件', es: 'Componentes', fr: 'Composants', de: 'Komponenten', ja: 'コンポーネント', ko: '구성요소', pt: 'Componentes', ar: 'المكونات', hi: 'घटक', ru: 'Компоненты', it: 'Componenti' },
  'project.logic': { en: 'Logic', zh: '逻辑', es: 'Lógica', fr: 'Logique', de: 'Logik', ja: 'ロジック', ko: '로직', pt: 'Lógica', ar: 'المنطق', hi: 'तर्क', ru: 'Логика', it: 'Logica' },
  'project.flow': { en: 'Flow', zh: '流程', es: 'Flujo', fr: 'Flux', de: 'Ablauf', ja: 'フロー', ko: '흐름', pt: 'Fluxo', ar: 'التدفق', hi: 'प्रवाह', ru: 'Поток', it: 'Flusso' },
  'project.notifications': { en: 'Notifications', zh: '通知', es: 'Notificaciones', fr: 'Notifications', de: 'Benachrichtigungen', ja: '通知', ko: '알림', pt: 'Notificações', ar: 'الإشعارات', hi: 'सूचनाएं', ru: 'Уведомления', it: 'Notifiche' },
  'project.translations': { en: 'Translations', zh: '翻译', es: 'Traducciones', fr: 'Traductions', de: 'Übersetzungen', ja: '翻訳', ko: '번역', pt: 'Traduções', ar: 'الترجمات', hi: 'अनुवाद', ru: 'Переводы', it: 'Traduzioni' },
  'project.layout': { en: 'Layout', zh: '布局', es: 'Diseño', fr: 'Mise en page', de: 'Layout', ja: 'レイアウト', ko: '레이아웃', pt: 'Layout', ar: 'التخطيط', hi: 'लेआउट', ru: 'Макет', it: 'Layout' },
  'project.preview': { en: 'Preview', zh: '预览', es: 'Vista previa', fr: 'Aperçu', de: 'Vorschau', ja: 'プレビュー', ko: '미리보기', pt: 'Visualizar', ar: 'معاينة', hi: 'पूर्वावलोकन', ru: 'Предпросмотр', it: 'Anteprima' },
  'project.participants': { en: 'Participants', zh: '参与者', es: 'Participantes', fr: 'Participants', de: 'Teilnehmer', ja: '参加者', ko: '참가자', pt: 'Participantes', ar: 'المشاركون', hi: 'प्रतिभागी', ru: 'Участники', it: 'Partecipanti' },
  'project.publish': { en: 'Publish', zh: '发布', es: 'Publicar', fr: 'Publier', de: 'Veröffentlichen', ja: '公開', ko: '게시', pt: 'Publicar', ar: 'نشر', hi: 'प्रकाशित करें', ru: 'Опубликовать', it: 'Pubblica' },
  'project.unpublish': { en: 'Unpublish', zh: '取消发布', es: 'Despublicar', fr: 'Dépublier', de: 'Zurückziehen', ja: '非公開', ko: '게시 취소', pt: 'Despublicar', ar: 'إلغاء النشر', hi: 'अप्रकाशित करें', ru: 'Снять с публикации', it: 'Annulla pubblicazione' },
  'project.saveAsTemplate': { en: 'Save as Template', zh: '保存为模板', es: 'Guardar como plantilla', fr: 'Enregistrer comme modèle', de: 'Als Vorlage speichern', ja: 'テンプレートとして保存', ko: '템플릿으로 저장', pt: 'Salvar como modelo', ar: 'حفظ كقالب', hi: 'टेम्पलेट के रूप में सहेजें', ru: 'Сохранить как шаблон', it: 'Salva come modello' },
  'project.active': { en: 'Active', zh: '活跃', es: 'Activo', fr: 'Actif', de: 'Aktiv', ja: 'アクティブ', ko: '활성', pt: 'Ativo', ar: 'نشط', hi: 'सक्रिय', ru: 'Активно', it: 'Attivo' },
  'project.enrolled': { en: 'Enrolled', zh: '已注册', es: 'Inscrito', fr: 'Inscrit', de: 'Eingeschrieben', ja: '登録済み', ko: '등록됨', pt: 'Inscrito', ar: 'مسجل', hi: 'नामांकित', ru: 'Зачислено', it: 'Iscritto' },
  'project.aiEditor': { en: 'AI Editor', zh: 'AI 编辑器', es: 'Editor IA', fr: 'Éditeur IA', de: 'KI-Editor', ja: 'AIエディタ', ko: 'AI 편집기', pt: 'Editor IA', ar: 'محرر الذكاء الاصطناعي', hi: 'AI संपादक', ru: 'ИИ-редактор', it: 'Editor IA' },
  'project.myTemplates': { en: 'My Templates', zh: '我的模板', es: 'Mis plantillas', fr: 'Mes modèles', de: 'Meine Vorlagen', ja: 'マイテンプレート', ko: '내 템플릿', pt: 'Meus modelos', ar: 'قوالبي', hi: 'मेरे टेम्पलेट', ru: 'Мои шаблоны', it: 'I miei modelli' },
  'project.findParticipants': { en: 'Find Participants', zh: '查找参与者', es: 'Buscar participantes', fr: 'Trouver des participants', de: 'Teilnehmer finden', ja: '参加者を探す', ko: '참가자 찾기', pt: 'Encontrar participantes', ar: 'البحث عن مشاركين', hi: 'प्रतिभागी खोजें', ru: 'Найти участников', it: 'Trova partecipanti' },
  'project.inviteParticipant': { en: 'Invite Participant', zh: '邀请参与者', es: 'Invitar participante', fr: 'Inviter un participant', de: 'Teilnehmer einladen', ja: '参加者を招待', ko: '참가자 초대', pt: 'Convidar participante', ar: 'دعوة مشارك', hi: 'प्रतिभागी आमंत्रित करें', ru: 'Пригласить участника', it: 'Invita partecipante' },
  'project.totalParticipants': { en: 'Total Participants', zh: '总参与者', es: 'Total de participantes', fr: 'Total de participants', de: 'Gesamtteilnehmer', ja: '総参加者数', ko: '총 참가자', pt: 'Total de participantes', ar: 'إجمالي المشاركين', hi: 'कुल प्रतिभागी', ru: 'Всего участников', it: 'Totale partecipanti' },
  'project.invited': { en: 'Invited', zh: '已邀请', es: 'Invitado', fr: 'Invité', de: 'Eingeladen', ja: '招待済み', ko: '초대됨', pt: 'Convidado', ar: 'مدعو', hi: 'आमंत्रित', ru: 'Приглашено', it: 'Invitato' },
  'project.noParticipants': { en: 'No participants yet', zh: '暂无参与者', es: 'Sin participantes aún', fr: 'Pas encore de participants', de: 'Noch keine Teilnehmer', ja: 'まだ参加者はいません', ko: '아직 참가자가 없습니다', pt: 'Nenhum participante ainda', ar: 'لا يوجد مشاركون بعد', hi: 'अभी तक कोई प्रतिभागी नहीं', ru: 'Пока нет участников', it: 'Nessun partecipante ancora' },
  'project.noParticipantsDesc': { en: 'Invite participants or find them in the library', zh: '邀请参与者或在库中查找', es: 'Invita participantes o encuéntralos en la biblioteca', fr: 'Invitez des participants ou trouvez-les dans la bibliothèque', de: 'Laden Sie Teilnehmer ein oder finden Sie sie in der Bibliothek', ja: '参加者を招待するか、ライブラリで見つけてください', ko: '참가자를 초대하거나 라이브러리에서 찾으세요', pt: 'Convide participantes ou encontre-os na biblioteca', ar: 'ادعُ مشاركين أو ابحث عنهم في المكتبة', hi: 'प्रतिभागियों को आमंत्रित करें या पुस्तकालय में खोजें', ru: 'Пригласите участников или найдите их в библиотеке', it: 'Invita partecipanti o trovali nella libreria' },

  // Builder
  'builder.aiSupport': { en: 'AI Support', zh: 'AI 支持', es: 'Soporte IA', fr: 'Support IA', de: 'KI-Unterstützung', ja: 'AIサポート', ko: 'AI 지원', pt: 'Suporte IA', ar: 'دعم الذكاء الاصطناعي', hi: 'AI सहायता', ru: 'ИИ-поддержка', it: 'Supporto IA' },
  'builder.completion': { en: 'Completion', zh: '完成率', es: 'Completado', fr: 'Achèvement', de: 'Abschluss', ja: '完了率', ko: '완료율', pt: 'Conclusão', ar: 'الإتمام', hi: 'पूर्णता', ru: 'Завершение', it: 'Completamento' },
  'builder.noQuestionnaires': { en: 'No questionnaires yet', zh: '暂无问卷', es: 'Sin cuestionarios aún', fr: 'Pas encore de questionnaires', de: 'Noch keine Fragebögen', ja: 'まだアンケートはありません', ko: '아직 설문지가 없습니다', pt: 'Nenhum questionário ainda', ar: 'لا توجد استبيانات بعد', hi: 'अभी तक कोई प्रश्नावली नहीं', ru: 'Пока нет анкет', it: 'Nessun questionario ancora' },

  // Responses
  'responses.title': { en: 'Responses', zh: '回复', es: 'Respuestas', fr: 'Réponses', de: 'Antworten', ja: '回答', ko: '응답', pt: 'Respostas', ar: 'الردود', hi: 'प्रतिक्रियाएं', ru: 'Ответы', it: 'Risposte' },
  'responses.completed': { en: 'Completed', zh: '已完成', es: 'Completado', fr: 'Terminé', de: 'Abgeschlossen', ja: '完了', ko: '완료', pt: 'Concluído', ar: 'مكتمل', hi: 'पूर्ण', ru: 'Завершено', it: 'Completato' },

  // Settings
  'settings.title': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'settings.subtitle': { en: 'Manage your account settings and preferences', zh: '管理您的帐户设置和偏好设置', es: 'Administra tu configuración', fr: 'Gérez vos paramètres', de: 'Verwalten Sie Ihre Einstellungen', ja: 'アカウント設定を管理', ko: '계정 설정 관리', pt: 'Gerencie suas configurações', ar: 'إدارة إعداداتك', hi: 'अपनी सेटिंग्स प्रबंधित करें', ru: 'Управляйте настройками', it: 'Gestisci le impostazioni' },
  'settings.profile': { en: 'Profile', zh: '个人资料', es: 'Perfil', fr: 'Profil', de: 'Profil', ja: 'プロフィール', ko: '프로필', pt: 'Perfil', ar: 'الملف الشخصي', hi: 'प्रोफ़ाइल', ru: 'Профиль', it: 'Profilo' },
  'settings.fullName': { en: 'Full Name', zh: '姓名', es: 'Nombre completo', fr: 'Nom complet', de: 'Vollständiger Name', ja: '氏名', ko: '이름', pt: 'Nome completo', ar: 'الاسم الكامل', hi: 'पूरा नाम', ru: 'Полное имя', it: 'Nome completo' },
  'settings.email': { en: 'Email', zh: '电子邮件', es: 'Correo electrónico', fr: 'E-mail', de: 'E-Mail', ja: 'メール', ko: '이메일', pt: 'E-mail', ar: 'البريد الإلكتروني', hi: 'ईमेल', ru: 'Email', it: 'Email' },
  'settings.phone': { en: 'Phone', zh: '电话', es: 'Teléfono', fr: 'Téléphone', de: 'Telefon', ja: '電話', ko: '전화', pt: 'Telefone', ar: 'الهاتف', hi: 'फ़ोन', ru: 'Телефон', it: 'Telefono' },
  'settings.introduction': { en: 'Introduction', zh: '简介', es: 'Introducción', fr: 'Introduction', de: 'Einleitung', ja: '自己紹介', ko: '소개', pt: 'Introdução', ar: 'مقدمة', hi: 'परिचय', ru: 'Введение', it: 'Introduzione' },
  'settings.introPlaceholder': { en: 'Tell us a bit about yourself', zh: '简单介绍一下自己吧', es: 'Cuéntanos un poco sobre ti', fr: 'Parlez-nous un peu de vous', de: 'Erzählen Sie uns etwas über sich', ja: '自己紹介をお願いします', ko: '자신에 대해 간단히 소개해 주세요', pt: 'Conte-nos um pouco sobre você', ar: 'أخبرنا قليلاً عن نفسك', hi: 'अपने बारे में थोड़ा बताएं', ru: 'Расскажите немного о себе', it: 'Raccontaci qualcosa di te' },
  'settings.edit': { en: 'Edit', zh: '编辑', es: 'Editar', fr: 'Modifier', de: 'Bearbeiten', ja: '編集', ko: '편집', pt: 'Editar', ar: 'تعديل', hi: 'संपादित करें', ru: 'Редактировать', it: 'Modifica' },
  'settings.saving': { en: 'Saving...', zh: '保存中...', es: 'Guardando...', fr: 'Enregistrement...', de: 'Speichern...', ja: '保存中...', ko: '저장 중...', pt: 'Salvando...', ar: 'جاري الحفظ...', hi: 'सहेजा जा रहा है...', ru: 'Сохранение...', it: 'Salvataggio...' },
  'settings.saved': { en: 'Settings saved!', zh: '设置已保存！', es: '¡Configuración guardada!', fr: 'Paramètres enregistrés !', de: 'Einstellungen gespeichert!', ja: '設定を保存しました！', ko: '설정이 저장되었습니다!', pt: 'Configurações salvas!', ar: 'تم حفظ الإعدادات!', hi: 'सेटिंग्स सहेजी गईं!', ru: 'Настройки сохранены!', it: 'Impostazioni salvate!' },
  'settings.profileSaved': { en: 'Profile saved!', zh: '个人资料已保存！', es: '¡Perfil guardado!', fr: 'Profil enregistré !', de: 'Profil gespeichert!', ja: 'プロフィールを保存しました！', ko: '프로필이 저장되었습니다!', pt: 'Perfil salvo!', ar: 'تم حفظ الملف الشخصي!', hi: 'प्रोफ़ाइल सहेजी गई!', ru: 'Профиль сохранен!', it: 'Profilo salvato!' },
  'settings.notifications': { en: 'Notifications', zh: '通知', es: 'Notificaciones', fr: 'Notifications', de: 'Benachrichtigungen', ja: '通知', ko: '알림', pt: 'Notificações', ar: 'الإشعارات', hi: 'सूचनाएं', ru: 'Уведомления', it: 'Notifiche' },
  'settings.webNotifications': { en: 'Web Notifications', zh: '网页通知', es: 'Notificaciones web', fr: 'Notifications web', de: 'Web-Benachrichtigungen', ja: 'ウェブ通知', ko: '웹 알림', pt: 'Notificações da web', ar: 'إشعارات الويب', hi: 'वेब सूचनाएं', ru: 'Веб-уведомления', it: 'Notifiche web' },
  'settings.webNotificationsDesc': { en: 'Receive notifications in your browser', zh: '在浏览器中接收通知', es: 'Recibe notificaciones en tu navegador', fr: 'Recevez des notifications dans votre navigateur', de: 'Benachrichtigungen im Browser erhalten', ja: 'ブラウザで通知を受信', ko: '브라우저에서 알림 받기', pt: 'Receba notificações no navegador', ar: 'تلقي الإشعارات في متصفحك', hi: 'अपने ब्राउज़र में सूचनाएं प्राप्त करें', ru: 'Получайте уведомления в браузере', it: 'Ricevi notifiche nel browser' },
  'settings.pushNotifications': { en: 'Push Notifications', zh: '推送通知', es: 'Notificaciones push', fr: 'Notifications push', de: 'Push-Benachrichtigungen', ja: 'プッシュ通知', ko: '푸시 알림', pt: 'Notificações push', ar: 'إشعارات الدفع', hi: 'पुश सूचनाएं', ru: 'Push-уведомления', it: 'Notifiche push' },
  'settings.pushNotificationsDesc': { en: 'Receive notifications on your mobile device', zh: '在移动设备上接收通知', es: 'Recibe notificaciones en tu dispositivo móvil', fr: 'Recevez des notifications sur votre mobile', de: 'Benachrichtigungen auf Mobilgerät erhalten', ja: 'モバイルで通知を受信', ko: '모바일에서 알림 받기', pt: 'Receba notificações no celular', ar: 'تلقي الإشعارات على جهازك المحمول', hi: 'मोबाइल पर सूचनाएं प्राप्त करें', ru: 'Получайте уведомления на мобильном', it: 'Ricevi notifiche sul dispositivo mobile' },
  'settings.emailNotifications': { en: 'Email Notifications', zh: '电子邮件通知', es: 'Notificaciones por email', fr: 'Notifications par e-mail', de: 'E-Mail-Benachrichtigungen', ja: 'メール通知', ko: '이메일 알림', pt: 'Notificações por e-mail', ar: 'إشعارات البريد الإلكتروني', hi: 'ईमेल सूचनाएं', ru: 'Уведомления по email', it: 'Notifiche email' },
  'settings.emailNotificationsDesc': { en: 'Receive notifications via email', zh: '通过电子邮件接收通知', es: 'Recibe notificaciones por email', fr: 'Recevez des notifications par e-mail', de: 'Benachrichtigungen per E-Mail erhalten', ja: 'メールで通知を受信', ko: '이메일로 알림 받기', pt: 'Receba notificações por e-mail', ar: 'تلقي الإشعارات عبر البريد الإلكتروني', hi: 'ईमेल से सूचनाएं प्राप्त करें', ru: 'Получайте уведомления по email', it: 'Ricevi notifiche via email' },
  'settings.security': { en: 'Security', zh: '安全', es: 'Seguridad', fr: 'Sécurité', de: 'Sicherheit', ja: 'セキュリティ', ko: '보안', pt: 'Segurança', ar: 'الأمان', hi: 'सुरक्षा', ru: 'Безопасность', it: 'Sicurezza' },
  'settings.changePassword': { en: 'Change Password', zh: '更改密码', es: 'Cambiar contraseña', fr: 'Changer le mot de passe', de: 'Passwort ändern', ja: 'パスワード変更', ko: '비밀번호 변경', pt: 'Alterar senha', ar: 'تغيير كلمة المرور', hi: 'पासवर्ड बदलें', ru: 'Изменить пароль', it: 'Cambia password' },
  'settings.changePasswordDesc': { en: 'Update your password to keep your account secure', zh: '更新密码以保证帐户安全', es: 'Actualiza tu contraseña para mantener tu cuenta segura', fr: 'Mettez à jour votre mot de passe', de: 'Passwort aktualisieren', ja: 'パスワードを更新してアカウントを保護', ko: '비밀번호를 업데이트하여 계정을 안전하게', pt: 'Atualize sua senha', ar: 'تحديث كلمة المرور للحفاظ على أمان حسابك', hi: 'अपना पासवर्ड अपडेट करें', ru: 'Обновите пароль для безопасности', it: 'Aggiorna la password' },
  'settings.signOut': { en: 'Sign Out', zh: '退出登录', es: 'Cerrar sesión', fr: 'Se déconnecter', de: 'Abmelden', ja: 'ログアウト', ko: '로그아웃', pt: 'Sair', ar: 'تسجيل الخروج', hi: 'साइन आउट', ru: 'Выйти', it: 'Esci' },
  'settings.pleaseSignIn': { en: 'Please Sign In', zh: '请登录', es: 'Por favor, inicia sesión', fr: 'Veuillez vous connecter', de: 'Bitte anmelden', ja: 'サインインしてください', ko: '로그인하세요', pt: 'Por favor, entre', ar: 'يرجى تسجيل الدخول', hi: 'कृपया साइन इन करें', ru: 'Пожалуйста, войдите', it: 'Per favore, accedi' },
  'settings.signInManage': { en: 'Sign in to manage your settings', zh: '登录以管理您的设置', es: 'Inicia sesión para gestionar tu configuración', fr: 'Connectez-vous pour gérer vos paramètres', de: 'Anmelden um Einstellungen zu verwalten', ja: 'サインインして設定を管理', ko: '로그인하여 설정 관리', pt: 'Entre para gerenciar configurações', ar: 'سجل الدخول لإدارة إعداداتك', hi: 'सेटिंग्स प्रबंधित करने के लिए साइन इन करें', ru: 'Войдите для управления настройками', it: 'Accedi per gestire le impostazioni' },
  'settings.countryRegion': { en: 'Country / Region', zh: '国家/地区', es: 'País / Región', fr: 'Pays / Région', de: 'Land / Region', ja: '国/地域', ko: '국가/지역', pt: 'País / Região', ar: 'الدولة / المنطقة', hi: 'देश/प्रदेश', ru: 'Страна / Регион', it: 'Paese / Regione' },
  'settings.age': { en: 'Age', zh: '年龄', es: 'Edad', fr: 'Âge', de: 'Alter', ja: '年齢', ko: '나이', pt: 'Idade', ar: 'العمر', hi: 'आयु', ru: 'Возраст', it: 'Età' },
  'settings.gender': { en: 'Gender', zh: '性别', es: 'Género', fr: 'Genre', de: 'Geschlecht', ja: '性別', ko: '성별', pt: 'Gênero', ar: 'الجنس', hi: 'लिंग', ru: 'Пол', it: 'Genere' },
  'settings.occupation': { en: 'Occupation', zh: '职业', es: 'Ocupación', fr: 'Profession', de: 'Beruf', ja: '職業', ko: '직업', pt: 'Ocupação', ar: 'الوظيفة', hi: 'व्यवसाय', ru: 'Профессия', it: 'Occupazione' },
  'settings.doNotDisturb': { en: 'Do Not Disturb', zh: '请勿打扰', es: 'No molestar', fr: 'Ne pas déranger', de: 'Nicht stören', ja: 'おやすみモード', ko: '방해 금지', pt: 'Não perturbe', ar: 'عدم الإزعاج', hi: 'परेशान न करें', ru: 'Не беспокоить', it: 'Non disturbare' },
  'settings.dndDesc': { en: 'Silence notifications during specific periods', zh: '在特定时间段内静音通知', es: 'Silenciar notificaciones durante períodos específicos', fr: 'Désactiver les notifications pendant des périodes spécifiques', de: 'Benachrichtigungen stummschalten', ja: '特定の時間帯に通知をミュート', ko: '특정 시간 동안 알림 음소거', pt: 'Silenciar notificações em períodos específicos', ar: 'كتم الإشعارات خلال فترات محددة', hi: 'विशिष्ट अवधियों में सूचनाओं को मौन करें', ru: 'Отключить уведомления в определённые периоды', it: 'Disattiva le notifiche durante periodi specifici' },
  'settings.all': { en: 'All', zh: '全部', es: 'Todos', fr: 'Tous', de: 'Alle', ja: 'すべて', ko: '모두', pt: 'Todos', ar: 'الكل', hi: 'सभी', ru: 'Все', it: 'Tutti' },
  'settings.to': { en: 'to', zh: '至', es: 'a', fr: 'à', de: 'bis', ja: '〜', ko: '에', pt: 'para', ar: 'إلى', hi: 'से', ru: 'до', it: 'a' },
  'settings.addQuietPeriod': { en: 'Add Quiet Period', zh: '添加静音时段', es: 'Agregar período silencioso', fr: 'Ajouter une période de silence', de: 'Ruhezeit hinzufügen', ja: '安静期間を追加', ko: '조용한 시간 추가', pt: 'Adicionar período silencioso', ar: 'إضافة فترة هدوء', hi: 'शांत अवधि जोड़ें', ru: 'Добавить тихий период', it: 'Aggiungi periodo di silenzio' },
  'settings.joinLibrary': { en: 'Join the Participant Library', zh: '加入参与者库', es: 'Unirse a la biblioteca de participantes', fr: 'Rejoindre la bibliothèque des participants', de: 'Der Teilnehmerbibliothek beitreten', ja: '参加者ライブラリに参加', ko: '참가자 라이브러리 참여', pt: 'Participar da biblioteca', ar: 'انضم إلى مكتبة المشاركين', hi: 'प्रतिभागी पुस्तकालय में शामिल हों', ru: 'Присоединиться к библиотеке участников', it: 'Iscriviti alla libreria' },
  'settings.joinLibraryDesc': { en: 'Make your profile visible to researchers for potential study invitations', zh: '让研究人员可以看到您的个人资料，以便邀请您参与研究', es: 'Haz que tu perfil sea visible para los investigadores', fr: 'Rendez votre profil visible aux chercheurs', de: 'Machen Sie Ihr Profil sichtbar für Forscher', ja: '研究者にプロフィールを公開して研究への招待を受ける', ko: '연구자에게 프로필을 공개하여 연구 초대를 받으세요', pt: 'Torne seu perfil visível para pesquisadores', ar: 'اجعل ملفك الشخصي مرئيًا للباحثين', hi: 'शोधकर्ताओं के लिए अपनी प्रोफ़ाइल दृश्यमान बनाएं', ru: 'Сделайте свой профиль видимым для исследователей', it: 'Rendi il tuo profilo visibile ai ricercatori' },
  'settings.editPublicProfile': { en: 'Edit Public Profile', zh: '编辑公开资料', es: 'Editar perfil público', fr: 'Modifier le profil public', de: 'Öffentliches Profil bearbeiten', ja: '公開プロフィールを編集', ko: '공개 프로필 편집', pt: 'Editar perfil público', ar: 'تعديل الملف الشخصي العام', hi: 'सार्वजनिक प्रोफ़ाइल संपादित करें', ru: 'Редактировать публичный профиль', it: 'Modifica il profilo pubblico' },
  'settings.hideDetails': { en: 'Hide Details', zh: '隐藏详细信息', es: 'Ocultar detalles', fr: 'Masquer les détails', de: 'Details ausblenden', ja: '詳細を隠す', ko: '세부 정보 숨기기', pt: 'Ocultar detalhes', ar: 'إخفاء التفاصيل', hi: 'विवरण छिपाएं', ru: 'Скрыть детали', it: 'Nascondi dettagli' },

  // Participant Library
  'participantLibrary.title': { en: 'Participant Library', zh: '参与者库', es: 'Biblioteca de participantes', fr: 'Bibliothèque de participants', de: 'Teilnehmerbibliothek', ja: '参加者ライブラリ', ko: '참가자 라이브러리', pt: 'Biblioteca de participantes', ar: 'مكتبة المشاركين', hi: 'प्रतिभागी पुस्तकालय', ru: 'Библиотека участников', it: 'Libreria dei partecipanti' },

  // Templates
  'templates.title': { en: 'Template Library', zh: '模板库', es: 'Biblioteca de plantillas', fr: 'Bibliothèque de modèles', de: 'Vorlagenbibliothek', ja: 'テンプレートライブラリ', ko: '템플릿 라이브러리', pt: 'Biblioteca de modelos', ar: 'مكتبة القوالب', hi: 'टेम्पलेट लाइब्रेरी', ru: 'Библиотека шаблонов', it: 'Libreria dei modelli' },
  'templates.subtitle': { en: 'Browse and use pre-built research templates', zh: '浏览和使用预建研究模板', es: 'Explora y usa plantillas de investigación', fr: 'Parcourez et utilisez des modèles de recherche', de: 'Durchsuchen und verwenden Sie Vorlagen', ja: 'テンプレートを閲覧して使用', ko: '사전 제작된 연구 템플릿 찾아보기', pt: 'Explore e use modelos de pesquisa', ar: 'تصفح واستخدم قوالب البحث', hi: 'पूर्व-निर्मित शोध टेम्पलेट ब्राउज़ करें', ru: 'Просматривайте и используйте шаблоны', it: 'Sfoglia e usa modelli di ricerca' },
  'templates.search': { en: 'Search templates...', zh: '搜索模板...', es: 'Buscar plantillas...', fr: 'Rechercher des modèles...', de: 'Vorlagen suchen...', ja: 'テンプレートを検索...', ko: '템플릿 검색...', pt: 'Pesquisar modelos...', ar: 'البحث عن قوالب...', hi: 'टेम्पलेट खोजें...', ru: 'Поиск шаблонов...', it: 'Cerca modelli...' },
  'templates.templates': { en: 'templates', zh: '个模板', es: 'plantillas', fr: 'modèles', de: 'Vorlagen', ja: 'テンプレート', ko: '템플릿', pt: 'modelos', ar: 'قوالب', hi: 'टेम्पलेट', ru: 'шаблонов', it: 'modelli' },
  'templates.research': { en: 'research', zh: '研究', es: 'investigación', fr: 'recherche', de: 'Forschung', ja: '研究', ko: '연구', pt: 'pesquisa', ar: 'بحث', hi: 'शोध', ru: 'исследований', it: 'ricerca' },
  'templates.questionnaires': { en: 'Questionnaires', zh: '问卷', es: 'Cuestionarios', fr: 'Questionnaires', de: 'Fragebögen', ja: 'アンケート', ko: '설문지', pt: 'Questionários', ar: 'الاستبيانات', hi: 'प्रश्नावली', ru: 'Анкеты', it: 'Questionari' },
  'templates.researchProjects': { en: 'Research Projects', zh: '研究项目', es: 'Proyectos de investigación', fr: 'Projets de recherche', de: 'Forschungsprojekte', ja: '研究プロジェクト', ko: '연구 프로젝트', pt: 'Projetos de pesquisa', ar: 'مشاريع البحث', hi: 'शोध परियोजनाएँ', ru: 'Исследовательские проекты', it: 'Progetti di ricerca' },
  'templates.researchProject': { en: 'Research Project', zh: '研究项目', es: 'Proyecto de investigación', fr: 'Projet de recherche', de: 'Forschungsprojekt', ja: '研究プロジェクト', ko: '연구 프로젝트', pt: 'Projeto de pesquisa', ar: 'مشروع بحثي', hi: 'शोध परियोजना', ru: 'Исследовательский проект', it: 'Progetto di ricerca' },
  'templates.questionnaire': { en: 'Questionnaire', zh: '问卷', es: 'Cuestionario', fr: 'Questionnaire', de: 'Fragebogen', ja: 'アンケート', ko: '설문지', pt: 'Questionário', ar: 'استبيان', hi: 'प्रश्नावली', ru: 'Анкета', it: 'Questionario' },
  'templates.project': { en: 'Project', zh: '项目', es: 'Proyecto', fr: 'Projet', de: 'Projekt', ja: 'プロジェクト', ko: '프로젝트', pt: 'Projeto', ar: 'مشروع', hi: 'प्रोजेक्ट', ru: 'Проект', it: 'Progetto' },
  'templates.noResults': { en: 'No templates found', zh: '未找到模板', es: 'No se encontraron plantillas', fr: 'Aucun modèle trouvé', de: 'Keine Vorlagen gefunden', ja: 'テンプレートが見つかりません', ko: '템플릿을 찾을 수 없습니다', pt: 'Nenhum modelo encontrado', ar: 'لم يتم العثور على قوالب', hi: 'कोई टेम्पलेट नहीं मिला', ru: 'Шаблоны не найдены', it: 'Nessun modello trovato' },
  'templates.adjustFilter': { en: 'Try adjusting your search or filter', zh: '尝试调整搜索或筛选条件', es: 'Intenta ajustar tu búsqueda o filtro', fr: 'Essayez de modifier votre recherche', de: 'Versuchen Sie, Ihre Suche anzupassen', ja: '検索やフィルターを調整してみてください', ko: '검색이나 필터를 조정해 보세요', pt: 'Tente ajustar sua pesquisa ou filtro', ar: 'حاول تعديل بحثك أو الفلتر', hi: 'अपनी खोज या फ़िल्टर समायोजित करें', ru: 'Попробуйте изменить поиск или фильтр', it: 'Prova a modificare la ricerca o il filtro' },
  'templates.min': { en: 'min', zh: '分钟', es: 'min', fr: 'min', de: 'Min', ja: '分', ko: '분', pt: 'min', ar: 'دقيقة', hi: 'मिनट', ru: 'мин', it: 'min' },
  'templates.preview': { en: 'Preview', zh: '预览', es: 'Vista previa', fr: 'Aperçu', de: 'Vorschau', ja: 'プレビュー', ko: '미리보기', pt: 'Visualizar', ar: 'معاينة', hi: 'पूर्वावलोकन', ru: 'Предпросмотр', it: 'Anteprima' },
  'templates.use': { en: 'Use', zh: '使用', es: 'Usar', fr: 'Utiliser', de: 'Verwenden', ja: '使用', ko: '사용', pt: 'Usar', ar: 'استخدام', hi: 'उपयोग', ru: 'Использовать', it: 'Usa' },
  'templates.import': { en: 'Import', zh: '导入', es: 'Importar', fr: 'Importer', de: 'Importieren', ja: 'インポート', ko: '가져오기', pt: 'Importar', ar: 'استيراد', hi: 'आयात', ru: 'Импорт', it: 'Importa' },
  'templates.creating': { en: 'Creating...', zh: '创建中...', es: 'Creando...', fr: 'Création...', de: 'Erstellen...', ja: '作成中...', ko: '생성 중...', pt: 'Criando...', ar: 'جاري الإنشاء...', hi: 'बना रहा है...', ru: 'Создание...', it: 'Creazione...' },
  'templates.createProject': { en: 'Create Project from Template', zh: '从模板创建项目', es: 'Crear proyecto desde plantilla', fr: 'Créer un projet depuis le modèle', de: 'Projekt aus Vorlage erstellen', ja: 'テンプレートからプロジェクト作成', ko: '템플릿에서 프로젝트 만들기', pt: 'Criar projeto do modelo', ar: 'إنشاء مشروع من القالب', hi: 'टेम्पलेट से प्रोजेक्ट बनाएं', ru: 'Создать проект из шаблона', it: 'Crea progetto dal modello' },
  'templates.useQuestionnaire': { en: 'Use Questionnaire', zh: '使用问卷', es: 'Usar cuestionario', fr: 'Utiliser le questionnaire', de: 'Fragebogen verwenden', ja: 'アンケートを使用', ko: '설문지 사용', pt: 'Usar questionário', ar: 'استخدام الاستبيان', hi: 'प्रश्नावली का उपयोग करें', ru: 'Использовать анкету', it: 'Usa questionario' },
  'templates.allCategories': { en: 'All Categories', zh: '所有分类', es: 'Todas las categorías', fr: 'Toutes les catégories', de: 'Alle Kategorien', ja: 'すべてのカテゴリ', ko: '모든 카테고리', pt: 'Todas as categorias', ar: 'جميع الفئات', hi: 'सभी श्रेणियाँ', ru: 'Все категории', it: 'Tutte le categorie' },
  'templates.academic': { en: 'Academic', zh: '学术', es: 'Académico', fr: 'Académique', de: 'Akademisch', ja: '学術', ko: '학술', pt: 'Acadêmico', ar: 'أكاديمي', hi: 'शैक्षणिक', ru: 'Академический', it: 'Accademico' },
  'templates.health': { en: 'Health', zh: '健康', es: 'Salud', fr: 'Santé', de: 'Gesundheit', ja: '健康', ko: '건강', pt: 'Saúde', ar: 'الصحة', hi: 'स्वास्थ्य', ru: 'Здоровье', it: 'Salute' },
  'templates.business': { en: 'Business', zh: '商业', es: 'Negocios', fr: 'Entreprise', de: 'Geschäft', ja: 'ビジネス', ko: '비즈니스', pt: 'Negócios', ar: 'الأعمال', hi: 'व्यापार', ru: 'Бизнес', it: 'Business' },
  'templates.social': { en: 'Social Science', zh: '社会科学', es: 'Ciencias sociales', fr: 'Sciences sociales', de: 'Sozialwissenschaften', ja: '社会科学', ko: '사회과학', pt: 'Ciências sociais', ar: 'العلوم الاجتماعية', hi: 'सामाजिक विज्ञान', ru: 'Социальные науки', it: 'Scienze sociali' },
  'templates.education': { en: 'Education', zh: '教育', es: 'Educación', fr: 'Éducation', de: 'Bildung', ja: '教育', ko: '교육', pt: 'Educação', ar: 'التعليم', hi: 'शिक्षा', ru: 'Образование', it: 'Istruzione' },
  'templates.psychology': { en: 'Psychology', zh: '心理学', es: 'Psicología', fr: 'Psychologie', de: 'Psychologie', ja: '心理学', ko: '심리학', pt: 'Psicologia', ar: 'علم النفس', hi: 'मनोविज्ञान', ru: 'Психология', it: 'Psicologia' },
  'templates.ux': { en: 'UX Research', zh: '用户体验研究', es: 'Investigación UX', fr: 'Recherche UX', de: 'UX-Forschung', ja: 'UXリサーチ', ko: 'UX 연구', pt: 'Pesquisa UX', ar: 'بحث تجربة المستخدم', hi: 'UX अनुसंधान', ru: 'UX-исследования', it: 'Ricerca UX' },
  'templates.market': { en: 'Market Research', zh: '市场研究', es: 'Investigación de mercado', fr: 'Étude de marché', de: 'Marktforschung', ja: '市場調査', ko: '시장 조사', pt: 'Pesquisa de mercado', ar: 'أبحاث السوق', hi: 'बाजार अनुसंधान', ru: 'Маркетинговые исследования', it: 'Ricerca di mercato' },

  // Join
  'join.title': { en: 'Join a Study', zh: '加入研究', es: 'Unirse a un estudio', fr: "Rejoindre une étude", de: 'An einer Studie teilnehmen', ja: '研究に参加', ko: '연구에 참여', pt: 'Participar de um estudo', ar: 'انضم إلى دراسة', hi: 'अध्ययन में शामिल हों', ru: 'Присоединиться к исследованию', it: 'Partecipa a uno studio' },
  'join.invitation': { en: 'Study Invitation', zh: '研究邀请', es: 'Invitación al estudio', fr: "Invitation à l'étude", de: 'Studieneinladung', ja: '研究への招待', ko: '연구 초대', pt: 'Convite para estudo', ar: 'دعوة للدراسة', hi: 'अध्ययन आमंत्रण', ru: 'Приглашение в исследование', it: 'Invito allo studio' },
  'join.invitedToParticipate': { en: 'You have been invited to participate in this study', zh: '您已被邀请参与此研究', es: 'Has sido invitado a participar', fr: 'Vous avez été invité à participer', de: 'Sie wurden eingeladen teilzunehmen', ja: 'この研究への参加に招待されました', ko: '이 연구에 참여하도록 초대되었습니다', pt: 'Você foi convidado a participar', ar: 'تمت دعوتك للمشاركة في هذه الدراسة', hi: 'आपको इस अध्ययन में भाग लेने के लिए आमंत्रित किया गया है', ru: 'Вас пригласили участвовать в этом исследовании', it: 'Sei stato invitato a partecipare' },
  'join.noDescription': { en: 'No description available', zh: '暂无描述', es: 'Sin descripción disponible', fr: 'Aucune description disponible', de: 'Keine Beschreibung verfügbar', ja: '説明なし', ko: '설명 없음', pt: 'Sem descrição disponível', ar: 'لا يوجد وصف', hi: 'कोई विवरण उपलब्ध नहीं', ru: 'Описание отсутствует', it: 'Nessuna descrizione disponibile' },
  'join.accept': { en: 'Accept & Join', zh: '接受并加入', es: 'Aceptar y unirse', fr: 'Accepter et rejoindre', de: 'Akzeptieren und beitreten', ja: '承諾して参加', ko: '수락 및 참여', pt: 'Aceitar e participar', ar: 'قبول والانضمام', hi: 'स्वीकार करें और शामिल हों', ru: 'Принять и присоединиться', it: 'Accetta e partecipa' },
  'join.decline': { en: 'Decline', zh: '拒绝', es: 'Rechazar', fr: 'Refuser', de: 'Ablehnen', ja: '辞退', ko: '거절', pt: 'Recusar', ar: 'رفض', hi: 'अस्वीकार करें', ru: 'Отклонить', it: 'Rifiuta' },
  'join.joining': { en: 'Joining...', zh: '加入中...', es: 'Uniéndose...', fr: 'Rejoindre...', de: 'Beitreten...', ja: '参加中...', ko: '참여 중...', pt: 'Participando...', ar: 'جاري الانضمام...', hi: 'शामिल हो रहा है...', ru: 'Присоединение...', it: 'Partecipazione...' },
  'join.enterCode': { en: 'Enter study code', zh: '输入研究代码', es: 'Ingresa el código del estudio', fr: "Entrez le code de l'étude", de: 'Studiencode eingeben', ja: '研究コードを入力', ko: '연구 코드 입력', pt: 'Digite o código do estudo', ar: 'أدخل رمز الدراسة', hi: 'अध्ययन कोड दर्ज करें', ru: 'Введите код исследования', it: 'Inserisci il codice dello studio' },
  'join.lookupStudy': { en: 'Look up study', zh: '查找研究', es: 'Buscar estudio', fr: "Rechercher l'étude", de: 'Studie suchen', ja: '研究を検索', ko: '연구 검색', pt: 'Buscar estudo', ar: 'البحث عن الدراسة', hi: 'अध्ययन खोजें', ru: 'Найти исследование', it: 'Cerca studio' },
  'join.orEnterCode': { en: 'Or enter a study code', zh: '或输入研究代码', es: 'O ingresa un código de estudio', fr: "Ou entrez un code d'étude", de: 'Oder geben Sie einen Studiencode ein', ja: 'または研究コードを入力', ko: '또는 연구 코드 입력', pt: 'Ou digite um código de estudo', ar: 'أو أدخل رمز الدراسة', hi: 'या अध्ययन कोड दर्ज करें', ru: 'Или введите код исследования', it: 'O inserisci un codice studio' },
  'join.browsePublicStudies': { en: 'Browse Public Studies', zh: '浏览公开研究', es: 'Explorar estudios públicos', fr: 'Parcourir les études publiques', de: 'Öffentliche Studien durchsuchen', ja: '公開研究を閲覧', ko: '공개 연구 찾아보기', pt: 'Explorar estudos públicos', ar: 'تصفح الدراسات العامة', hi: 'सार्वजनिक अध्ययन ब्राउज़ करें', ru: 'Просмотреть публичные исследования', it: 'Sfoglia studi pubblici' },

  // Home
  'home.welcome': { en: 'Welcome', zh: '欢迎', es: 'Bienvenido', fr: 'Bienvenue', de: 'Willkommen', ja: 'ようこそ', ko: '환영합니다', pt: 'Bem-vindo', ar: 'مرحبًا', hi: 'स्वागत', ru: 'Добро пожаловать', it: 'Benvenuto' },
  'home.yourStudies': { en: 'Your Studies', zh: '您的研究', es: 'Tus estudios', fr: 'Vos études', de: 'Ihre Studien', ja: 'あなたの研究', ko: '내 연구', pt: 'Seus estudos', ar: 'دراساتك', hi: 'आपके अध्ययन', ru: 'Ваши исследования', it: 'I tuoi studi' },
  'home.quickActions': { en: 'Quick Actions', zh: '快速操作', es: 'Acciones rápidas', fr: 'Actions rapides', de: 'Schnellaktionen', ja: 'クイックアクション', ko: '빠른 작업', pt: 'Ações rápidas', ar: 'إجراءات سريعة', hi: 'त्वरित कार्रवाइयाँ', ru: 'Быстрые действия', it: 'Azioni rapide' },
  'home.recentActivity': { en: 'Recent Activity', zh: '最近活动', es: 'Actividad reciente', fr: 'Activité récente', de: 'Letzte Aktivität', ja: '最近のアクティビティ', ko: '최근 활동', pt: 'Atividade recente', ar: 'النشاط الأخير', hi: 'हाल की गतिविधि', ru: 'Недавняя активность', it: 'Attività recente' },
  'home.createNewStudy': { en: 'Create New Study', zh: '创建新研究', es: 'Crear nuevo estudio', fr: 'Créer une nouvelle étude', de: 'Neue Studie erstellen', ja: '新しい研究を作成', ko: '새 연구 만들기', pt: 'Criar novo estudo', ar: 'إنشاء دراسة جديدة', hi: 'नया अध्ययन बनाएं', ru: 'Создать новое исследование', it: 'Crea nuovo studio' },
  'home.joinStudy': { en: 'Join a Study', zh: '加入研究', es: 'Unirse a un estudio', fr: "Rejoindre une étude", de: 'An einer Studie teilnehmen', ja: '研究に参加', ko: '연구에 참여', pt: 'Participar de um estudo', ar: 'انضم إلى دراسة', hi: 'अध्ययन में शामिल हों', ru: 'Присоединиться к исследованию', it: 'Partecipa a uno studio' },
  'home.browseTemplates': { en: 'Browse Templates', zh: '浏览模板', es: 'Explorar plantillas', fr: 'Parcourir les modèles', de: 'Vorlagen durchsuchen', ja: 'テンプレートを閲覧', ko: '템플릿 찾아보기', pt: 'Explorar modelos', ar: 'تصفح القوالب', hi: 'टेम्पलेट ब्राउज़ करें', ru: 'Просмотреть шаблоны', it: 'Sfoglia modelli' },
  'home.discoverStudies': { en: 'Discover Studies', zh: '发现研究', es: 'Descubrir estudios', fr: 'Découvrir des études', de: 'Studien entdecken', ja: '研究を発見', ko: '연구 발견', pt: 'Descobrir estudos', ar: 'اكتشف الدراسات', hi: 'अध्ययन खोजें', ru: 'Обзор исследований', it: 'Scopri studi' },

  // Create Project Dialog
  'createProject.title': { en: 'Create New Study', zh: '创建新研究', es: 'Crear nuevo estudio', fr: 'Créer une nouvelle étude', de: 'Neue Studie erstellen', ja: '新しい研究を作成', ko: '새 연구 만들기', pt: 'Criar novo estudo', ar: 'إنشاء دراسة جديدة', hi: 'नया अध्ययन बनाएं', ru: 'Создать новое исследование', it: 'Crea nuovo studio' },
  'createProject.studyName': { en: 'Study Name', zh: '研究名称', es: 'Nombre del estudio', fr: "Nom de l'étude", de: 'Studienname', ja: '研究名', ko: '연구 이름', pt: 'Nome do estudo', ar: 'اسم الدراسة', hi: 'अध्ययन का नाम', ru: 'Название исследования', it: 'Nome dello studio' },
  'createProject.studyNamePlaceholder': { en: 'e.g. Student Well-being Survey', zh: '例如：学生幸福感调查', es: 'Ej. Encuesta de bienestar estudiantil', fr: 'Ex. Enquête sur le bien-être des étudiants', de: 'Z.B. Umfrage zum Wohlbefinden der Studenten', ja: '例：学生の幸福度調査', ko: '예: 학생 웰빙 설문조사', pt: 'Ex. Pesquisa de bem-estar estudantil', ar: 'مثال: استطلاع رفاهية الطلاب', hi: 'उदा. छात्र कल्याण सर्वेक्षण', ru: 'Напр. Опрос о благополучии студентов', it: 'Es. Sondaggio sul benessere degli studenti' },
  'createProject.description': { en: 'Description', zh: '描述', es: 'Descripción', fr: 'Description', de: 'Beschreibung', ja: '説明', ko: '설명', pt: 'Descrição', ar: 'الوصف', hi: 'विवरण', ru: 'Описание', it: 'Descrizione' },
  'createProject.descriptionPlaceholder': { en: 'Briefly describe your study...', zh: '简要描述您的研究...', es: 'Describe brevemente tu estudio...', fr: 'Décrivez brièvement votre étude...', de: 'Beschreiben Sie Ihre Studie kurz...', ja: '研究の概要を簡単に説明してください...', ko: '연구를 간략하게 설명하세요...', pt: 'Descreva brevemente seu estudo...', ar: 'صف دراستك باختصار...', hi: 'अपने अध्ययन का संक्षेप में वर्णन करें...', ru: 'Кратко опишите ваше исследование...', it: 'Descrivi brevemente il tuo studio...' },
  'createProject.studyType': { en: 'Study Type', zh: '研究类型', es: 'Tipo de estudio', fr: "Type d'étude", de: 'Studientyp', ja: '研究タイプ', ko: '연구 유형', pt: 'Tipo de estudo', ar: 'نوع الدراسة', hi: 'अध्ययन प्रकार', ru: 'Тип исследования', it: 'Tipo di studio' },
  'createProject.createStudy': { en: 'Create Study', zh: '创建研究', es: 'Crear estudio', fr: "Créer l'étude", de: 'Studie erstellen', ja: '研究を作成', ko: '연구 만들기', pt: 'Criar estudo', ar: 'إنشاء الدراسة', hi: 'अध्ययन बनाएं', ru: 'Создать исследование', it: 'Crea studio' },
  'createProject.continue': { en: 'Continue', zh: '继续', es: 'Continuar', fr: 'Continuer', de: 'Weiter', ja: '続行', ko: '계속', pt: 'Continuar', ar: 'متابعة', hi: 'जारी रखें', ru: 'Продолжить', it: 'Continua' },

  // Toast messages
  'toast.projectDeleted': { en: 'Project deleted', zh: '项目已删除', es: 'Proyecto eliminado', fr: 'Projet supprimé', de: 'Projekt gelöscht', ja: 'プロジェクトが削除されました', ko: '프로젝트 삭제됨', pt: 'Projeto excluído', ar: 'تم حذف المشروع', hi: 'प्रोजेक्ट हटा दिया गया', ru: 'Проект удалён', it: 'Progetto eliminato' },
  'toast.deleteFailed': { en: 'Failed to delete project', zh: '删除项目失败', es: 'Error al eliminar', fr: 'Échec de la suppression', de: 'Löschen fehlgeschlagen', ja: '削除に失敗', ko: '삭제 실패', pt: 'Falha ao excluir', ar: 'فشل الحذف', hi: 'हटाने में विफल', ru: 'Не удалось удалить', it: 'Eliminazione fallita' },
  'toast.duplicated': { en: 'Project duplicated', zh: '项目已复制', es: 'Proyecto duplicado', fr: 'Projet dupliqué', de: 'Projekt dupliziert', ja: 'プロジェクトが複製されました', ko: '프로젝트 복제됨', pt: 'Projeto duplicado', ar: 'تم نسخ المشروع', hi: 'प्रोजेक्ट डुप्लिकेट किया गया', ru: 'Проект скопирован', it: 'Progetto duplicato' },
  'toast.duplicateFailed': { en: 'Failed to duplicate project', zh: '复制项目失败', es: 'Error al duplicar', fr: 'Échec de la duplication', de: 'Duplizieren fehlgeschlagen', ja: '複製に失敗', ko: '복제 실패', pt: 'Falha ao duplicar', ar: 'فشل النسخ', hi: 'डुप्लिकेट करने में विफल', ru: 'Не удалось скопировать', it: 'Duplicazione fallita' },
  'toast.saveFailed': { en: 'Failed to save', zh: '保存失败', es: 'Error al guardar', fr: "Échec de l'enregistrement", de: 'Speichern fehlgeschlagen', ja: '保存に失敗', ko: '저장 실패', pt: 'Falha ao salvar', ar: 'فشل الحفظ', hi: 'सहेजने में विफल', ru: 'Не удалось сохранить', it: 'Salvataggio fallito' },
  'toast.saveProfileFailed': { en: 'Failed to save profile', zh: '保存个人资料失败', es: 'Error al guardar perfil', fr: "Échec de l'enregistrement du profil", de: 'Profil speichern fehlgeschlagen', ja: 'プロフィールの保存に失敗', ko: '프로필 저장 실패', pt: 'Falha ao salvar perfil', ar: 'فشل حفظ الملف الشخصي', hi: 'प्रोफ़ाइल सहेजने में विफल', ru: 'Не удалось сохранить профиль', it: 'Salvataggio profilo fallito' },
  'toast.researcherNotFound': { en: 'Researcher profile not found', zh: '未找到研究员档案', es: 'Perfil de investigador no encontrado', fr: 'Profil de chercheur introuvable', de: 'Forscherprofil nicht gefunden', ja: '研究者プロフィールが見つかりません', ko: '연구자 프로필을 찾을 수 없습니다', pt: 'Perfil de pesquisador não encontrado', ar: 'لم يتم العثور على ملف الباحث', hi: 'शोधकर्ता प्रोफ़ाइल नहीं मिली', ru: 'Профиль исследователя не найден', it: 'Profilo ricercatore non trovato' },

  // Button actions
  'action.duplicate': { en: 'Duplicate', zh: '复制', es: 'Duplicar', fr: 'Dupliquer', de: 'Duplizieren', ja: '複製', ko: '복제', pt: 'Duplicar', ar: 'نسخ', hi: 'डुप्लिकेट', ru: 'Дублировать', it: 'Duplica' },

  // Discover
  'discover.title': { en: 'Discover Studies', zh: '发现研究', es: 'Descubrir estudios', fr: 'Découvrir des études', de: 'Studien entdecken', ja: '研究を発見', ko: '연구 발견', pt: 'Descobrir estudos', ar: 'اكتشف الدراسات', hi: 'अध्ययन खोजें', ru: 'Обзор исследований', it: 'Scopri studi' },
  'discover.subtitle': { en: 'Find and join public research studies', zh: '查找并加入公开研究', es: 'Encuentra y únete a estudios públicos', fr: 'Trouvez et rejoignez des études publiques', de: 'Öffentliche Studien finden und beitreten', ja: '公開研究を見つけて参加', ko: '공개 연구를 찾고 참여하세요', pt: 'Encontre e participe de estudos públicos', ar: 'ابحث وانضم إلى الدراسات العامة', hi: 'सार्वजनिक अध्ययन खोजें और शामिल हों', ru: 'Найдите и присоединитесь к публичным исследованиям', it: 'Trova e partecipa a studi pubblici' },

  // Pricing
  'pricing.title': { en: 'Simple, Transparent Pricing', zh: '简单透明的定价', es: 'Precios simples y transparentes', fr: 'Tarification simple et transparente', de: 'Einfache, transparente Preise', ja: 'シンプルで透明な料金体系', ko: '간단하고 투명한 요금제', pt: 'Preços simples e transparentes', ar: 'أسعار بسيطة وشفافة', hi: 'सरल, पारदर्शी मूल्य निर्धारण', ru: 'Простые и прозрачные цены', it: 'Prezzi semplici e trasparenti' },
  'pricing.subtitle': { en: 'Start free, scale as you grow', zh: '免费开始，随需扩展', es: 'Comienza gratis, escala a medida que creces', fr: 'Commencez gratuitement, évoluez avec votre croissance', de: 'Starten Sie kostenlos, skalieren Sie mit Wachstum', ja: '無料で始めて、成長に応じてスケール', ko: '무료로 시작하고, 성장에 따라 확장', pt: 'Comece grátis, escale conforme cresce', ar: 'ابدأ مجاناً، وتوسع مع نموك', hi: 'मुफ्त शुरू करें, बढ़ने के साथ विस्तार करें', ru: 'Начните бесплатно, масштабируйтесь по мере роста', it: 'Inizia gratis, cresci con le tue esigenze' },

  // Features Page
  'features.title': { en: 'Features', zh: '功能', es: 'Características', fr: 'Fonctionnalités', de: 'Funktionen', ja: '機能', ko: '기능', pt: 'Recursos', ar: 'الميزات', hi: 'सुविधाएँ', ru: 'Возможности', it: 'Funzionalità' },
  'features.subtitle': { en: 'Everything you need to run world-class research', zh: '运行世界级研究所需的一切', es: 'Todo lo que necesitas para investigación de clase mundial', fr: 'Tout ce dont vous avez besoin pour une recherche de classe mondiale', de: 'Alles für erstklassige Forschung', ja: 'ワールドクラスの研究に必要なすべて', ko: '세계적 수준의 연구를 위한 모든 것', pt: 'Tudo para pesquisa de classe mundial', ar: 'كل ما تحتاجه لإجراء بحث عالمي المستوى', hi: 'विश्व स्तरीय शोध के लिए सब कुछ', ru: 'Всё для проведения исследований мирового уровня', it: 'Tutto per ricerche di livello mondiale' },

  // Researcher Settings
  'researcherSettings.title': { en: 'Researcher Settings', zh: '研究员设置', es: 'Configuración del investigador', fr: 'Paramètres du chercheur', de: 'Forscher-Einstellungen', ja: '研究者の設定', ko: '연구자 설정', pt: 'Configurações do pesquisador', ar: 'إعدادات الباحث', hi: 'शोधकर्ता सेटिंग्स', ru: 'Настройки исследователя', it: 'Impostazioni ricercatore' },
  'researcherSettings.organization': { en: 'Organization', zh: '组织', es: 'Organización', fr: 'Organisation', de: 'Organisation', ja: '組織', ko: '조직', pt: 'Organização', ar: 'المنظمة', hi: 'संगठन', ru: 'Организация', it: 'Organizzazione' },

  // Participant Settings
  'participantSettings.title': { en: 'Participant Settings', zh: '参与者设置', es: 'Configuración del participante', fr: 'Paramètres du participant', de: 'Teilnehmer-Einstellungen', ja: '参加者の設定', ko: '참가자 설정', pt: 'Configurações do participante', ar: 'إعدادات المشارك', hi: 'प्रतिभागी सेटिंग्स', ru: 'Настройки участника', it: 'Impostazioni partecipante' },

  // Library (Participant Library page)
  'library.searchPlaceholder': { en: 'Search participants...', zh: '搜索参与者...', es: 'Buscar participantes...', fr: 'Rechercher des participants...', de: 'Teilnehmer suchen...', ja: '参加者を検索...', ko: '참가자 검색...', pt: 'Pesquisar participantes...', ar: 'البحث عن مشاركين...', hi: 'प्रतिभागी खोजें...', ru: 'Поиск участников...', it: 'Cerca partecipanti...' },
  'library.inviteToStudy': { en: 'Invite to Study', zh: '邀请参加研究', es: 'Invitar al estudio', fr: "Inviter à l'étude", de: 'Zur Studie einladen', ja: '研究に招待', ko: '연구에 초대', pt: 'Convidar para estudo', ar: 'دعوة للدراسة', hi: 'अध्ययन में आमंत्रित करें', ru: 'Пригласить в исследование', it: 'Invita allo studio' },
  'library.selectStudy': { en: 'Select a study', zh: '选择研究', es: 'Seleccionar un estudio', fr: 'Sélectionner une étude', de: 'Studie auswählen', ja: '研究を選択', ko: '연구 선택', pt: 'Selecionar um estudo', ar: 'اختر دراسة', hi: 'अध्ययन चुनें', ru: 'Выберите исследование', it: 'Seleziona uno studio' },
  'library.sendInvitation': { en: 'Send Invitation', zh: '发送邀请', es: 'Enviar invitación', fr: 'Envoyer une invitation', de: 'Einladung senden', ja: '招待を送信', ko: '초대 보내기', pt: 'Enviar convite', ar: 'إرسال الدعوة', hi: 'आमंत्रण भेजें', ru: 'Отправить приглашение', it: 'Invia invito' },
  'library.noParticipants': { en: 'No participants found', zh: '未找到参与者', es: 'No se encontraron participantes', fr: 'Aucun participant trouvé', de: 'Keine Teilnehmer gefunden', ja: '参加者が見つかりません', ko: '참가자를 찾을 수 없습니다', pt: 'Nenhum participante encontrado', ar: 'لم يتم العثور على مشاركين', hi: 'कोई प्रतिभागी नहीं मिला', ru: 'Участники не найдены', it: 'Nessun partecipante trovato' },
};

interface I18nContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const I18nContext = createContext<I18nContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
  dir: 'ltr',
});

export const useI18n = () => useContext(I18nContext);

export const I18nProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('easyresearch_lang') as Language;
    return saved && LANGUAGES.some(l => l.code === saved) ? saved : 'en';
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('easyresearch_lang', newLang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[key]?.[lang] || translations[key]?.en || key;
  }, [lang]);

  const dir: 'ltr' | 'rtl' = LANGUAGES.find(l => l.code === lang)?.dir || 'ltr';

  return (
    <I18nContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </I18nContext.Provider>
  );
};
