// i18n support for Easier Research
import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'es' | 'fr' | 'de' | 'ja' | 'ko' | 'pt' | 'ar' | 'hi' | 'ru' | 'it';

export const LANGUAGES: { code: Language; name: string; nativeName: string; dir?: 'rtl' | 'ltr' }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
];

type TranslationDict = Record<string, Record<Language, string>>;

const translations: TranslationDict = {
  // Brand
  'brand.name': { en: 'Easier Research', zh: '轻易研究', es: 'Easier Research', fr: 'Easier Research', de: 'Easier Research', ja: 'Easier Research', ko: 'Easier Research', pt: 'Easier Research', ar: 'Easier Research', hi: 'Easier Research', ru: 'Easier Research', it: 'Easier Research' },
  'brand.copyright': { en: '© 2026 Easier Research. All rights reserved.', zh: '© 2026 轻易研究。保留所有权利。', es: '© 2026 Easier Research. Todos los derechos reservados.', fr: '© 2026 Easier Research. Tous droits réservés.', de: '© 2026 Easier Research. Alle Rechte vorbehalten.', ja: '© 2026 Easier Research. All rights reserved.', ko: '© 2026 Easier Research. 모든 권리 보유.', pt: '© 2026 Easier Research. Todos os direitos reservados.', ar: '© 2026 Easier Research. جميع الحقوق محفوظة.', hi: '© 2026 Easier Research. सर्वाधिकार सुरक्षित।', ru: '© 2026 Easier Research. Все права защищены.', it: '© 2026 Easier Research. Tutti i diritti riservati.' },

  // Landing page
  'landing.hero.title1': { en: 'Research made', zh: '让研究变得', es: 'Investigación', fr: 'La recherche', de: 'Forschung', ja: 'リサーチを', ko: '연구를', pt: 'Pesquisa', ar: 'البحث أصبح', hi: 'शोध को बनाएं', ru: 'Исследования', it: 'La ricerca' },
  'landing.hero.title2': { en: 'easier', zh: '更轻易', es: 'más fácil', fr: 'simplifiée', de: 'leicht gemacht', ja: 'もっと簡単に', ko: '더 쉽게', pt: 'mais fácil', ar: 'أسهل', hi: 'आसान', ru: 'проще', it: 'più facile' },
  'landing.hero.subtitle': { en: 'Create surveys, collect quality data, and analyze results — all in one place.', zh: '创建问卷、收集高质量数据并分析结果——尽在一处。', es: 'Crea encuestas, recopila datos de calidad y analiza resultados, todo en un solo lugar.', fr: 'Créez des sondages, collectez des données de qualité et analysez les résultats — tout en un seul endroit.', de: 'Erstellen Sie Umfragen, sammeln Sie qualitative Daten und analysieren Sie Ergebnisse — alles an einem Ort.', ja: 'アンケートを作成し、質の高いデータを収集し、結果を分析 — すべてを一か所で。', ko: '설문조사를 만들고, 양질의 데이터를 수집하고, 결과를 분석하세요 — 모든 것을 한 곳에서.', pt: 'Crie pesquisas, colete dados de qualidade e analise resultados — tudo em um só lugar.', ar: 'أنشئ استطلاعات، واجمع بيانات عالية الجودة، وحلل النتائج — كل ذلك في مكان واحد.', hi: 'सर्वेक्षण बनाएं, गुणवत्तापूर्ण डेटा एकत्र करें, और परिणामों का विश्लेषण करें — सब एक ही जगह।', ru: 'Создавайте опросы, собирайте качественные данные и анализируйте результаты — всё в одном месте.', it: 'Crea sondaggi, raccogli dati di qualità e analizza i risultati — tutto in un unico posto.' },
  'landing.getStarted': { en: 'Get started', zh: '开始使用', es: 'Comenzar', fr: 'Commencer', de: 'Loslegen', ja: '始める', ko: '시작하기', pt: 'Começar', ar: 'ابدأ الآن', hi: 'शुरू करें', ru: 'Начать', it: 'Inizia' },
  'landing.browseTemplates': { en: 'Browse templates', zh: '浏览模板', es: 'Ver plantillas', fr: 'Voir les modèles', de: 'Vorlagen ansehen', ja: 'テンプレートを見る', ko: '템플릿 보기', pt: 'Ver modelos', ar: 'تصفح القوالب', hi: 'टेम्पलेट देखें', ru: 'Шаблоны', it: 'Sfoglia modelli' },
  'landing.freeForever': { en: 'Free forever · No credit card required', zh: '永久免费 · 无需信用卡', es: 'Gratis para siempre · Sin tarjeta de crédito', fr: 'Gratuit pour toujours · Aucune carte de crédit requise', de: 'Für immer kostenlos · Keine Kreditkarte erforderlich', ja: '永久無料・クレジットカード不要', ko: '영원히 무료 · 신용카드 불필요', pt: 'Grátis para sempre · Sem cartão de crédito', ar: 'مجاني للأبد · لا حاجة لبطاقة ائتمان', hi: 'हमेशा मुफ्त · क्रेडिट कार्ड की आवश्यकता नहीं', ru: 'Бесплатно навсегда · Кредитная карта не нужна', it: 'Gratis per sempre · Nessuna carta di credito' },
  'landing.features.title': { en: 'Everything you need', zh: '您需要的一切', es: 'Todo lo que necesitas', fr: 'Tout ce dont vous avez besoin', de: 'Alles was Sie brauchen', ja: '必要なものすべて', ko: '필요한 모든 것', pt: 'Tudo o que você precisa', ar: 'كل ما تحتاجه', hi: 'आपको जो कुछ भी चाहिए', ru: 'Всё, что вам нужно', it: 'Tutto ciò di cui hai bisogno' },
  'landing.features.subtitle': { en: 'Powerful tools, zero complexity.', zh: '强大的工具，零复杂度。', es: 'Herramientas poderosas, cero complejidad.', fr: 'Des outils puissants, zéro complexité.', de: 'Leistungsstarke Tools, null Komplexität.', ja: '強力なツール、ゼロの複雑さ。', ko: '강력한 도구, 제로 복잡성.', pt: 'Ferramentas poderosas, complexidade zero.', ar: 'أدوات قوية، صفر تعقيد.', hi: 'शक्तिशाली उपकरण, शून्य जटिलता।', ru: 'Мощные инструменты, ноль сложности.', it: 'Strumenti potenti, zero complessità.' },
  'landing.howItWorks': { en: 'Three steps', zh: '三个步骤', es: 'Tres pasos', fr: 'Trois étapes', de: 'Drei Schritte', ja: '3つのステップ', ko: '세 단계', pt: 'Três passos', ar: 'ثلاث خطوات', hi: 'तीन चरण', ru: 'Три шага', it: 'Tre passaggi' },
  'landing.useCases.title': { en: 'Built for every field', zh: '为每个领域而建', es: 'Creado para cada campo', fr: 'Conçu pour tous les domaines', de: 'Für jedes Fachgebiet', ja: 'あらゆる分野に対応', ko: '모든 분야를 위해', pt: 'Feito para todos os campos', ar: 'مصمم لكل مجال', hi: 'हर क्षेत्र के लिए बनाया गया', ru: 'Для любой области', it: 'Per ogni settore' },
  'landing.cta.title': { en: 'Ready to start?', zh: '准备开始了吗？', es: '¿Listo para comenzar?', fr: 'Prêt à commencer ?', de: 'Bereit loszulegen?', ja: '始める準備はできましたか？', ko: '시작할 준비가 되셨나요?', pt: 'Pronto para começar?', ar: 'مستعد للبدء؟', hi: 'शुरू करने के लिए तैयार?', ru: 'Готовы начать?', it: 'Pronto per iniziare?' },
  'landing.cta.subtitle': { en: 'Join researchers who trust Easier for their studies.', zh: '加入信赖 Easier 的研究人员。', es: 'Únete a investigadores que confían en Easier.', fr: 'Rejoignez les chercheurs qui font confiance à Easier.', de: 'Schließen Sie sich Forschern an, die Easier vertrauen.', ja: 'Easierを信頼する研究者に加わりましょう。', ko: 'Easier를 신뢰하는 연구자들과 함께하세요.', pt: 'Junte-se a pesquisadores que confiam no Easier.', ar: 'انضم إلى الباحثين الذين يثقون بـ Easier.', hi: 'Easier पर भरोसा करने वाले शोधकर्ताओं से जुड़ें।', ru: 'Присоединяйтесь к исследователям, которые доверяют Easier.', it: 'Unisciti ai ricercatori che si fidano di Easier.' },
  'landing.cta.button': { en: 'Create your first survey', zh: '创建您的第一个问卷', es: 'Crea tu primera encuesta', fr: 'Créez votre premier sondage', de: 'Erstellen Sie Ihre erste Umfrage', ja: '最初のアンケートを作成', ko: '첫 설문조사를 만드세요', pt: 'Crie sua primeira pesquisa', ar: 'أنشئ استطلاعك الأول', hi: 'अपना पहला सर्वेक्षण बनाएं', ru: 'Создайте свой первый опрос', it: 'Crea il tuo primo sondaggio' },

  // AI Features section
  'landing.ai.title': { en: 'Built-in AI Features', zh: 'AI驱动的研究', es: 'Investigación con IA', fr: 'Recherche alimentée par l\'IA', de: 'KI-gestützte Forschung', ja: 'AI搭載リサーチ', ko: 'AI 기반 연구', pt: 'Pesquisa com IA', ar: 'بحث مدعوم بالذكاء الاصطناعي', hi: 'AI-संचालित अनुसंधान', ru: 'Исследования с ИИ', it: 'Ricerca potenziata dall\'IA' },
  'landing.ai.subtitle': { en: 'AI writes survey questions from your topic', zh: '让AI处理繁重工作，让您专注于洞察。', es: 'Deja que la IA haga el trabajo pesado para que puedas enfocarte en los insights.', fr: 'Laissez l\'IA faire le gros du travail pour vous concentrer sur les insights.', de: 'Lassen Sie KI die schwere Arbeit erledigen, damit Sie sich auf Erkenntnisse konzentrieren können.', ja: 'AIに面倒な作業を任せて、インサイトに集中しましょう。', ko: 'AI가 무거운 작업을 처리하여 인사이트에 집중하세요.', pt: 'Deixe a IA fazer o trabalho pesado para que você possa focar nos insights.', ar: 'دع الذكاء الاصطناعي يتولى الأعمال الشاقة حتى تتمكن من التركيز على الرؤى.', hi: 'AI को भारी काम करने दें ताकि आप अंतर्दृष्टि पर ध्यान दे सकें।', ru: 'Пусть ИИ выполняет тяжёлую работу, а вы сосредоточитесь на аналитике.', it: 'Lascia che l\'IA faccia il lavoro pesante per concentrarti sugli insight.' },
  'landing.ai.cta': { en: 'Participants answer by voice or chatbot', zh: '创建、编辑和分析——全部由AI完成', es: 'Crea, edita y analiza — todo con IA', fr: 'Créez, éditez et analysez — tout avec l\'IA', de: 'Erstellen, bearbeiten und analysieren — alles mit KI', ja: '作成、編集、分析 — すべてAIで', ko: '만들고, 편집하고, 분석하세요 — 모두 AI로', pt: 'Crie, edite e analise — tudo com IA', ar: 'أنشئ وحرر وحلل — كل شيء بالذكاء الاصطناعي', hi: 'बनाएं, संपादित करें, और विश्लेषण करें — सब AI के साथ', ru: 'Создавайте, редактируйте и анализируйте — всё с ИИ', it: 'Crea, modifica e analizza — tutto con l\'IA' },
  'landing.ai.fullDesc': { en: 'Describe your research topic and AI generates a complete questionnaire. Participants can speak answers or chat with an AI assistant instead of typing.', zh: '从构建研究到收集回复，AI承担繁重工作。研究人员用AI设计，参与者用AI回答，每个人都节省时间。', es: 'Desde construir tu investigación hasta recopilar respuestas, la IA hace el trabajo pesado. Los investigadores diseñan con IA. Los participantes responden con IA. Todos ahorran tiempo.', fr: 'De la construction de votre recherche à la collecte des réponses, l\'IA fait le gros du travail. Les chercheurs conçoivent avec l\'IA. Les participants répondent avec l\'IA. Tout le monde gagne du temps.', de: 'Vom Aufbau Ihrer Forschung bis zur Erfassung der Antworten übernimmt KI die schwere Arbeit. Forscher entwerfen mit KI. Teilnehmer antworten mit KI. Alle sparen Zeit.', ja: '研究の構築から回答の収集まで、AIが面倒な作業を担当。研究者はAIで設計し、参加者はAIで回答。全員が時間を節約。', ko: '연구 구축부터 응답 수집까지 AI가 무거운 작업을 처리합니다. 연구자는 AI로 설계하고, 참가자는 AI로 답변합니다. 모두가 시간을 절약합니다.', pt: 'Desde a construção da pesquisa até a coleta de respostas, a IA faz o trabalho pesado. Pesquisadores projetam com IA. Participantes respondem com IA. Todos economizam tempo.', ar: 'من بناء بحثك إلى جمع الردود، يتولى الذكاء الاصطناعي العمل الشاق. الباحثون يصممون بالذكاء الاصطناعي. المشاركون يجيبون بالذكاء الاصطناعي. الجميع يوفر الوقت.', hi: 'शोध बनाने से लेकर प्रतिक्रियाएं एकत्र करने तक, AI भारी काम संभालता है। शोधकर्ता AI से डिज़ाइन करते हैं। प्रतिभागी AI से जवाब देते हैं। सभी समय बचाते हैं।', ru: 'От создания исследования до сбора ответов — ИИ берёт на себя тяжёлую работу. Исследователи проектируют с ИИ. Участники отвечают с ИИ. Все экономят время.', it: 'Dalla costruzione della ricerca alla raccolta delle risposte, l\'IA fa il lavoro pesante. I ricercatori progettano con l\'IA. I partecipanti rispondono con l\'IA. Tutti risparmiano tempo.' },
  'landing.ai.cap1': { en: 'AI generates questions from your topic', zh: 'AI从您的主题生成问题', es: 'IA genera preguntas de tu tema', fr: 'L\'IA génère des questions', de: 'KI generiert Fragen', ja: 'AIが質問を生成', ko: 'AI가 질문 생성', pt: 'IA gera perguntas', ar: 'الذكاء الاصطناعي يولد الأسئلة', hi: 'AI प्रश्न उत्पन्न करता है', ru: 'ИИ генерирует вопросы', it: 'L\'IA genera domande' },
  'landing.ai.cap2': { en: 'Voice input — speak instead of type', zh: '语音输入——说话代替打字', es: 'Entrada de voz — habla en lugar de escribir', fr: 'Entrée vocale — parlez au lieu de taper', de: 'Spracheingabe — sprechen statt tippen', ja: '音声入力 — タイプの代わりに話す', ko: '음성 입력 — 타이핑 대신 말하기', pt: 'Entrada de voz — fale em vez de digitar', ar: 'إدخال صوتي — تحدث بدلاً من الكتابة', hi: 'वॉयस इनपुट — टाइप करने के बजाय बोलें', ru: 'Голосовой ввод — говорите вместо печати', it: 'Input vocale — parla invece di digitare' },
  'landing.ai.cap3': { en: 'Chatbot helps participants answer', zh: '聊天机器人帮助参与者回答', es: 'Chatbot ayuda a los participantes', fr: 'Chatbot aide les participants', de: 'Chatbot hilft Teilnehmern', ja: 'チャットボットが参加者を支援', ko: '챗봇이 참가자를 도움', pt: 'Chatbot ajuda participantes', ar: 'روبوت الدردشة يساعد المشاركين', hi: 'चैटबॉट प्रतिभागियों की मदद करता है', ru: 'Чат-бот помогает участникам', it: 'Chatbot aiuta i partecipanti' },
  'landing.ai.tryButton': { en: 'Try it free', zh: '试用AI驱动的研究', es: 'Probar investigación con IA', fr: 'Essayer la recherche IA', de: 'KI-Forschung ausprobieren', ja: 'AI搭載リサーチを試す', ko: 'AI 기반 연구 시도', pt: 'Experimentar pesquisa com IA', ar: 'جرب البحث بالذكاء الاصطناعي', hi: 'AI-संचालित अनुसंधान आज़माएं', ru: 'Попробовать ИИ-исследования', it: 'Prova la ricerca con IA' },

  // Common
  'common.back': { en: 'Back', zh: '返回', es: 'Atrás', fr: 'Retour', de: 'Zurück', ja: '戻る', ko: '뒤로', pt: 'Voltar', ar: 'رجوع', hi: 'वापस', ru: 'Назад', it: 'Indietro' },
  'common.next': { en: 'Next', zh: '下一步', es: 'Siguiente', fr: 'Suivant', de: 'Weiter', ja: '次へ', ko: '다음', pt: 'Próximo', ar: 'التالي', hi: 'अगला', ru: 'Далее', it: 'Avanti' },
  'common.submit': { en: 'Submit', zh: '提交', es: 'Enviar', fr: 'Soumettre', de: 'Absenden', ja: '送信', ko: '제출', pt: 'Enviar', ar: 'إرسال', hi: 'जमा करें', ru: 'Отправить', it: 'Invia' },
  'common.cancel': { en: 'Cancel', zh: '取消', es: 'Cancelar', fr: 'Annuler', de: 'Abbrechen', ja: 'キャンセル', ko: '취소', pt: 'Cancelar', ar: 'إلغاء', hi: 'रद्द करें', ru: 'Отмена', it: 'Annulla' },
  'common.save': { en: 'Save', zh: '保存', es: 'Guardar', fr: 'Enregistrer', de: 'Speichern', ja: '保存', ko: '저장', pt: 'Salvar', ar: 'حفظ', hi: 'सहेजें', ru: 'Сохранить', it: 'Salva' },
  'common.loading': { en: 'Loading...', zh: '加载中...', es: 'Cargando...', fr: 'Chargement...', de: 'Laden...', ja: '読み込み中...', ko: '로딩 중...', pt: 'Carregando...', ar: 'جاري التحميل...', hi: 'लोड हो रहा है...', ru: 'Загрузка...', it: 'Caricamento...' },
  'common.signIn': { en: 'Sign In', zh: '登录', es: 'Iniciar sesión', fr: 'Se connecter', de: 'Anmelden', ja: 'ログイン', ko: '로그인', pt: 'Entrar', ar: 'تسجيل الدخول', hi: 'साइन इन', ru: 'Войти', it: 'Accedi' },
  'common.signOut': { en: 'Sign Out', zh: '退出登录', es: 'Cerrar sesión', fr: 'Se déconnecter', de: 'Abmelden', ja: 'ログアウト', ko: '로그아웃', pt: 'Sair', ar: 'تسجيل الخروج', hi: 'साइन आउट', ru: 'Выйти', it: 'Esci' },
  'common.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'common.search': { en: 'Search', zh: '搜索', es: 'Buscar', fr: 'Rechercher', de: 'Suchen', ja: '検索', ko: '검색', pt: 'Buscar', ar: 'بحث', hi: 'खोजें', ru: 'Поиск', it: 'Cerca' },

  // Dashboard
  'dashboard.myStudies': { en: 'My Studies', zh: '我的研究', es: 'Mis Estudios', fr: 'Mes Études', de: 'Meine Studien', ja: 'マイスタディ', ko: '내 연구', pt: 'Meus Estudos', ar: 'دراساتي', hi: 'मेरे अध्ययन', ru: 'Мои исследования', it: 'I miei studi' },
  'dashboard.newProject': { en: 'New Project', zh: '新项目', es: 'Nuevo Proyecto', fr: 'Nouveau Projet', de: 'Neues Projekt', ja: '新規プロジェクト', ko: '새 프로젝트', pt: 'Novo Projeto', ar: 'مشروع جديد', hi: 'नया प्रोजेक्ट', ru: 'Новый проект', it: 'Nuovo progetto' },
  'dashboard.aiCreate': { en: 'AI Create', zh: 'AI创建', es: 'Crear con IA', fr: 'Créer avec IA', de: 'KI erstellen', ja: 'AI作成', ko: 'AI 생성', pt: 'Criar com IA', ar: 'إنشاء بالذكاء الاصطناعي', hi: 'AI बनाएं', ru: 'ИИ создание', it: 'Crea con IA' },
  'dashboard.noProjects': { en: 'No projects yet', zh: '还没有项目', es: 'Aún no hay proyectos', fr: 'Pas encore de projets', de: 'Noch keine Projekte', ja: 'まだプロジェクトがありません', ko: '아직 프로젝트가 없습니다', pt: 'Nenhum projeto ainda', ar: 'لا توجد مشاريع بعد', hi: 'अभी कोई प्रोजेक्ट नहीं', ru: 'Пока нет проектов', it: 'Nessun progetto ancora' },

  // Nav
  'nav.home': { en: 'Home', zh: '首页', es: 'Inicio', fr: 'Accueil', de: 'Startseite', ja: 'ホーム', ko: '홈', pt: 'Início', ar: 'الرئيسية', hi: 'होम', ru: 'Главная', it: 'Home' },
  'nav.myStudies': { en: 'My Studies', zh: '我的研究', es: 'Mis Estudios', fr: 'Mes Études', de: 'Meine Studien', ja: 'マイスタディ', ko: '내 연구', pt: 'Meus Estudos', ar: 'دراساتي', hi: 'मेरे अध्ययन', ru: 'Мои исследования', it: 'I miei studi' },
  'nav.discover': { en: 'Discover', zh: '发现', es: 'Descubrir', fr: 'Découvrir', de: 'Entdecken', ja: '探す', ko: '탐색', pt: 'Descobrir', ar: 'اكتشف', hi: 'खोजें', ru: 'Обзор', it: 'Scopri' },
  'nav.participants': { en: 'Participants', zh: '参与者', es: 'Participantes', fr: 'Participants', de: 'Teilnehmer', ja: '参加者', ko: '참여자', pt: 'Participantes', ar: 'المشاركون', hi: 'प्रतिभागी', ru: 'Участники', it: 'Partecipanti' },
  'nav.inbox': { en: 'Inbox', zh: '收件箱', es: 'Bandeja', fr: 'Boîte', de: 'Posteingang', ja: '受信箱', ko: '받은편지함', pt: 'Caixa', ar: 'البريد', hi: 'इनबॉक्स', ru: 'Входящие', it: 'Posta' },
  'nav.templates': { en: 'Templates', zh: '模板', es: 'Plantillas', fr: 'Modèles', de: 'Vorlagen', ja: 'テンプレート', ko: '템플릿', pt: 'Modelos', ar: 'القوالب', hi: 'टेम्पलेट', ru: 'Шаблоны', it: 'Modelli' },
  'nav.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'nav.research': { en: 'Research', zh: '研究', es: 'Investigación', fr: 'Recherche', de: 'Forschung', ja: '研究', ko: '연구', pt: 'Pesquisa', ar: 'البحث', hi: 'अनुसंधान', ru: 'Исследования', it: 'Ricerca' },
  'nav.dashboard': { en: 'Dashboard', zh: '仪表盘', es: 'Panel', fr: 'Tableau de bord', de: 'Dashboard', ja: 'ダッシュボード', ko: '대시보드', pt: 'Painel', ar: 'لوحة القيادة', hi: 'डैशबोर्ड', ru: 'Панель', it: 'Dashboard' },
  'nav.features': { en: 'Features', zh: '功能', es: 'Funciones', fr: 'Fonctionnalités', de: 'Funktionen', ja: '機能', ko: '기능', pt: 'Recursos', ar: 'الميزات', hi: 'सुविधाएँ', ru: 'Функции', it: 'Funzionalità' },
  'nav.joinStudies': { en: 'Join Studies', zh: '参加研究', es: 'Unirse a Estudios', fr: 'Rejoindre des Études', de: 'Studien beitreten', ja: '研究に参加', ko: '연구 참여', pt: 'Participar de Estudos', ar: 'انضم للدراسات', hi: 'अध्ययन में शामिल हों', ru: 'Присоединиться к исследованиям', it: 'Partecipa a Studi' },
  'nav.joinStudies.desc': { en: 'Find studies to participate in — some offer compensation', zh: '寻找可参与的研究——部分研究提供报酬', es: 'Encuentra estudios en los que participar — algunos ofrecen compensación', fr: 'Trouvez des études auxquelles participer — certaines offrent une rémunération', de: 'Finden Sie Studien, an denen Sie teilnehmen können — einige bieten Vergütung', ja: '参加できる研究を見つける — 報酬がある場合も', ko: '참여할 연구를 찾으세요 — 일부는 보상을 제공합니다', pt: 'Encontre estudos para participar — alguns oferecem compensação', ar: 'ابحث عن دراسات للمشاركة فيها — بعضها يقدم تعويضاً', hi: 'भाग लेने के लिए अध्ययन खोजें — कुछ मुआवज़ा प्रदान करते हैं', ru: 'Найдите исследования для участия — некоторые предлагают вознаграждение', it: 'Trova studi a cui partecipare — alcuni offrono compenso' },
  'landing.ai.voiceDesc': { en: 'Voice-powered answering — participants can speak every answer, get chatbot assistance, and complete surveys without typing a single word.', zh: '语音驱动答题——参与者可以用语音回答每个问题，获得聊天机器人辅助，无需打一个字即可完成问卷。', es: 'Respuestas por voz — los participantes pueden hablar cada respuesta, obtener asistencia del chatbot y completar encuestas sin escribir una sola palabra.', fr: 'Réponses vocales — les participants peuvent dicter chaque réponse, obtenir l\'aide du chatbot et compléter les enquêtes sans taper un seul mot.', de: 'Sprachgesteuerte Antworten — Teilnehmer können jede Antwort sprechen, Chatbot-Hilfe erhalten und Umfragen abschließen, ohne ein einziges Wort zu tippen.', ja: '音声回答 — 参加者はすべての回答を音声で行い、チャットボットの支援を受け、一文字も入力せずにアンケートを完了できます。', ko: '음성 응답 — 참가자는 모든 답변을 음성으로 말하고, 챗봇 도움을 받으며, 한 글자도 입력하지 않고 설문을 완료할 수 있습니다.', pt: 'Respostas por voz — participantes podem falar cada resposta, obter assistência do chatbot e completar pesquisas sem digitar uma única palavra.', ar: 'إجابات صوتية — يمكن للمشاركين نطق كل إجابة والحصول على مساعدة الروبوت وإكمال الاستبيانات دون كتابة كلمة واحدة.', hi: 'वॉइस-संचालित उत्तर — प्रतिभागी हर उत्तर बोल सकते हैं, चैटबॉट सहायता प्राप्त कर सकते हैं, और एक भी शब्द टाइप किए बिना सर्वेक्षण पूरा कर सकते हैं।', ru: 'Голосовые ответы — участники могут проговаривать каждый ответ, получать помощь чат-бота и проходить опросы, не набирая ни единого слова.', it: 'Risposte vocali — i partecipanti possono parlare ogni risposta, ricevere assistenza dal chatbot e completare sondaggi senza digitare una sola parola.' },

  // Feature names for landing page
  'feature.questionTypes': { en: '13+ Question Types', zh: '13+题型', es: '13+ Tipos de Preguntas', fr: '13+ Types de Questions', de: '13+ Fragetypen', ja: '13以上の質問タイプ', ko: '13+ 질문 유형', pt: '13+ Tipos de Perguntas', ar: '13+ نوع من الأسئلة', hi: '13+ प्रश्न प्रकार', ru: '13+ типов вопросов', it: '13+ Tipi di Domande' },
  'feature.questionTypes.desc': { en: 'From choice to NPS, Likert, sliders, and more.', zh: '从选择题到NPS、李克特量表、滑块等。', es: 'Desde opciones múltiples hasta NPS, Likert, deslizadores y más.', fr: 'Du choix au NPS, Likert, curseurs et plus.', de: 'Von Auswahl über NPS, Likert, Schieberegler und mehr.', ja: '選択問題からNPS、リッカート、スライダーまで。', ko: '선택형부터 NPS, 리커트, 슬라이더 등.', pt: 'De múltipla escolha a NPS, Likert, controles deslizantes e mais.', ar: 'من الاختيار إلى NPS وليكرت والمنزلقات والمزيد.', hi: 'चॉइस से NPS, लिकर्ट, स्लाइडर और अधिक।', ru: 'От выбора до NPS, шкалы Ликерта, слайдеров и др.', it: 'Da scelte multiple a NPS, Likert, cursori e altro.' },
  'feature.skipLogic': { en: 'Skip Logic', zh: '跳转逻辑', es: 'Lógica de salto', fr: 'Logique de saut', de: 'Sprunglogik', ja: 'スキップロジック', ko: '건너뛰기 로직', pt: 'Lógica de pulo', ar: 'منطق التخطي', hi: 'स्किप लॉजिक', ru: 'Логика пропуска', it: 'Logica di salto' },
  'feature.skipLogic.desc': { en: 'Dynamic surveys that adapt to each response.', zh: '根据每个回答动态调整的问卷。', es: 'Encuestas dinámicas que se adaptan a cada respuesta.', fr: 'Sondages dynamiques qui s\'adaptent à chaque réponse.', de: 'Dynamische Umfragen, die sich an jede Antwort anpassen.', ja: '各回答に適応する動的アンケート。', ko: '각 응답에 적응하는 동적 설문조사.', pt: 'Pesquisas dinâmicas que se adaptam a cada resposta.', ar: 'استطلاعات ديناميكية تتكيف مع كل إجابة.', hi: 'प्रत्येक प्रतिक्रिया के अनुरूप गतिशील सर्वेक्षण।', ru: 'Динамические опросы, адаптирующиеся к каждому ответу.', it: 'Sondaggi dinamici che si adattano a ogni risposta.' },
  'feature.webBased': { en: 'Web-Based', zh: '网页版', es: 'Basado en Web', fr: 'En ligne', de: 'Web-basiert', ja: 'ウェブベース', ko: '웹 기반', pt: 'Baseado na Web', ar: 'على الويب', hi: 'वेब-आधारित', ru: 'Веб-версия', it: 'Web-Based' },
  'feature.webBased.desc': { en: 'Access from anywhere. No installs required.', zh: '随时随地访问，无需安装。', es: 'Accede desde cualquier lugar. Sin instalación.', fr: 'Accédez de n\'importe où. Aucune installation requise.', de: 'Zugriff von überall. Keine Installation erforderlich.', ja: 'どこからでもアクセス。インストール不要。', ko: '어디서든 접근 가능. 설치 불필요.', pt: 'Acesse de qualquer lugar. Sem instalação.', ar: 'الوصول من أي مكان. لا حاجة للتثبيت.', hi: 'कहीं से भी पहुंचें। कोई इंस्टॉल नहीं।', ru: 'Доступ отовсюду. Установка не требуется.', it: 'Accedi ovunque. Nessuna installazione.' },
  'feature.mobileFriendly': { en: 'Mobile-First', zh: '移动优先', es: 'Móvil Primero', fr: 'Mobile-First', de: 'Mobile-First', ja: 'モバイルファースト', ko: '모바일 우선', pt: 'Mobile-First', ar: 'الهاتف أولاً', hi: 'मोबाइल-फर्स्ट', ru: 'Мобильная версия', it: 'Mobile-First' },
  'feature.mobileFriendly.desc': { en: 'Beautiful on every device, every time.', zh: '在每台设备上都完美呈现。', es: 'Hermoso en cualquier dispositivo.', fr: 'Beau sur chaque appareil.', de: 'Schön auf jedem Gerät.', ja: 'すべてのデバイスで美しく。', ko: '모든 기기에서 아름답게.', pt: 'Bonito em qualquer dispositivo.', ar: 'جميل على كل جهاز.', hi: 'हर डिवाइस पर सुंदर।', ru: 'Красиво на любом устройстве.', it: 'Bello su ogni dispositivo.' },
  'feature.secure': { en: 'Secure', zh: '安全', es: 'Seguro', fr: 'Sécurisé', de: 'Sicher', ja: 'セキュア', ko: '보안', pt: 'Seguro', ar: 'آمن', hi: 'सुरक्षित', ru: 'Безопасно', it: 'Sicuro' },
  'feature.secure.desc': { en: 'Encrypted storage with row-level security.', zh: '加密存储，行级安全策略。', es: 'Almacenamiento encriptado con seguridad a nivel de fila.', fr: 'Stockage chiffré avec sécurité au niveau des lignes.', de: 'Verschlüsselte Speicherung mit Sicherheit auf Zeilenebene.', ja: '行レベルセキュリティによる暗号化ストレージ。', ko: '행 수준 보안이 있는 암호화 스토리지.', pt: 'Armazenamento criptografado com segurança em nível de linha.', ar: 'تخزين مشفر مع أمان على مستوى الصف.', hi: 'पंक्ति-स्तरीय सुरक्षा के साथ एन्क्रिप्टेड स्टोरेज।', ru: 'Зашифрованное хранилище с безопасностью на уровне строк.', it: 'Archiviazione crittografata con sicurezza a livello di riga.' },
  'feature.analytics': { en: 'Real-Time Analytics', zh: '实时分析', es: 'Análisis en Tiempo Real', fr: 'Analyses en Temps Réel', de: 'Echtzeit-Analysen', ja: 'リアルタイム分析', ko: '실시간 분석', pt: 'Análise em Tempo Real', ar: 'تحليلات فورية', hi: 'रीयल-टाइम एनालिटिक्स', ru: 'Аналитика в реальном времени', it: 'Analisi in Tempo Reale' },
  'feature.analytics.desc': { en: 'Live dashboards as responses flow in.', zh: '实时仪表板，随着回复到来。', es: 'Paneles en vivo a medida que llegan las respuestas.', fr: 'Tableaux de bord en direct à mesure que les réponses arrivent.', de: 'Live-Dashboards, sobald Antworten eingehen.', ja: '回答が入るたびにライブダッシュボード。', ko: '응답이 들어오면 실시간 대시보드.', pt: 'Painéis ao vivo conforme as respostas chegam.', ar: 'لوحات معلومات مباشرة مع تدفق الردود.', hi: 'प्रतिक्रियाएं आने पर लाइव डैशबोर्ड।', ru: 'Живые дашборды по мере поступления ответов.', it: 'Dashboard in tempo reale man mano che le risposte arrivano.' },
  'feature.export': { en: 'Data Export', zh: '数据导出', es: 'Exportar Datos', fr: 'Export de Données', de: 'Datenexport', ja: 'データエクスポート', ko: '데이터 내보내기', pt: 'Exportar Dados', ar: 'تصدير البيانات', hi: 'डेटा निर्यात', ru: 'Экспорт данных', it: 'Esportazione Dati' },
  'feature.export.desc': { en: 'CSV, Excel, and JSON exports.', zh: 'CSV、Excel和JSON导出。', es: 'Exportaciones en CSV, Excel y JSON.', fr: 'Exports CSV, Excel et JSON.', de: 'CSV-, Excel- und JSON-Exporte.', ja: 'CSV、Excel、JSONエクスポート。', ko: 'CSV, Excel, JSON 내보내기.', pt: 'Exportações em CSV, Excel e JSON.', ar: 'تصدير بتنسيقات CSV وExcel وJSON.', hi: 'CSV, Excel, और JSON निर्यात।', ru: 'Экспорт в CSV, Excel и JSON.', it: 'Esportazioni CSV, Excel e JSON.' },
  'feature.templates': { en: 'Research Templates', zh: '研究模板', es: 'Plantillas de Investigación', fr: 'Modèles de Recherche', de: 'Forschungsvorlagen', ja: '研究テンプレート', ko: '연구 템플릿', pt: 'Modelos de Pesquisa', ar: 'قوالب البحث', hi: 'शोध टेम्पलेट', ru: 'Шаблоны исследований', it: 'Modelli di Ricerca' },
  'feature.templates.desc': { en: 'Start fast with ready-made templates.', zh: '使用现成模板快速开始。', es: 'Comienza rápido con plantillas listas.', fr: 'Commencez vite avec des modèles prêts à l\'emploi.', de: 'Starten Sie schnell mit fertigen Vorlagen.', ja: 'テンプレートですぐに始められます。', ko: '기성 템플릿으로 빠르게 시작하세요.', pt: 'Comece rápido com modelos prontos.', ar: 'ابدأ بسرعة مع قوالب جاهزة.', hi: 'तैयार टेम्पलेट के साथ तेज़ी से शुरू करें।', ru: 'Начните быстро с готовыми шаблонами.', it: 'Inizia velocemente con modelli pronti.' },

  // AI feature names
  'ai.projectBuilder': { en: 'AI Project Builder', zh: 'AI项目构建器', es: 'Constructor de Proyectos IA', fr: 'Constructeur de Projets IA', de: 'KI-Projektersteller', ja: 'AIプロジェクトビルダー', ko: 'AI 프로젝트 빌더', pt: 'Construtor de Projetos IA', ar: 'منشئ المشاريع بالذكاء الاصطناعي', hi: 'AI प्रोजेक्ट बिल्डर', ru: 'ИИ-конструктор проектов', it: 'Costruttore Progetti IA' },
  'ai.projectBuilder.desc': { en: 'Describe your research and AI creates the entire project with questionnaires and questions.', zh: '描述您的研究，AI将自动创建包含问卷和问题的完整项目。', es: 'Describe tu investigación y la IA crea todo el proyecto con cuestionarios y preguntas.', fr: 'Décrivez votre recherche et l\'IA crée le projet entier avec questionnaires et questions.', de: 'Beschreiben Sie Ihre Forschung und KI erstellt das gesamte Projekt mit Fragebögen und Fragen.', ja: '研究を説明するだけで、AIがアンケートと質問を含むプロジェクト全体を作成します。', ko: '연구를 설명하면 AI가 설문지와 질문을 포함한 전체 프로젝트를 생성합니다.', pt: 'Descreva sua pesquisa e a IA cria o projeto inteiro com questionários e perguntas.', ar: 'صف بحثك وسيقوم الذكاء الاصطناعي بإنشاء المشروع بالكامل مع الاستبيانات والأسئلة.', hi: 'अपने शोध का वर्णन करें और AI प्रश्नावली और प्रश्नों के साथ पूरा प्रोजेक्ट बनाएगा।', ru: 'Опишите своё исследование, и ИИ создаст весь проект с анкетами и вопросами.', it: 'Descrivi la tua ricerca e l\'IA crea l\'intero progetto con questionari e domande.' },
  'ai.autoAnswer': { en: 'AI Auto-Answer', zh: 'AI自动回答', es: 'Respuesta Automática IA', fr: 'Réponse Auto IA', de: 'KI Auto-Antwort', ja: 'AI自動回答', ko: 'AI 자동 답변', pt: 'Resposta Automática IA', ar: 'إجابة تلقائية بالذكاء الاصطناعي', hi: 'AI ऑटो-उत्तर', ru: 'ИИ авто-ответ', it: 'Risposta Automatica IA' },
  'ai.autoAnswer.desc': { en: 'AI predicts likely answers for participants to review and correct, speeding up completion.', zh: 'AI预测可能的答案供参与者审查和修正，加快完成速度。', es: 'La IA predice respuestas probables para que los participantes revisen y corrijan.', fr: 'L\'IA prédit les réponses probables pour que les participants vérifient et corrigent.', de: 'KI sagt wahrscheinliche Antworten voraus, die Teilnehmer überprüfen und korrigieren können.', ja: 'AIが回答を予測し、参加者が確認・修正できるため、回答が速くなります。', ko: 'AI가 참가자가 검토하고 수정할 수 있는 답변을 예측하여 완료 속도를 높입니다.', pt: 'A IA prevê respostas prováveis para os participantes revisarem e corrigirem.', ar: 'يتنبأ الذكاء الاصطناعي بالإجابات المحتملة ليراجعها المشاركون ويصححوها.', hi: 'AI संभावित उत्तरों की भविष्यवाणी करता है ताकि प्रतिभागी समीक्षा और सुधार कर सकें।', ru: 'ИИ предсказывает вероятные ответы для проверки и коррекции участниками.', it: 'L\'IA prevede risposte probabili per i partecipanti da rivedere e correggere.' },
  'ai.chatbot': { en: 'AI Survey Chatbot', zh: 'AI问卷聊天机器人', es: 'Chatbot IA para Encuestas', fr: 'Chatbot IA pour Sondages', de: 'KI-Umfrage-Chatbot', ja: 'AIアンケートチャットボット', ko: 'AI 설문 챗봇', pt: 'Chatbot IA para Pesquisas', ar: 'روبوت محادثة ذكي للاستطلاعات', hi: 'AI सर्वेक्षण चैटबॉट', ru: 'ИИ-чатбот для опросов', it: 'Chatbot IA per Sondaggi' },
  'ai.chatbot.desc': { en: 'Participants chat naturally and AI fills in survey answers automatically from the conversation.', zh: '参与者自然聊天，AI从对话中自动填写问卷答案。', es: 'Los participantes chatean naturalmente y la IA completa las respuestas automáticamente.', fr: 'Les participants discutent naturellement et l\'IA remplit automatiquement les réponses.', de: 'Teilnehmer chatten natürlich und KI füllt Antworten automatisch aus dem Gespräch.', ja: '参加者が自然に会話し、AIが会話からアンケートの回答を自動入力します。', ko: '참가자가 자연스럽게 대화하면 AI가 대화에서 자동으로 답변을 채웁니다.', pt: 'Os participantes conversam naturalmente e a IA preenche as respostas automaticamente.', ar: 'يتحدث المشاركون بشكل طبيعي ويملأ الذكاء الاصطناعي الإجابات تلقائياً من المحادثة.', hi: 'प्रतिभागी स्वाभाविक रूप से चैट करते हैं और AI बातचीत से स्वचालित रूप से उत्तर भरता है।', ru: 'Участники общаются естественно, а ИИ автоматически заполняет ответы из разговора.', it: 'I partecipanti chattano naturalmente e l\'IA compila automaticamente le risposte.' },
  'ai.voiceInput': { en: 'Voice Input', zh: '语音输入', es: 'Entrada de Voz', fr: 'Saisie Vocale', de: 'Spracheingabe', ja: '音声入力', ko: '음성 입력', pt: 'Entrada de Voz', ar: 'إدخال صوتي', hi: 'वॉइस इनपुट', ru: 'Голосовой ввод', it: 'Input Vocale' },
  'ai.voiceInput.desc': { en: 'Speak your answers — perfect for accessibility and hands-free completion.', zh: '语音回答——非常适合无障碍访问和免提完成。', es: 'Dicta tus respuestas — perfecto para accesibilidad y uso manos libres.', fr: 'Dictez vos réponses — parfait pour l\'accessibilité et la complétion mains libres.', de: 'Sprechen Sie Ihre Antworten — perfekt für Barrierefreiheit und freihändige Eingabe.', ja: '音声で回答 — アクセシビリティとハンズフリー入力に最適。', ko: '음성으로 답변 — 접근성과 핸즈프리 완료에 완벽합니다.', pt: 'Fale suas respostas — perfeito para acessibilidade e preenchimento mãos livres.', ar: 'انطق إجاباتك — مثالي لإمكانية الوصول والإكمال بدون استخدام اليدين.', hi: 'अपने उत्तर बोलें — पहुंच और हैंड्स-फ्री पूर्णता के लिए बिल्कुल सही।', ru: 'Говорите ответы — идеально для доступности и работы без рук.', it: 'Parla le tue risposte — perfetto per l\'accessibilità e il completamento a mani libere.' },
  'ai.assist': { en: 'AI Assist & Enhance', zh: 'AI辅助与增强', es: 'Asistente IA y Mejora', fr: 'Assistance IA et Amélioration', de: 'KI-Assistenz & Verbesserung', ja: 'AIアシスト＆エンハンス', ko: 'AI 어시스트 & 향상', pt: 'Assistente IA e Melhoria', ar: 'مساعدة وتحسين بالذكاء الاصطناعي', hi: 'AI सहायता और सुधार', ru: 'ИИ-помощь и улучшение', it: 'Assistente IA e Miglioramento' },
  'ai.assist.desc': { en: 'Get contextual help understanding questions and enhance text answers with AI.', zh: '获取理解问题的上下文帮助，并使用AI增强文本答案。', es: 'Obtén ayuda contextual para entender preguntas y mejora respuestas de texto con IA.', fr: 'Obtenez de l\'aide contextuelle pour comprendre les questions et améliorez les réponses textuelles avec l\'IA.', de: 'Erhalten Sie kontextbezogene Hilfe beim Verstehen von Fragen und verbessern Sie Textantworten mit KI.', ja: '質問を理解するためのコンテキストヘルプを取得し、AIでテキスト回答を向上させます。', ko: '질문 이해를 위한 상황별 도움을 받고 AI로 텍스트 답변을 개선하세요.', pt: 'Obtenha ajuda contextual para entender perguntas e melhore respostas de texto com IA.', ar: 'احصل على مساعدة سياقية لفهم الأسئلة وتحسين الإجابات النصية بالذكاء الاصطناعي.', hi: 'प्रश्नों को समझने के लिए संदर्भित सहायता प्राप्त करें और AI के साथ पाठ उत्तरों को बेहतर बनाएं।', ru: 'Получайте контекстную помощь в понимании вопросов и улучшайте текстовые ответы с помощью ИИ.', it: 'Ottieni aiuto contestuale per capire le domande e migliora le risposte testuali con l\'IA.' },

  // Landing page: use cases
  'useCase.academic': { en: 'Academic', zh: '学术', es: 'Académico', fr: 'Académique', de: 'Akademisch', ja: '学術', ko: '학술', pt: 'Acadêmico', ar: 'أكاديمي', hi: 'शैक्षणिक', ru: 'Академический', it: 'Accademico' },
  'useCase.academic.desc': { en: 'Thesis & longitudinal studies', zh: '论文和纵向研究', es: 'Tesis y estudios longitudinales', fr: 'Thèses et études longitudinales', de: 'Abschlussarbeiten und Langzeitstudien', ja: '論文と縦断研究', ko: '논문 및 종단 연구', pt: 'Teses e estudos longitudinais', ar: 'أطروحات ودراسات طولية', hi: 'थीसिस और अनुदैर्ध्य अध्ययन', ru: 'Дипломные и лонгитюдные исследования', it: 'Tesi e studi longitudinali' },
  'useCase.healthcare': { en: 'Healthcare', zh: '医疗', es: 'Salud', fr: 'Santé', de: 'Gesundheitswesen', ja: 'ヘルスケア', ko: '의료', pt: 'Saúde', ar: 'الرعاية الصحية', hi: 'स्वास्थ्य', ru: 'Здравоохранение', it: 'Sanità' },
  'useCase.healthcare.desc': { en: 'Patient outcomes & clinical', zh: '患者结果和临床研究', es: 'Resultados de pacientes y clínicos', fr: 'Résultats patients et cliniques', de: 'Patientenergebnisse und Klinisches', ja: '患者アウトカムと臨床', ko: '환자 결과 및 임상', pt: 'Resultados de pacientes e clínicos', ar: 'نتائج المرضى والسريرية', hi: 'रोगी परिणाम और नैदानिक', ru: 'Результаты пациентов и клинические', it: 'Esiti clinici e dei pazienti' },
  'useCase.uxResearch': { en: 'UX Research', zh: '用户体验研究', es: 'Investigación UX', fr: 'Recherche UX', de: 'UX-Forschung', ja: 'UXリサーチ', ko: 'UX 연구', pt: 'Pesquisa UX', ar: 'بحث تجربة المستخدم', hi: 'UX रिसर्च', ru: 'UX-исследования', it: 'Ricerca UX' },
  'useCase.uxResearch.desc': { en: 'Usability & user feedback', zh: '可用性和用户反馈', es: 'Usabilidad y retroalimentación', fr: 'Utilisabilité et retours utilisateurs', de: 'Usability und Nutzerfeedback', ja: 'ユーザビリティとフィードバック', ko: '사용성 및 사용자 피드백', pt: 'Usabilidade e feedback do usuário', ar: 'سهولة الاستخدام وملاحظات المستخدمين', hi: 'उपयोगिता और उपयोगकर्ता प्रतिक्रिया', ru: 'Юзабилити и отзывы', it: 'Usabilità e feedback utenti' },
  'useCase.marketResearch': { en: 'Market Research', zh: '市场调研', es: 'Investigación de Mercado', fr: 'Études de Marché', de: 'Marktforschung', ja: '市場調査', ko: '시장 조사', pt: 'Pesquisa de Mercado', ar: 'أبحاث السوق', hi: 'बाज़ार अनुसंधान', ru: 'Маркетинговые исследования', it: 'Ricerca di Mercato' },
  'useCase.marketResearch.desc': { en: 'Consumer insights & trends', zh: '消费者洞察和趋势', es: 'Insights del consumidor y tendencias', fr: 'Insights consommateurs et tendances', de: 'Verbrauchereinblicke und Trends', ja: '消費者インサイトとトレンド', ko: '소비자 인사이트 및 트렌드', pt: 'Insights do consumidor e tendências', ar: 'رؤى المستهلكين والاتجاهات', hi: 'उपभोक्ता अंतर्दृष्टि और रुझान', ru: 'Потребительские инсайты и тренды', it: 'Insight dei consumatori e tendenze' },
  'useCase.hr': { en: 'HR & Employee', zh: '人力资源', es: 'RRHH y Empleados', fr: 'RH et Employés', de: 'HR & Mitarbeiter', ja: 'HR＆従業員', ko: 'HR 및 직원', pt: 'RH e Funcionários', ar: 'الموارد البشرية والموظفون', hi: 'एचआर और कर्मचारी', ru: 'HR и сотрудники', it: 'HR e Dipendenti' },
  'useCase.hr.desc': { en: 'Engagement & satisfaction', zh: '参与度和满意度', es: 'Compromiso y satisfacción', fr: 'Engagement et satisfaction', de: 'Engagement und Zufriedenheit', ja: 'エンゲージメントと満足度', ko: '참여도 및 만족도', pt: 'Engajamento e satisfação', ar: 'المشاركة والرضا', hi: 'सहभागिता और संतुष्टि', ru: 'Вовлечённость и удовлетворённость', it: 'Engagement e soddisfazione' },
  'useCase.psychology': { en: 'Psychology', zh: '心理学', es: 'Psicología', fr: 'Psychologie', de: 'Psychologie', ja: '心理学', ko: '심리학', pt: 'Psicologia', ar: 'علم النفس', hi: 'मनोविज्ञान', ru: 'Психология', it: 'Psicologia' },
  'useCase.psychology.desc': { en: 'Behavioral & cognitive studies', zh: '行为和认知研究', es: 'Estudios conductuales y cognitivos', fr: 'Études comportementales et cognitives', de: 'Verhaltens- und Kognitionsstudien', ja: '行動・認知研究', ko: '행동 및 인지 연구', pt: 'Estudos comportamentais e cognitivos', ar: 'دراسات سلوكية ومعرفية', hi: 'व्यवहारिक और संज्ञानात्मक अध्ययन', ru: 'Поведенческие и когнитивные исследования', it: 'Studi comportamentali e cognitivi' },

  // Steps
  'step.design': { en: 'Design', zh: '设计', es: 'Diseñar', fr: 'Concevoir', de: 'Entwerfen', ja: 'デザイン', ko: '디자인', pt: 'Projetar', ar: 'تصميم', hi: 'डिज़ाइन', ru: 'Дизайн', it: 'Progetta' },
  'step.design.desc': { en: 'Build your survey with our intuitive drag-and-drop builder — or let AI do it.', zh: '使用直观的拖放构建器创建问卷——或让AI来做。', es: 'Construye tu encuesta con nuestro constructor intuitivo — o deja que la IA lo haga.', fr: 'Construisez votre sondage avec notre constructeur intuitif — ou laissez l\'IA le faire.', de: 'Erstellen Sie Ihre Umfrage mit unserem Drag-and-Drop-Builder — oder lassen Sie KI es tun.', ja: '直感的なビルダーでアンケートを作成 — またはAIにおまかせ。', ko: '직관적인 빌더로 설문조사를 만들거나 AI에게 맡기세요.', pt: 'Crie sua pesquisa com nosso construtor intuitivo — ou deixe a IA fazer.', ar: 'ابنِ استطلاعك باستخدام منشئنا البديهي — أو دع الذكاء الاصطناعي يفعل ذلك.', hi: 'हमारे सहज बिल्डर से सर्वेक्षण बनाएं — या AI को करने दें।', ru: 'Создайте опрос с помощью нашего конструктора — или пусть ИИ сделает это.', it: 'Crea il sondaggio con il nostro builder intuitivo — o lascia fare all\'IA.' },
  'step.distribute': { en: 'Distribute', zh: '分发', es: 'Distribuir', fr: 'Distribuer', de: 'Verteilen', ja: '配布', ko: '배포', pt: 'Distribuir', ar: 'توزيع', hi: 'वितरित करें', ru: 'Распространение', it: 'Distribuisci' },
  'step.distribute.desc': { en: 'Share via link or survey code. Works on any device.', zh: '通过链接或调查码分享，适用于任何设备。', es: 'Comparte por enlace o código. Funciona en cualquier dispositivo.', fr: 'Partagez par lien ou code. Fonctionne sur tout appareil.', de: 'Teilen per Link oder Code. Funktioniert auf jedem Gerät.', ja: 'リンクまたはコードで共有。どのデバイスでも。', ko: '링크 또는 코드로 공유. 모든 기기에서 작동.', pt: 'Compartilhe por link ou código. Funciona em qualquer dispositivo.', ar: 'شارك عبر رابط أو رمز. يعمل على أي جهاز.', hi: 'लिंक या कोड से साझा करें। किसी भी डिवाइस पर काम करता है।', ru: 'Поделитесь ссылкой или кодом. Работает на любом устройстве.', it: 'Condividi tramite link o codice. Funziona su qualsiasi dispositivo.' },
  'step.analyze': { en: 'Analyze', zh: '分析', es: 'Analizar', fr: 'Analyser', de: 'Analysieren', ja: '分析', ko: '분석', pt: 'Analisar', ar: 'تحليل', hi: 'विश्लेषण', ru: 'Анализ', it: 'Analizza' },
  'step.analyze.desc': { en: 'View real-time analytics and export your data.', zh: '查看实时分析并导出数据。', es: 'Ve analíticas en tiempo real y exporta tus datos.', fr: 'Consultez les analyses en temps réel et exportez vos données.', de: 'Sehen Sie Echtzeit-Analysen und exportieren Sie Ihre Daten.', ja: 'リアルタイム分析を確認し、データをエクスポート。', ko: '실시간 분석을 보고 데이터를 내보내세요.', pt: 'Veja análises em tempo real e exporte seus dados.', ar: 'اعرض التحليلات في الوقت الفعلي وصدّر بياناتك.', hi: 'रीयल-टाइम एनालिटिक्स देखें और डेटा निर्यात करें।', ru: 'Смотрите аналитику в реальном времени и экспортируйте данные.', it: 'Visualizza analisi in tempo reale ed esporta i tuoi dati.' },

  // Trusted by categories
  'trusted.universities': { en: 'Universities', zh: '高校', es: 'Universidades', fr: 'Universités', de: 'Universitäten', ja: '大学', ko: '대학교', pt: 'Universidades', ar: 'الجامعات', hi: 'विश्वविद्यालय', ru: 'Университеты', it: 'Università' },
  'trusted.healthcare': { en: 'Healthcare', zh: '医疗', es: 'Salud', fr: 'Santé', de: 'Gesundheitswesen', ja: 'ヘルスケア', ko: '의료', pt: 'Saúde', ar: 'الرعاية الصحية', hi: 'स्वास्थ्य', ru: 'Здравоохранение', it: 'Sanità' },
  'trusted.uxTeams': { en: 'UX Teams', zh: 'UX团队', es: 'Equipos UX', fr: 'Équipes UX', de: 'UX-Teams', ja: 'UXチーム', ko: 'UX 팀', pt: 'Equipes UX', ar: 'فرق UX', hi: 'UX टीम', ru: 'UX-команды', it: 'Team UX' },
  'trusted.marketResearch': { en: 'Market Research', zh: '市场调研', es: 'Investigación de Mercado', fr: 'Études de Marché', de: 'Marktforschung', ja: '市場調査', ko: '시장 조사', pt: 'Pesquisa de Mercado', ar: 'أبحاث السوق', hi: 'बाज़ार अनुसंधान', ru: 'Маркетинговые исследования', it: 'Ricerca di Mercato' },
  'trusted.hr': { en: 'HR', zh: '人力资源', es: 'RRHH', fr: 'RH', de: 'HR', ja: 'HR', ko: 'HR', pt: 'RH', ar: 'الموارد البشرية', hi: 'एचआर', ru: 'HR', it: 'HR' },
  'trusted.startups': { en: 'Startups', zh: '初创企业', es: 'Startups', fr: 'Startups', de: 'Startups', ja: 'スタートアップ', ko: '스타트업', pt: 'Startups', ar: 'الشركات الناشئة', hi: 'स्टार्टअप', ru: 'Стартапы', it: 'Startup' },

  // Participant Library
  'participantLibrary.title': { en: 'Participant Library', zh: '参与者库', es: 'Biblioteca de Participantes', fr: 'Bibliothèque de Participants', de: 'Teilnehmerbibliothek', ja: '参加者ライブラリ', ko: '참여자 라이브러리', pt: 'Biblioteca de Participantes', ar: 'مكتبة المشاركين', hi: 'प्रतिभागी पुस्तकालय', ru: 'Библиотека участников', it: 'Libreria Partecipanti' },
  'participantLibrary.subtitle': { en: 'Find participants for your research or get discovered by researchers.', zh: '为您的研究寻找参与者，或被研究人员发现。', es: 'Encuentra participantes para tu investigación o deja que los investigadores te descubran.', fr: 'Trouvez des participants pour votre recherche ou faites-vous découvrir par des chercheurs.', de: 'Finden Sie Teilnehmer für Ihre Forschung oder lassen Sie sich von Forschern entdecken.', ja: '研究の参加者を探すか、研究者に発見してもらいましょう。', ko: '연구를 위한 참여자를 찾거나 연구자에게 발견되세요.', pt: 'Encontre participantes para sua pesquisa ou seja descoberto por pesquisadores.', ar: 'ابحث عن مشاركين لبحثك أو اجعل الباحثين يكتشفونك.', hi: 'अपने शोध के लिए प्रतिभागी खोजें या शोधकर्ताओं द्वारा खोजे जाएं।', ru: 'Найдите участников для исследования или будьте найдены исследователями.', it: 'Trova partecipanti per la tua ricerca o fatti scoprire dai ricercatori.' },
  'participantLibrary.joinToggle': { en: 'Join Participant Library', zh: '加入参与者库', es: 'Unirse a la Biblioteca', fr: 'Rejoindre la Bibliothèque', de: 'Teilnehmerbibliothek beitreten', ja: '参加者ライブラリに参加', ko: '참여자 라이브러리 참여', pt: 'Entrar na Biblioteca', ar: 'الانضمام إلى مكتبة المشاركين', hi: 'प्रतिभागी पुस्तकालय में शामिल हों', ru: 'Присоединиться к библиотеке', it: 'Unisciti alla Libreria' },
  'participantLibrary.joinDesc': { en: 'Make your profile visible to researchers looking for participants.', zh: '让研究人员可以找到您的个人资料。', es: 'Haz tu perfil visible para investigadores que buscan participantes.', fr: 'Rendez votre profil visible aux chercheurs qui cherchent des participants.', de: 'Machen Sie Ihr Profil für Forscher sichtbar.', ja: '参加者を探している研究者にプロフィールを公開します。', ko: '참여자를 찾는 연구자에게 프로필을 공개하세요.', pt: 'Torne seu perfil visível para pesquisadores procurando participantes.', ar: 'اجعل ملفك الشخصي مرئيًا للباحثين الذين يبحثون عن مشاركين.', hi: 'प्रतिभागियों की तलाश कर रहे शोधकर्ताओं को अपनी प्रोफ़ाइल दिखाएं।', ru: 'Сделайте свой профиль видимым для исследователей.', it: 'Rendi il tuo profilo visibile ai ricercatori.' },
  'participantLibrary.country': { en: 'Country', zh: '国家', es: 'País', fr: 'Pays', de: 'Land', ja: '国', ko: '국가', pt: 'País', ar: 'البلد', hi: 'देश', ru: 'Страна', it: 'Paese' },
  'participantLibrary.region': { en: 'Region', zh: '地区', es: 'Región', fr: 'Région', de: 'Region', ja: '地域', ko: '지역', pt: 'Região', ar: 'المنطقة', hi: 'क्षेत्र', ru: 'Регион', it: 'Regione' },
  'participantLibrary.age': { en: 'Age', zh: '年龄', es: 'Edad', fr: 'Âge', de: 'Alter', ja: '年齢', ko: '나이', pt: 'Idade', ar: 'العمر', hi: 'उम्र', ru: 'Возраст', it: 'Età' },
  'participantLibrary.occupation': { en: 'Occupation', zh: '职业', es: 'Ocupación', fr: 'Profession', de: 'Beruf', ja: '職業', ko: '직업', pt: 'Profissão', ar: 'المهنة', hi: 'पेशा', ru: 'Профессия', it: 'Professione' },
  'participantLibrary.allCountries': { en: 'All Countries', zh: '所有国家', es: 'Todos los países', fr: 'Tous les pays', de: 'Alle Länder', ja: 'すべての国', ko: '모든 국가', pt: 'Todos os países', ar: 'جميع البلدان', hi: 'सभी देश', ru: 'Все страны', it: 'Tutti i paesi' },
  'participantLibrary.allRegions': { en: 'All Regions', zh: '所有地区', es: 'Todas las regiones', fr: 'Toutes les régions', de: 'Alle Regionen', ja: 'すべての地域', ko: '모든 지역', pt: 'Todas as regiões', ar: 'جميع المناطق', hi: 'सभी क्षेत्र', ru: 'Все регионы', it: 'Tutte le regioni' },
  'participantLibrary.noResults': { en: 'No participants found matching your criteria.', zh: '没有找到符合条件的参与者。', es: 'No se encontraron participantes que coincidan con tus criterios.', fr: 'Aucun participant trouvé correspondant à vos critères.', de: 'Keine Teilnehmer gefunden, die Ihren Kriterien entsprechen.', ja: '条件に一致する参加者が見つかりませんでした。', ko: '기준에 맞는 참여자가 없습니다.', pt: 'Nenhum participante encontrado com seus critérios.', ar: 'لم يتم العثور على مشاركين يطابقون معاييرك.', hi: 'आपके मानदंडों से मेल खाने वाले कोई प्रतिभागी नहीं मिले।', ru: 'Участники по вашим критериям не найдены.', it: 'Nessun partecipante trovato con i tuoi criteri.' },
  'participantLibrary.inviteToStudy': { en: 'Invite to Study', zh: '邀请参加研究', es: 'Invitar al estudio', fr: 'Inviter à l\'étude', de: 'Zur Studie einladen', ja: '研究に招待', ko: '연구에 초대', pt: 'Convidar para estudo', ar: 'دعوة للدراسة', hi: 'अध्ययन में आमंत्रित करें', ru: 'Пригласить в исследование', it: 'Invita allo studio' },
  'participantLibrary.viewProfile': { en: 'View Profile', zh: '查看资料', es: 'Ver perfil', fr: 'Voir le profil', de: 'Profil ansehen', ja: 'プロフィールを見る', ko: '프로필 보기', pt: 'Ver perfil', ar: 'عرض الملف الشخصي', hi: 'प्रोफ़ाइल देखें', ru: 'Посмотреть профиль', it: 'Vedi profilo' },
  'participantLibrary.updateProfile': { en: 'Update your profile to be discovered', zh: '更新您的资料以被发现', es: 'Actualiza tu perfil para ser descubierto', fr: 'Mettez à jour votre profil pour être découvert', de: 'Aktualisieren Sie Ihr Profil', ja: 'プロフィールを更新して発見されましょう', ko: '프로필을 업데이트하여 발견되세요', pt: 'Atualize seu perfil para ser descoberto', ar: 'حدّث ملفك الشخصي ليتم اكتشافك', hi: 'खोजे जाने के लिए अपना प्रोफ़ाइल अपडेट करें', ru: 'Обновите профиль, чтобы вас нашли', it: 'Aggiorna il profilo per essere scoperto' },

  // Dashboard tabs
  'dashboard.allStudies': { en: 'All Studies', zh: '所有研究', es: 'Todos los Estudios', fr: 'Toutes les Études', de: 'Alle Studien', ja: 'すべての研究', ko: '모든 연구', pt: 'Todos os Estudos', ar: 'جميع الدراسات', hi: 'सभी अध्ययन', ru: 'Все исследования', it: 'Tutti gli studi' },
  'dashboard.myDrafts': { en: 'My Drafts', zh: '我的草稿', es: 'Mis Borradores', fr: 'Mes Brouillons', de: 'Meine Entwürfe', ja: 'マイ下書き', ko: '내 초안', pt: 'Meus Rascunhos', ar: 'مسوداتي', hi: 'मेरे ड्राफ्ट', ru: 'Мои черновики', it: 'Le mie bozze' },
  'dashboard.myPublishedStudies': { en: 'My Published Studies', zh: '我发布的研究', es: 'Mis Estudios Publicados', fr: 'Mes Études Publiées', de: 'Meine Veröffentlichten', ja: '公開済みの研究', ko: '내 게시된 연구', pt: 'Meus Estudos Publicados', ar: 'دراساتي المنشورة', hi: 'मेरे प्रकाशित अध्ययन', ru: 'Мои опубликованные', it: 'I miei studi pubblicati' },
  'dashboard.myJoinedStudies': { en: 'My Joined Studies', zh: '我参与的研究', es: 'Mis Estudios Unidos', fr: 'Mes Études Rejointes', de: 'Beigetretene Studien', ja: '参加した研究', ko: '참여한 연구', pt: 'Estudos Participados', ar: 'الدراسات التي انضممت إليها', hi: 'मेरे शामिल अध्ययन', ru: 'Мои присоединённые', it: 'Studi a cui partecipo' },
  'dashboard.studies': { en: 'studies', zh: '项研究', es: 'estudios', fr: 'études', de: 'Studien', ja: '研究', ko: '연구', pt: 'estudos', ar: 'دراسات', hi: 'अध्ययन', ru: 'исследований', it: 'studi' },
  'dashboard.study': { en: 'study', zh: '项研究', es: 'estudio', fr: 'étude', de: 'Studie', ja: '研究', ko: '연구', pt: 'estudo', ar: 'دراسة', hi: 'अध्ययन', ru: 'исследование', it: 'studio' },
  'dashboard.newStudy': { en: '+ New Study', zh: '+ 新研究', es: '+ Nuevo Estudio', fr: '+ Nouvelle Étude', de: '+ Neue Studie', ja: '+ 新しい研究', ko: '+ 새 연구', pt: '+ Novo Estudo', ar: '+ دراسة جديدة', hi: '+ नया अध्ययन', ru: '+ Новое исследование', it: '+ Nuovo studio' },
  'dashboard.edit': { en: 'Edit', zh: '编辑', es: 'Editar', fr: 'Modifier', de: 'Bearbeiten', ja: '編集', ko: '편집', pt: 'Editar', ar: 'تعديل', hi: 'संपादन', ru: 'Редактировать', it: 'Modifica' },
  'dashboard.owner': { en: 'Owner', zh: '负责人', es: 'Propietario', fr: 'Propriétaire', de: 'Eigentümer', ja: 'オーナー', ko: '소유자', pt: 'Proprietário', ar: 'المالك', hi: 'मालिक', ru: 'Владелец', it: 'Proprietario' },
  'dashboard.participant': { en: 'Participant', zh: '参与者', es: 'Participante', fr: 'Participant', de: 'Teilnehmer', ja: '参加者', ko: '참여자', pt: 'Participante', ar: 'مشارك', hi: 'प्रतिभागी', ru: 'Участник', it: 'Partecipante' },
  'dashboard.signInToStart': { en: 'Sign in to get started', zh: '登录以开始', es: 'Inicia sesión para comenzar', fr: 'Connectez-vous pour commencer', de: 'Melden Sie sich an', ja: 'ログインして始めましょう', ko: '로그인하여 시작하세요', pt: 'Entre para começar', ar: 'سجّل الدخول للبدء', hi: 'शुरू करने के लिए साइन इन करें', ru: 'Войдите, чтобы начать', it: 'Accedi per iniziare' },
  'dashboard.createOrJoin': { en: 'Create or join research studies', zh: '创建或参与研究', es: 'Crea o únete a estudios', fr: 'Créez ou rejoignez des études', de: 'Erstellen oder beitreten', ja: '研究の作成または参加', ko: '연구를 만들거나 참여하세요', pt: 'Crie ou participe de estudos', ar: 'أنشئ أو انضم إلى دراسات', hi: 'अध्ययन बनाएं या शामिल हों', ru: 'Создайте или присоединитесь к исследованиям', it: 'Crea o partecipa a studi' },
  'dashboard.noDescription': { en: 'No description', zh: '暂无描述', es: 'Sin descripción', fr: 'Aucune description', de: 'Keine Beschreibung', ja: '説明なし', ko: '설명 없음', pt: 'Sem descrição', ar: 'بدون وصف', hi: 'कोई विवरण नहीं', ru: 'Без описания', it: 'Nessuna descrizione' },

  // Responses tab
  'responses.title': { en: 'Responses', zh: '回复', es: 'Respuestas', fr: 'Réponses', de: 'Antworten', ja: '回答', ko: '응답', pt: 'Respostas', ar: 'الردود', hi: 'प्रतिक्रियाएँ', ru: 'Ответы', it: 'Risposte' },
  'responses.totalResponses': { en: 'TOTAL RESPONSES', zh: '总回复数', es: 'RESPUESTAS TOTALES', fr: 'RÉPONSES TOTALES', de: 'ANTWORTEN GESAMT', ja: '回答総数', ko: '총 응답', pt: 'RESPOSTAS TOTAIS', ar: 'إجمالي الردود', hi: 'कुल प्रतिक्रियाएँ', ru: 'ВСЕГО ОТВЕТОВ', it: 'RISPOSTE TOTALI' },
  'responses.participants': { en: 'PARTICIPANTS', zh: '参与者', es: 'PARTICIPANTES', fr: 'PARTICIPANTS', de: 'TEILNEHMER', ja: '参加者', ko: '참여자', pt: 'PARTICIPANTES', ar: 'المشاركون', hi: 'प्रतिभागी', ru: 'УЧАСТНИКИ', it: 'PARTECIPANTI' },
  'responses.completed': { en: 'COMPLETED', zh: '已完成', es: 'COMPLETADAS', fr: 'COMPLÉTÉES', de: 'ABGESCHLOSSEN', ja: '完了', ko: '완료', pt: 'CONCLUÍDAS', ar: 'مكتملة', hi: 'पूर्ण', ru: 'ЗАВЕРШЕНО', it: 'COMPLETATE' },
  'responses.completionRate': { en: 'COMPLETION RATE', zh: '完成率', es: 'TASA DE FINALIZACIÓN', fr: 'TAUX DE COMPLÉTION', de: 'ABSCHLUSSRATE', ja: '完了率', ko: '완료율', pt: 'TAXA DE CONCLUSÃO', ar: 'معدل الإكمال', hi: 'पूर्णता दर', ru: 'ПРОЦЕНТ ЗАВЕРШЕНИЯ', it: 'TASSO DI COMPLETAMENTO' },
  'responses.summary': { en: 'Summary', zh: '摘要', es: 'Resumen', fr: 'Résumé', de: 'Zusammenfassung', ja: 'サマリー', ko: '요약', pt: 'Resumo', ar: 'ملخص', hi: 'सारांश', ru: 'Сводка', it: 'Riepilogo' },
  'responses.individual': { en: 'Individual', zh: '个人', es: 'Individual', fr: 'Individuel', de: 'Einzeln', ja: '個別', ko: '개인', pt: 'Individual', ar: 'فردي', hi: 'व्यक्तिगत', ru: 'Индивидуальный', it: 'Individuale' },
  'responses.table': { en: 'Table', zh: '表格', es: 'Tabla', fr: 'Tableau', de: 'Tabelle', ja: 'テーブル', ko: '표', pt: 'Tabela', ar: 'جدول', hi: 'तालिका', ru: 'Таблица', it: 'Tabella' },
  'responses.export': { en: 'Export', zh: '导出', es: 'Exportar', fr: 'Exporter', de: 'Exportieren', ja: 'エクスポート', ko: '내보내기', pt: 'Exportar', ar: 'تصدير', hi: 'निर्यात', ru: 'Экспорт', it: 'Esporta' },
  'responses.allQuestionnaires': { en: 'All Questionnaires', zh: '所有问卷', es: 'Todos los Cuestionarios', fr: 'Tous les Questionnaires', de: 'Alle Fragebögen', ja: 'すべてのアンケート', ko: '모든 설문지', pt: 'Todos os Questionários', ar: 'جميع الاستبيانات', hi: 'सभी प्रश्नावली', ru: 'Все анкеты', it: 'Tutti i questionari' },
  'responses.noResponses': { en: 'No responses yet', zh: '暂无回复', es: 'Sin respuestas aún', fr: 'Pas encore de réponses', de: 'Noch keine Antworten', ja: 'まだ回答がありません', ko: '아직 응답 없음', pt: 'Sem respostas ainda', ar: 'لا توجد ردود بعد', hi: 'अभी कोई प्रतिक्रिया नहीं', ru: 'Пока нет ответов', it: 'Nessuna risposta ancora' },
  'responses.noResponsesDesc': { en: 'Responses will appear here as participants complete your questionnaires.', zh: '参与者完成问卷后，回复将显示在此处。', es: 'Las respuestas aparecerán aquí cuando los participantes completen tus cuestionarios.', fr: 'Les réponses apparaîtront ici lorsque les participants complèteront vos questionnaires.', de: 'Antworten erscheinen hier, sobald Teilnehmer Ihre Fragebögen ausfüllen.', ja: '参加者がアンケートを完了すると、ここに回答が表示されます。', ko: '참가자가 설문지를 완료하면 여기에 응답이 표시됩니다.', pt: 'As respostas aparecerão aqui conforme os participantes completarem seus questionários.', ar: 'ستظهر الردود هنا عندما يكمل المشاركون استبياناتك.', hi: 'प्रतिभागियों द्वारा प्रश्नावली पूर्ण करने पर प्रतिक्रियाएँ यहाँ दिखाई देंगी।', ru: 'Ответы появятся здесь, когда участники заполнят ваши анкеты.', it: 'Le risposte appariranno qui quando i partecipanti completeranno i tuoi questionari.' },
  'responses.responses': { en: 'responses', zh: '条回复', es: 'respuestas', fr: 'réponses', de: 'Antworten', ja: '回答', ko: '응답', pt: 'respostas', ar: 'ردود', hi: 'प्रतिक्रियाएँ', ru: 'ответов', it: 'risposte' },
  'responses.answers': { en: 'answers', zh: '个回答', es: 'respuestas', fr: 'réponses', de: 'Antworten', ja: '回答', ko: '답변', pt: 'respostas', ar: 'إجابات', hi: 'उत्तर', ru: 'ответов', it: 'risposte' },
  'responses.average': { en: 'Average', zh: '平均值', es: 'Promedio', fr: 'Moyenne', de: 'Durchschnitt', ja: '平均', ko: '평균', pt: 'Média', ar: 'المتوسط', hi: 'औसत', ru: 'Среднее', it: 'Media' },
  'responses.minimum': { en: 'Minimum', zh: '最小值', es: 'Mínimo', fr: 'Minimum', de: 'Minimum', ja: '最小', ko: '최소', pt: 'Mínimo', ar: 'الحد الأدنى', hi: 'न्यूनतम', ru: 'Минимум', it: 'Minimo' },
  'responses.maximum': { en: 'Maximum', zh: '最大值', es: 'Máximo', fr: 'Maximum', de: 'Maximum', ja: '最大', ko: '최대', pt: 'Máximo', ar: 'الحد الأقصى', hi: 'अधिकतम', ru: 'Максимум', it: 'Massimo' },
  'responses.selectParticipant': { en: 'Select a participant', zh: '选择参与者', es: 'Seleccionar participante', fr: 'Sélectionner un participant', de: 'Teilnehmer auswählen', ja: '参加者を選択', ko: '참여자 선택', pt: 'Selecionar participante', ar: 'اختر مشاركاً', hi: 'प्रतिभागी चुनें', ru: 'Выберите участника', it: 'Seleziona partecipante' },

  // Project builder tabs
  'project.settings': { en: 'Settings', zh: '设置', es: 'Configuración', fr: 'Paramètres', de: 'Einstellungen', ja: '設定', ko: '설정', pt: 'Configurações', ar: 'الإعدادات', hi: 'सेटिंग्स', ru: 'Настройки', it: 'Impostazioni' },
  'project.questionnaires': { en: 'Questionnaires', zh: '问卷', es: 'Cuestionarios', fr: 'Questionnaires', de: 'Fragebögen', ja: 'アンケート', ko: '설문지', pt: 'Questionários', ar: 'الاستبيانات', hi: 'प्रश्नावली', ru: 'Анкеты', it: 'Questionari' },
  'project.components': { en: 'Forms & Components', zh: '表单与组件', es: 'Formularios y Componentes', fr: 'Formulaires et Composants', de: 'Formulare & Komponenten', ja: 'フォーム＆コンポーネント', ko: '양식 및 구성 요소', pt: 'Formulários e Componentes', ar: 'النماذج والمكونات', hi: 'फॉर्म और घटक', ru: 'Формы и компоненты', it: 'Moduli e Componenti' },
  'project.flow': { en: 'Flow', zh: '流程', es: 'Flujo', fr: 'Flux', de: 'Ablauf', ja: 'フロー', ko: '흐름', pt: 'Fluxo', ar: 'التدفق', hi: 'प्रवाह', ru: 'Поток', it: 'Flusso' },
  'project.translations': { en: 'Translation', zh: '翻译', es: 'Traducción', fr: 'Traduction', de: 'Übersetzung', ja: '翻訳', ko: '번역', pt: 'Tradução', ar: 'الترجمة', hi: 'अनुवाद', ru: 'Перевод', it: 'Traduzione' },
  'project.logic': { en: 'Logic', zh: '逻辑', es: 'Lógica', fr: 'Logique', de: 'Logik', ja: 'ロジック', ko: '로직', pt: 'Lógica', ar: 'المنطق', hi: 'लॉजिक', ru: 'Логика', it: 'Logica' },
  'project.notifications': { en: 'Notifications', zh: '通知', es: 'Notificaciones', fr: 'Notifications', de: 'Benachrichtigungen', ja: '通知', ko: '알림', pt: 'Notificações', ar: 'الإشعارات', hi: 'सूचनाएं', ru: 'Уведомления', it: 'Notifiche' },
  'project.layout': { en: 'Layout', zh: '布局', es: 'Diseño', fr: 'Mise en page', de: 'Layout', ja: 'レイアウト', ko: '레이아웃', pt: 'Layout', ar: 'التخطيط', hi: 'लेआउट', ru: 'Макет', it: 'Layout' },
  'project.preview': { en: 'Preview', zh: '预览', es: 'Vista previa', fr: 'Aperçu', de: 'Vorschau', ja: 'プレビュー', ko: '미리보기', pt: 'Visualizar', ar: 'معاينة', hi: 'पूर्वावलोकन', ru: 'Предпросмотр', it: 'Anteprima' },
  'project.unpublish': { en: 'Unpublish', zh: '取消发布', es: 'Despublicar', fr: 'Dépublier', de: 'Veröffentlichung aufheben', ja: '非公開にする', ko: '게시 취소', pt: 'Despublicar', ar: 'إلغاء النشر', hi: 'अप्रकाशित करें', ru: 'Снять с публикации', it: 'Annulla pubblicazione' },
  'project.publish': { en: 'Publish', zh: '发布', es: 'Publicar', fr: 'Publier', de: 'Veröffentlichen', ja: '公開する', ko: '게시', pt: 'Publicar', ar: 'نشر', hi: 'प्रकाशित करें', ru: 'Опубликовать', it: 'Pubblica' },
  'project.participants': { en: 'Participants', zh: '参与者', es: 'Participantes', fr: 'Participants', de: 'Teilnehmer', ja: '参加者', ko: '참여자', pt: 'Participantes', ar: 'المشاركون', hi: 'प्रतिभागी', ru: 'Участники', it: 'Partecipanti' },
  'project.findParticipants': { en: 'Find Participants', zh: '寻找参与者', es: 'Buscar Participantes', fr: 'Trouver des Participants', de: 'Teilnehmer finden', ja: '参加者を探す', ko: '참여자 찾기', pt: 'Encontrar Participantes', ar: 'البحث عن مشاركين', hi: 'प्रतिभागी खोजें', ru: 'Найти участников', it: 'Trova Partecipanti' },
  'project.findParticipantsDesc': { en: 'Browse the participant library and invite people to your study.', zh: '浏览参与者库并邀请人员参加您的研究。', es: 'Explore la biblioteca y invite personas a su estudio.', fr: 'Parcourez la bibliothèque et invitez des personnes.', de: 'Durchsuchen Sie die Bibliothek und laden Sie Personen ein.', ja: 'ライブラリを閲覧し、研究に招待しましょう。', ko: '라이브러리를 탐색하고 연구에 초대하세요.', pt: 'Navegue pela biblioteca e convide pessoas.', ar: 'تصفح المكتبة وادعُ أشخاصاً.', hi: 'लाइब्रेरी ब्राउज़ करें और लोगों को आमंत्रित करें।', ru: 'Просмотрите библиотеку и пригласите участников.', it: 'Sfoglia la libreria e invita persone.' },
  'project.inviteParticipant': { en: 'Invite Participant', zh: '邀请参与者', es: 'Invitar Participante', fr: 'Inviter un Participant', de: 'Teilnehmer einladen', ja: '参加者を招待', ko: '참여자 초대', pt: 'Convidar Participante', ar: 'دعوة مشارك', hi: 'प्रतिभागी आमंत्रित करें', ru: 'Пригласить участника', it: 'Invita Partecipante' },
  'project.totalParticipants': { en: 'Total', zh: '总计', es: 'Total', fr: 'Total', de: 'Gesamt', ja: '合計', ko: '합계', pt: 'Total', ar: 'الإجمالي', hi: 'कुल', ru: 'Всего', it: 'Totale' },
  'project.invited': { en: 'Invited', zh: '已邀请', es: 'Invitados', fr: 'Invités', de: 'Eingeladen', ja: '招待済み', ko: '초대됨', pt: 'Convidados', ar: 'مدعوون', hi: 'आमंत्रित', ru: 'Приглашено', it: 'Invitati' },
  'project.active': { en: 'Active', zh: '活跃', es: 'Activos', fr: 'Actifs', de: 'Aktiv', ja: 'アクティブ', ko: '활성', pt: 'Ativos', ar: 'نشط', hi: 'सक्रिय', ru: 'Активных', it: 'Attivi' },
  'project.enrolled': { en: 'Enrolled', zh: '已登记', es: 'Inscrito', fr: 'Inscrit', de: 'Eingeschrieben', ja: '登録済み', ko: '등록됨', pt: 'Inscrito', ar: 'مسجل', hi: 'नामांकित', ru: 'Зарегистрирован', it: 'Iscritto' },
  'project.noParticipants': { en: 'No Participants Yet', zh: '暂无参与者', es: 'Aún no hay participantes', fr: 'Pas encore de participants', de: 'Noch keine Teilnehmer', ja: 'まだ参加者がいません', ko: '아직 참여자가 없습니다', pt: 'Nenhum participante ainda', ar: 'لا يوجد مشاركون بعد', hi: 'अभी कोई प्रतिभागी नहीं', ru: 'Пока нет участников', it: 'Nessun partecipante ancora' },
  'project.noParticipantsDesc': { en: 'Invite participants or find them in the participant library.', zh: '邀请参与者或在参与者库中查找。', es: 'Invite participantes o búsquelos en la biblioteca.', fr: 'Invitez des participants ou trouvez-les dans la bibliothèque.', de: 'Laden Sie Teilnehmer ein oder finden Sie sie in der Bibliothek.', ja: '参加者を招待するか、ライブラリから探しましょう。', ko: '참여자를 초대하거나 라이브러리에서 찾으세요.', pt: 'Convide participantes ou encontre-os na biblioteca.', ar: 'ادعُ مشاركين أو ابحث عنهم في المكتبة.', hi: 'प्रतिभागियों को आमंत्रित करें या लाइब्रेरी में खोजें।', ru: 'Пригласите участников или найдите их в библиотеке.', it: 'Invita partecipanti o trovali nella libreria.' },
  'project.addFromTemplates': { en: 'Add from Templates', zh: '从模板添加', es: 'Añadir desde Plantillas', fr: 'Ajouter depuis les Modèles', de: 'Aus Vorlagen hinzufügen', ja: 'テンプレートから追加', ko: '템플릿에서 추가', pt: 'Adicionar de Modelos', ar: 'إضافة من القوالب', hi: 'टेम्पलेट से जोड़ें', ru: 'Добавить из шаблонов', it: 'Aggiungi da Modelli' },
  'project.saveAsTemplate': { en: 'Save as Template', zh: '保存为模板', es: 'Guardar como Plantilla', fr: 'Enregistrer comme Modèle', de: 'Als Vorlage speichern', ja: 'テンプレートとして保存', ko: '템플릿으로 저장', pt: 'Salvar como Modelo', ar: 'حفظ كقالب', hi: 'टेम्पलेट के रूप में सहेजें', ru: 'Сохранить как шаблон', it: 'Salva come Modello' },
  'project.myTemplates': { en: 'My Templates', zh: '我的模板', es: 'Mis Plantillas', fr: 'Mes Modèles', de: 'Meine Vorlagen', ja: 'マイテンプレート', ko: '내 템플릿', pt: 'Meus Modelos', ar: 'قوالبي', hi: 'मेरे टेम्पलेट', ru: 'Мои шаблоны', it: 'I miei Modelli' },
  'project.templateMarketplace': { en: 'Template Marketplace', zh: '模板市场', es: 'Mercado de Plantillas', fr: 'Marché de Modèles', de: 'Vorlagen-Marktplatz', ja: 'テンプレートマーケット', ko: '템플릿 마켓플레이스', pt: 'Mercado de Modelos', ar: 'سوق القوالب', hi: 'टेम्पलेट मार्केटप्लेस', ru: 'Маркетплейс шаблонов', it: 'Marketplace Modelli' },

  // Incentive
  'incentive.title': { en: 'Study Incentives', zh: '研究激励', es: 'Incentivos del Estudio', fr: 'Incitations à l\'Étude', de: 'Studienanreize', ja: '研究インセンティブ', ko: '연구 인센티브', pt: 'Incentivos do Estudo', ar: 'حوافز الدراسة', hi: 'अध्ययन प्रोत्साहन', ru: 'Стимулы исследования', it: 'Incentivi dello Studio' },
  'incentive.enable': { en: 'Enable Incentives', zh: '启用激励', es: 'Activar Incentivos', fr: 'Activer les Incitations', de: 'Anreize aktivieren', ja: 'インセンティブを有効にする', ko: '인센티브 활성화', pt: 'Ativar Incentivos', ar: 'تفعيل الحوافز', hi: 'प्रोत्साहन सक्षम करें', ru: 'Включить стимулы', it: 'Attiva Incentivi' },
  'incentive.enableDesc': { en: 'Offer compensation to participants for completing your study.', zh: '为完成研究的参与者提供报酬。', es: 'Ofrece compensación a los participantes por completar tu estudio.', fr: 'Offrez une compensation aux participants pour compléter votre étude.', de: 'Bieten Sie Teilnehmern eine Vergütung an.', ja: '研究完了の参加者に報酬を提供します。', ko: '연구 완료 참가자에게 보상을 제공합니다.', pt: 'Ofereça compensação aos participantes.', ar: 'قدّم تعويضاً للمشاركين لإكمال دراستك.', hi: 'अध्ययन पूरा करने के लिए प्रतिभागियों को मुआवजा दें।', ru: 'Предложите компенсацию участникам.', it: 'Offri compensazione ai partecipanti.' },
  'incentive.type': { en: 'Incentive Type', zh: '激励类型', es: 'Tipo de Incentivo', fr: 'Type d\'Incitation', de: 'Anreiztyp', ja: 'インセンティブタイプ', ko: '인센티브 유형', pt: 'Tipo de Incentivo', ar: 'نوع الحافز', hi: 'प्रोत्साहन प्रकार', ru: 'Тип стимула', it: 'Tipo di Incentivo' },
  'incentive.fixed': { en: 'Fixed Payment', zh: '固定支付', es: 'Pago Fijo', fr: 'Paiement Fixe', de: 'Festbetrag', ja: '固定報酬', ko: '고정 지급', pt: 'Pagamento Fixo', ar: 'دفعة ثابتة', hi: 'निश्चित भुगतान', ru: 'Фиксированная оплата', it: 'Pagamento Fisso' },
  'incentive.fixedDesc': { en: 'Fixed amount upon study completion', zh: '完成研究后支付固定金额', es: 'Monto fijo al completar el estudio', fr: 'Montant fixe à la fin de l\'étude', de: 'Fester Betrag nach Abschluss', ja: '研究完了時の固定金額', ko: '연구 완료 시 고정 금액', pt: 'Valor fixo ao concluir o estudo', ar: 'مبلغ ثابت عند إكمال الدراسة', hi: 'अध्ययन पूरा होने पर निश्चित राशि', ru: 'Фиксированная сумма по завершении', it: 'Importo fisso al completamento' },
  'incentive.perResponse': { en: 'Per Response', zh: '按回复计', es: 'Por Respuesta', fr: 'Par Réponse', de: 'Pro Antwort', ja: '回答ごと', ko: '응답당', pt: 'Por Resposta', ar: 'لكل رد', hi: 'प्रति प्रतिक्रिया', ru: 'За ответ', it: 'Per Risposta' },
  'incentive.perResponseDesc': { en: 'Pay per completed questionnaire', zh: '每完成一份问卷支付', es: 'Pago por cuestionario completado', fr: 'Paiement par questionnaire complété', de: 'Zahlung pro ausgefülltem Fragebogen', ja: '完了したアンケートごとに支払い', ko: '완료된 설문지당 지불', pt: 'Pagamento por questionário concluído', ar: 'الدفع لكل استبيان مكتمل', hi: 'प्रत्येक प्रश्नावली पूर्ण करने पर भुगतान', ru: 'Оплата за каждую анкету', it: 'Pagamento per questionario completato' },
  'incentive.lottery': { en: 'Lottery / Raffle', zh: '抽奖', es: 'Sorteo', fr: 'Tirage au Sort', de: 'Verlosung', ja: '抽選', ko: '추첨', pt: 'Sorteio', ar: 'سحب / يانصيب', hi: 'लॉटरी / रैफल', ru: 'Лотерея', it: 'Lotteria / Estrazione' },
  'incentive.lotteryDesc': { en: 'Chance to win a prize', zh: '有机会赢得奖品', es: 'Oportunidad de ganar un premio', fr: 'Chance de gagner un prix', de: 'Chance auf einen Preis', ja: '賞品が当たるチャンス', ko: '상금 당첨 기회', pt: 'Chance de ganhar um prêmio', ar: 'فرصة للفوز بجائزة', hi: 'पुरस्कार जीतने का मौका', ru: 'Шанс выиграть приз', it: 'Possibilità di vincere un premio' },
  'incentive.amount': { en: 'Amount', zh: '金额', es: 'Monto', fr: 'Montant', de: 'Betrag', ja: '金額', ko: '금액', pt: 'Valor', ar: 'المبلغ', hi: 'राशि', ru: 'Сумма', it: 'Importo' },
  'incentive.currency': { en: 'Currency', zh: '货币', es: 'Moneda', fr: 'Devise', de: 'Währung', ja: '通貨', ko: '통화', pt: 'Moeda', ar: 'العملة', hi: 'मुद्रा', ru: 'Валюта', it: 'Valuta' },
  'incentive.description': { en: 'Description for Participants', zh: '参与者描述', es: 'Descripción para Participantes', fr: 'Description pour les Participants', de: 'Beschreibung für Teilnehmer', ja: '参加者向け説明', ko: '참여자 설명', pt: 'Descrição para Participantes', ar: 'وصف للمشاركين', hi: 'प्रतिभागियों के लिए विवरण', ru: 'Описание для участников', it: 'Descrizione per i Partecipanti' },
  'incentive.descriptionPlaceholder': { en: 'e.g., Receive a $10 Amazon gift card after completing all surveys', zh: '例如：完成所有问卷后可获得10美元亚马逊礼品卡', es: 'ej., Reciba una tarjeta regalo de $10 al completar todas las encuestas', fr: 'ex., Recevez une carte cadeau de 10$ après avoir complété tous les sondages', de: 'z.B., Erhalten Sie einen 10$ Amazon-Gutschein nach Abschluss', ja: '例：全アンケート完了後に$10のAmazonギフトカードを受け取れます', ko: '예: 모든 설문 완료 후 $10 아마존 기프트 카드 지급', pt: 'ex., Receba um vale-presente de $10 ao concluir todas as pesquisas', ar: 'مثال: احصل على بطاقة هدية بقيمة 10 دولارات بعد إكمال جميع الاستطلاعات', hi: 'उदा., सभी सर्वेक्षण पूरा करने पर $10 का अमेज़न गिफ्ट कार्ड प्राप्त करें', ru: 'напр., Получите подарочную карту Amazon на $10 после завершения', it: 'es., Ricevi una gift card Amazon da $10 dopo aver completato tutti i sondaggi' },
  'incentive.paymentMethod': { en: 'Payment Method', zh: '支付方式', es: 'Método de Pago', fr: 'Mode de Paiement', de: 'Zahlungsmethode', ja: '支払い方法', ko: '지불 방법', pt: 'Método de Pagamento', ar: 'طريقة الدفع', hi: 'भुगतान विधि', ru: 'Способ оплаты', it: 'Metodo di Pagamento' },
  'incentive.manualPayment': { en: 'Manual', zh: '手动', es: 'Manual', fr: 'Manuel', de: 'Manuell', ja: '手動', ko: '수동', pt: 'Manual', ar: 'يدوي', hi: 'मैनुअल', ru: 'Вручную', it: 'Manuale' },
  'incentive.manualPaymentDesc': { en: 'Contact participants directly', zh: '直接联系参与者', es: 'Contacte directamente', fr: 'Contactez directement', de: 'Direkt kontaktieren', ja: '参加者に直接連絡', ko: '참여자에게 직접 연락', pt: 'Contate diretamente', ar: 'تواصل مباشرة مع المشاركين', hi: 'प्रतिभागियों से सीधे संपर्क करें', ru: 'Свяжитесь с участниками напрямую', it: 'Contatta direttamente' },
  'incentive.paypalDesc': { en: 'Send via PayPal email', zh: '通过PayPal邮箱发送', es: 'Enviar por correo de PayPal', fr: 'Envoyer par email PayPal', de: 'Per PayPal-E-Mail senden', ja: 'PayPalメールで送信', ko: 'PayPal 이메일로 전송', pt: 'Enviar por email do PayPal', ar: 'إرسال عبر بريد PayPal', hi: 'PayPal ईमेल से भेजें', ru: 'Отправить через PayPal', it: 'Invia tramite email PayPal' },
  'incentive.giftCard': { en: 'Gift Card', zh: '礼品卡', es: 'Tarjeta Regalo', fr: 'Carte Cadeau', de: 'Geschenkkarte', ja: 'ギフトカード', ko: '기프트 카드', pt: 'Vale-Presente', ar: 'بطاقة هدية', hi: 'गिफ्ट कार्ड', ru: 'Подарочная карта', it: 'Gift Card' },
  'incentive.giftCardDesc': { en: 'Digital gift card codes', zh: '数字礼品卡代码', es: 'Códigos de tarjeta regalo digital', fr: 'Codes de carte cadeau numérique', de: 'Digitale Geschenkkarten-Codes', ja: 'デジタルギフトカードコード', ko: '디지털 기프트 카드 코드', pt: 'Códigos de vale-presente digital', ar: 'رموز بطاقات هدايا رقمية', hi: 'डिजिटल गिफ्ट कार्ड कोड', ru: 'Цифровые коды подарочных карт', it: 'Codici gift card digitali' },
  'incentive.bankTransfer': { en: 'Bank Transfer', zh: '银行转账', es: 'Transferencia Bancaria', fr: 'Virement Bancaire', de: 'Banküberweisung', ja: '銀行振込', ko: '은행 이체', pt: 'Transferência Bancária', ar: 'تحويل بنكي', hi: 'बैंक ट्रांसफर', ru: 'Банковский перевод', it: 'Bonifico Bancario' },
  'incentive.bankTransferDesc': { en: 'Direct bank deposit', zh: '直接银行存款', es: 'Depósito bancario directo', fr: 'Dépôt bancaire direct', de: 'Direkte Bankeinzahlung', ja: '銀行直接入金', ko: '직접 은행 입금', pt: 'Depósito bancário direto', ar: 'إيداع مصرفي مباشر', hi: 'सीधा बैंक जमा', ru: 'Прямой банковский депозит', it: 'Deposito bancario diretto' },
  'incentive.paymentInstructions': { en: 'Payment Instructions', zh: '付款说明', es: 'Instrucciones de Pago', fr: 'Instructions de Paiement', de: 'Zahlungsanweisungen', ja: '支払い方法の説明', ko: '지불 안내', pt: 'Instruções de Pagamento', ar: 'تعليمات الدفع', hi: 'भुगतान निर्देश', ru: 'Инструкции по оплате', it: 'Istruzioni di Pagamento' },
  'incentive.paymentInstructionsPlaceholder': { en: 'e.g., Payment will be processed within 7 business days via the selected method.', zh: '例如：付款将在7个工作日内通过所选方式处理。', es: 'ej., El pago se procesará en 7 días hábiles.', fr: 'ex., Le paiement sera traité sous 7 jours ouvrables.', de: 'z.B., Zahlung wird innerhalb von 7 Werktagen bearbeitet.', ja: '例：選択された方法で7営業日以内に処理されます。', ko: '예: 선택한 방법으로 7영업일 이내에 처리됩니다.', pt: 'ex., O pagamento será processado em 7 dias úteis.', ar: 'مثال: ستتم معالجة الدفع خلال 7 أيام عمل.', hi: 'उदा., चयनित विधि के माध्यम से 7 कार्य दिवसों में भुगतान संसाधित किया जाएगा।', ru: 'напр., Оплата будет обработана в течение 7 рабочих дней.', it: 'es., Il pagamento verrà elaborato entro 7 giorni lavorativi.' },
  'incentive.participantWillSee': { en: 'Participants will see:', zh: '参与者将看到：', es: 'Los participantes verán:', fr: 'Les participants verront:', de: 'Teilnehmer werden sehen:', ja: '参加者には以下が表示されます：', ko: '참여자에게 표시:', pt: 'Os participantes verão:', ar: 'سيرى المشاركون:', hi: 'प्रतिभागी देखेंगे:', ru: 'Участники увидят:', it: 'I partecipanti vedranno:' },
  'incentive.uponCompletion': { en: 'upon study completion', zh: '研究完成后', es: 'al completar el estudio', fr: 'à la fin de l\'étude', de: 'nach Abschluss der Studie', ja: '研究完了時', ko: '연구 완료 시', pt: 'ao concluir o estudo', ar: 'عند إكمال الدراسة', hi: 'अध्ययन पूरा होने पर', ru: 'по завершении исследования', it: 'al completamento dello studio' },
  'incentive.perResponseSuffix': { en: 'per completed questionnaire', zh: '每完成一份问卷', es: 'por cuestionario completado', fr: 'par questionnaire complété', de: 'pro ausgefülltem Fragebogen', ja: '完了したアンケートごと', ko: '완료된 설문지당', pt: 'por questionário concluído', ar: 'لكل استبيان مكتمل', hi: 'प्रत्येक प्रश्नावली पूर्ण करने पर', ru: 'за каждую заполненную анкету', it: 'per questionario completato' },
  'incentive.lotteryPrefix': { en: 'Chance to win', zh: '有机会赢取', es: 'Oportunidad de ganar', fr: 'Chance de gagner', de: 'Chance auf', ja: '当選のチャンス', ko: '당첨 기회', pt: 'Chance de ganhar', ar: 'فرصة للفوز بـ', hi: 'जीतने का मौका', ru: 'Шанс выиграть', it: 'Possibilità di vincere' },
  'incentive.paidVia': { en: 'Paid via', zh: '通过以下方式支付', es: 'Pagado vía', fr: 'Payé via', de: 'Bezahlt über', ja: '支払い方法', ko: '지급 방법', pt: 'Pago via', ar: 'الدفع عبر', hi: 'इसके माध्यम से भुगतान', ru: 'Оплата через', it: 'Pagato tramite' },
};

interface I18nContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const I18nContext = createContext<I18nContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
  dir: 'ltr',
});

export const useI18n = () => useContext(I18nContext);

export const I18nProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('easyresearch_lang') as Language;
    return saved && LANGUAGES.some(l => l.code === saved) ? saved : 'en';
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('easyresearch_lang', newLang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[key]?.[lang] || translations[key]?.en || key;
  }, [lang]);

  const dir = LANGUAGES.find(l => l.code === lang)?.dir || 'ltr';

  return (
    <I18nContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </I18nContext.Provider>
  );
};
